export const chapter17 = [
    { id: "u5_c17_01", native: "게임", english: "game", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_02", native: "관람(하다)", english: "watching (to watch)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_03", native: "낚시(하다)", english: "fishing (to fish)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_04", native: "다양(하다)", english: "various; diverse", unit: 5, chapter: 17, type: "adjective" },
    { id: "u5_c17_05", native: "~대/세대", english: "~ generation", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_06", native: "레저", english: "leisure", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_07", native: "뮤지컬", english: "musical", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_08", native: "바이올린", english: "violin", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_09", native: "스포츠", english: "sports", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_10", native: "시간이 나다", english: "to have time; to be free", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_11", native: "악기", english: "musical instrument", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_12", native: "암벽등반", english: "rock climbing", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_13", native: "연극", english: "play; theater performance", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_14", native: "연주(하다)", english: "performance (to perform)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_15", native: "음악회", english: "concert", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_16", native: "~ 이상", english: "~ or more", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_17", native: "인터넷", english: "internet", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_18", native: "조사(하다/되다)", english: "research; survey (to research / to be researched)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_19", native: "주로", english: "mainly; mostly", unit: 5, chapter: 17, type: "adverb" },
    { id: "u5_c17_20", native: "즐기다", english: "to enjoy", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_21", native: "초대권", english: "invitation ticket", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_22", native: "피아노", english: "piano", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_23", native: "활동", english: "activity", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_24", native: "헬스", english: "fitness; gym", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_25", native: "감독", english: "director", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_26", native: "곤", english: "difficulty; hardship", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_27", native: "공포", english: "horror; terror", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_28", native: "관객", english: "audience; spectator", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_29", native: "극장", english: "theater; movie theater", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_30", native: "매진(되다)", english: "sold out (to be sold out)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_31", native: "무섭다", english: "to be scary; to be frightening", unit: 5, chapter: 17, type: "adjective" },
    { id: "u5_c17_32", native: "미리", english: "in advance; beforehand", unit: 5, chapter: 17, type: "adverb" },
    { id: "u5_c17_33", native: "방금", english: "just now; a moment ago", unit: 5, chapter: 17, type: "adverb" },
    { id: "u5_c17_34", native: "배우", english: "actor; actress", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_35", native: "상영(하다/되다)", english: "screening (to screen / to be screened)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_36", native: "싫다", english: "to dislike; to hate", unit: 5, chapter: 17, type: "adjective" },
    { id: "u5_c17_37", native: "액션", english: "action", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_38", native: "어느", english: "which; some", unit: 5, chapter: 17, type: "determiner" },
    { id: "u5_c17_39", native: "제목", english: "title", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_40", native: "-(으)ㄴ/는/ㄹ 것 같다", english: "it seems that; it looks like", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_41", native: "조조할인", english: "early morning discount", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_42", native: "주연", english: "leading role; starring", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_43", native: "코미디/코메디", english: "comedy", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_44", native: "판매(하다/되다)", english: "sale (to sell / to be sold)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_45", native: "학생증", english: "student ID", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_46", native: "~회", english: "~ times; ~ performance", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_47", native: "~개월", english: "~ months", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_48", native: "개인", english: "individual; personal", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_49", native: "검색(하다)", english: "search (to search)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_50", native: "결제(하다/되다)", english: "payment (to pay / to be paid)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_51", native: "공연", english: "performance; show", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_52", native: "관심", english: "interest", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_53", native: "누르다", english: "to press; to push", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_54", native: "무용(하다)", english: "dance (to dance)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_55", native: "미술", english: "art; fine arts", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_56", native: "발레", english: "ballet", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_57", native: "방법", english: "method; way", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_58", native: "버튼", english: "button", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_59", native: "선택(하다)", english: "selection (to select)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_60", native: "연령", english: "age", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_61", native: "예매(하다/되다)", english: "reservation; booking (to reserve / to be booked)", unit: 5, chapter: 17, type: "verb" },
    { id: "u5_c17_62", native: "일반석", english: "regular seat; standard seat", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_63", native: "전시회", english: "exhibition", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_64", native: "정보", english: "information", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_65", native: "주소", english: "address", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_66", native: "티켓", english: "ticket", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_67", native: "행사", english: "event", unit: 5, chapter: 17, type: "noun" },
    { id: "u5_c17_68", native: "홈페이지", english: "homepage; website", unit: 5, chapter: 17, type: "noun" },
];
