export const chapter54 = [
  { id: "u14_c54_01", native: "갖추다", english: "to be equipped with", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_02", native: "개방(하다/되다)", english: "opening; open (to open/to be open)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_03", native: "거주(~하다)", english: "living; residing (to live; to reside)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_04", native: "노트북", english: "a laptop computer; “notebook”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_05", native: "단말기", english: "a terminal; a device attached to the end of a wire or cable", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_06", native: "달성(하다/되다)", english: "achievement; accomplishment (to achieve/to be achieved)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_07", native: "동력", english: "(electric) power; dynamic force; “power to move”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_08", native: "말투", english: "one’s way of speaking; one’s style of speaking; one’s manner of speaking", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_09", native: "몰두(하다)", english: "absorption; preoccupation; “submerged head” (to be preoccupied)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_10", native: "무선", english: "wireless; cordless; “no line”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_11", native: "민항기", english: "a civilian aircraft abbreviated form of 민간항공기", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_12", native: "발전(소)", english: "power generating (plant)", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_13", native: "방안", english: "a plan (to solve or cope with a problem); a device; a scheme", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_14", native: "보급(하다/되다)", english: "dissemination; spread (to disseminate/to be disseminated)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_15", native: "비롯한/비롯해서", english: "including", unit: 14, chapter: 54, type: "particle" },
  { id: "u14_c54_16", native: "생성(하다/되다)", english: "creation; formation (to create/to be created)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_17", native: "선보이다", english: "to present (something new); to show (something new); to unveil", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_18", native: "성과", english: "a result (of an effort); an outcome", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_19", native: "수소", english: "hydrogen", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_20", native: "스마트폰", english: "a smartphone", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_21", native: "시제품", english: "a trial product; “test product”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_22", native: "아이디어", english: "an idea", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_23", native: "알아맞히다", english: "to guess correctly; to make a good guess", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_24", native: "양산(하다/되다)", english: "mass production (to produce in large quantities/to be produced in large quantities)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_25", native: "연간", english: "annual; yearly", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_26", native: "연결(하다/되다)", english: "a connection; a link (to connect/to be connected)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_27", native: "연료", english: "a fuel; “burning material”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_28", native: "원자력", english: "nuclear energy; atomic energy; “atom power”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_29", native: "유치(하다)", english: "a lure or an enticement (to an event, investment, etc.); hosting (an event) (to invite/attract events, investment, etc.; to host an event)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_30", native: "육성(하다/되다)", english: "upbringing; rearing (to rear/to be reared)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_31", native: "이동(하다/되다)", english: "move; migration (to move/to be moved)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_32", native: "인공", english: "artificial; man-made", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_33", native: "인식(하다/되다)", english: "cognition; recognition; perception (to recognize; to perceive/to be recognized; to be perceived)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_34", native: "재생(하다/되다)", english: "reproduction; regeneration; replay (to reproduce/to be reproduced)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_35", native: "점유(하다/되다)", english: "occupying (of space) (to occupy/to be occupied)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_36", native: "접속(하다/되다)", english: "connection (to connect/to be connected)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_37", native: "조성(하다/되다)", english: "formation or creation (of a site for housing or a plant) (to form; to create/to be formed; to be created)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_38", native: "조작(하다/되다)", english: "operation; manipulation (to operate; to manipulate/to be operated; to be manipulated)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_39", native: "종목", english: "an item (of business); a (sporting) event; “type”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_40", native: "주목(하다)", english: "attention (to pay attention)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_41", native: "준공(하다/되다)", english: "completion of construction (to complete construction/construction to be completed)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_42", native: "지능", english: "intelligence; IQ", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_43", native: "지배(하다/되다)", english: "ruling; domination (to rule; to dominate/to be ruled; to be dominated)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_44", native: "차세대", english: "the next generation", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_45", native: "청사", english: "a government building", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_46", native: "체질", english: "fundamental physical constitution", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_47", native: "촬영(하다/되다)", english: "photographing; filming (to film/to be filmed)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_48", native: "출시(하다/되다)", english: "releasing (a product) to the market (to release to the market; to launch to the market/to be released to the market)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_49", native: "충전(하다/되다)", english: "(electric) charging (to charge/to be charged)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_50", native: "콘텐츠", english: "content", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_51", native: "태양광", english: "sunlight", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_52", native: "파악(하다/되다)", english: "grasp; hold; grip (to grasp; to understand/to be grasped; to be understood)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_53", native: "폭", english: "width; breadth", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_54", native: "표준화(하다/되다)", english: "standardization (to standardize/to be standardized)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_55", native: "풍력", english: "wind-powered; “wind power”", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_56", native: "플랜트", english: "a(n) (industrial) plant", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_57", native: "활성화(하다/시키다)", english: "vitalization; galvanization (to vitalize; to galvanize)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_58", native: "힘쓰다", english: "to strive; to make an effort", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_59", native: "내후년", english: "the year after next; two years from now", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_60", native: "~년도", english: "year ~", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_61", native: "도약", english: "a breakthrough; a solution", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_62", native: "돌파(하다)", english: "a breakthrough; (to break through; to exceed; to overcome)", unit: 14, chapter: 54, type: "verb" },
  { id: "u14_c54_63", native: "상업", english: "commerce; business", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_64", native: "와이파이 존", english: "a Wi-Fi zone", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_65", native: "우주", english: "the universe; outer space", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_66", native: "제대로", english: "properly", unit: 14, chapter: 54, type: "adverb" },
  { id: "u14_c54_67", native: "전략", english: "a strategy", unit: 14, chapter: 54, type: "noun" },
  { id: "u14_c54_68", native: "전지", english: "a battery; “electric pond”", unit: 14, chapter: 54, type: "noun" },
];
