export const chapter28 = [
  { id: "u7_c28_01", native: "~간", english: "between", unit: 7, chapter: 28, type: "particle" },
  { id: "u7_c28_02", native: "강하다", english: "to be strong", unit: 7, chapter: 28, type: "adjective" },
  { id: "u7_c28_03", native: "개성", english: "individuality", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_04", native: "고개", english: "the head", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_05", native: "공경(하다)", english: "reverence; respect; honor (to revere; to respect)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_06", native: "공손(하다)", english: "politeness; courteousness (to be polite; to be courteous)", unit: 7, chapter: 28, type: "adjective" },
  { id: "u7_c28_07", native: "굽히다", english: "to bend", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_08", native: "기성세대/구세대", english: "older generation; old generation", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_09", native: "꼬다", english: "to twist; to cross", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_10", native: "–나요", english: "an interrogative ending", unit: 7, chapter: 28, type: "particle" },
  { id: "u7_c28_11", native: "나이/연세(↑)(가) 들다", english: "to get old; “age gets in”", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_12", native: "노력(하다)", english: "an effort; an endeavor; hard work (to make an effort)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_13", native: "대화(하다)", english: "a conversation (to talk with)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_14", native: "들다", english: "to raise; to lift; to hold", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_15", native: "뜻(하다)", english: "meaning (to mean)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_16", native: "마음", english: "heart; mind", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_17", native: "방법", english: "a method", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_18", native: "방식", english: "a way; a style", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_19", native: "발음(하다/되다)", english: "pronunciation (to pronounce/to be pronounced)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_20", native: "버릇", english: "manners; a habit", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_21", native: "부르다", english: "to call; to name", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_22", native: "부지런하다/부지런히", english: "to be diligent/diligently", unit: 7, chapter: 28, type: "adjective" },
  { id: "u7_c28_23", native: "사투리/방언", english: "a dialect; vernacular", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_24", native: "실수(하다)", english: "a mistake (to make a mistake)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_25", native: "숙이다", english: "to bow; to bend one’s head (or upper body) forward", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_26", native: "신세대", english: "younger generation; “new generation”", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_27", native: "솔직(하다)", english: "frankness; candidness (to be frank; to be candid; to be straightforward)", unit: 7, chapter: 28, type: "adjective" },
  { id: "u7_c28_28", native: "손짓(하다)", english: "a hand gesture (to make a hand gesture)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_29", native: "악수(하다)", english: "shaking hands (to shake hands)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_30", native: "예절", english: "manners; etiquette", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_31", native: "외우다", english: "to memorize", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_32", native: "우연히", english: "by chance; incidentally", unit: 7, chapter: 28, type: "adverb" },
  { id: "u7_c28_33", native: "웃다", english: "to smile; to laugh", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_34", native: "의견", english: "an opinion", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_35", native: "이해(하다/되다)", english: "understanding; comprehension (to understand/to be understood)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_36", native: "자연스럽다", english: "to be natural", unit: 7, chapter: 28, type: "adjective" },
  { id: "u7_c28_37", native: "존경(하다)", english: "respect (to respect)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_38", native: "존댓말", english: "honorific language; honorific; “honoring language”", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_39", native: "주의(하다)", english: "a care; a caution (to be careful; to be cautious)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_40", native: "지키다", english: "to keep; to observe", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_41", native: "쳐다보다", english: "to look; to gaze", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_42", native: "통하다", english: "to communicate with; to be understood; “to flow freely”", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_43", native: "틀리다", english: "to be wrong; to be incorrect", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_44", native: "포옹(하다)", english: "a hug (to hug; to embrace)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_45", native: "표준말", english: "a standard language", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_46", native: "표현(하다/되다)", english: "an expression (to express/to be expressed)", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_47", native: "흔들다", english: "to shake; to wave", unit: 7, chapter: 28, type: "verb" },
  { id: "u7_c28_48", native: "에티켓", english: "etiquette", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_49", native: "여전히", english: "still", unit: 7, chapter: 28, type: "adverb" },
  { id: "u7_c28_50", native: "예의", english: "courtesy; manners; etiquette", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_51", native: "제스처", english: "a gesture", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_52", native: "반", english: "a class; a section (of a class)", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_53", native: "반말", english: "blunt language; impolite language; “half language”", unit: 7, chapter: 28, type: "noun" },
  { id: "u7_c28_54", native: "–지요", english: "a verb ending expressing intention or suggestion in a friendly manner", unit: 7, chapter: 28, type: "particle" },
];
