export const chapter32 = [
  { id: "u8_c32_01", native: "간식", english: "snacks; “between meals”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_02", native: "개인", english: "an individual; a private citizen", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_03", native: "–거든요", english: "informal sentence ending", unit: 8, chapter: 32, type: "particle" },
  { id: "u8_c32_04", native: "거르다", english: "to skip (a meal); to omit", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_05", native: "거의", english: "almost", unit: 8, chapter: 32, type: "adverb" },
  { id: "u8_c32_06", native: "건강관리사", english: "a health and nutrition counselor; a health-care specialist; “health managing specialist”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_07", native: "–게 하다", english: "have / make … do…", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_08", native: "골고루", english: "evenly; equally; a broad variety of", unit: 8, chapter: 32, type: "adverb" },
  { id: "u8_c32_09", native: "과자", english: "sweets; confectionary; cookies", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_10", native: "귀찮다", english: "to be annoying; to be bothersome; to be tiresome", unit: 8, chapter: 32, type: "adjective" },
  { id: "u8_c32_11", native: "균형([을] 잡다)", english: "balance (to balance)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_12", native: "긍정적(이다)", english: "affirmative; positive (to be affirmative; to be positive)", unit: 8, chapter: 32, type: "adjective" },
  { id: "u8_c32_13", native: "낙천적(이다)", english: "optimistic; happy-go-lucky (to be optimistic)", unit: 8, chapter: 32, type: "adjective" },
  { id: "u8_c32_14", native: "끌다", english: "to pull; to draw; to tow; to attract; to charm", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_15", native: "–는 데에", english: "for/in/at doing something", unit: 8, chapter: 32, type: "particle" },
  { id: "u8_c32_16", native: "다양(하다)", english: "variety (to be various; to be diverse)", unit: 8, chapter: 32, type: "adjective" },
  { id: "u8_c32_17", native: "땀([이] 나다/[을] 흘리다)", english: "sweat; perspiration (sweat breaks out / to sweat)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_18", native: "마련(하다)", english: "preparation; provision; plan (to prepare; to raise money; to plan)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_19", native: "마스크", english: "a face mask", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_20", native: "마을/촌", english: "a village", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_21", native: "맞이하다", english: "to meet; to greet; to welcome", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_22", native: "문의(하다)", english: "an inquiry (to inquire)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_23", native: "~ 및", english: "and (also); as well as", unit: 8, chapter: 32, type: "particle" },
  { id: "u8_c32_24", native: "벗어나다", english: "to get out of; to free oneself from", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_25", native: "보리/보리쌀", english: "barley", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_26", native: "비결", english: "a secret; a key; a knack", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_27", native: "비율", english: "a ratio; a percent; a proportion; “compared rate”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_28", native: "사탕", english: "candies", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_29", native: "섞다", english: "to mix; to blend; to mingle", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_30", native: "섭취(하다)", english: "intake; ingestion (to intake; to ingest)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_31", native: "소식(하다)", english: "light eating; “small meal” (to eat little)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_32", native: "식단", english: "a menu (schedule)", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_33", native: "–(으)ㄹ 만하다", english: "be worth (~ing)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_34", native: "야외", english: "outdoors; open air", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_35", native: "양/량", english: "an amount; a quantity", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_36", native: "영양소", english: "a nutrient", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_37", native: "오염(되다)", english: "contamination; pollution; “dirty dilution” (to be polluted)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_38", native: "오토캠핑", english: "car camping; “(auto)mobile camping”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_39", native: "올바르다", english: "to be right; to be rightful; to be upright; to be honest", unit: 8, chapter: 32, type: "adjective" },
  { id: "u8_c32_40", native: "운영(하다/되다)", english: "operation; management; administration; “operation and management” (to operate; to manage/to be operated)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_41", native: "움직이다", english: "to move; to stir; to shift", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_42", native: "유기농", english: "organic (farming)", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_43", native: "웰빙", english: "well-being", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_44", native: "잡곡", english: "cereals; minor grains; any grain but rice; “mixed grains”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_45", native: "장수(하다)", english: "longevity; “long life” (to live long)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_46", native: "적어도", english: "at least", unit: 8, chapter: 32, type: "adverb" },
  { id: "u8_c32_47", native: "전문가", english: "a specialist; a professional", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_48", native: "지방", english: "fat", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_49", native: "직접", english: "direct(ly); firsthand; “direct contact”", unit: 8, chapter: 32, type: "adverb" },
  { id: "u8_c32_50", native: "진단(하다)", english: "a diagnosis (to diagnose)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_51", native: "참여(하다)", english: "participation (to participate; to take part in)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_52", native: "채식(하다)", english: "vegetarian diet; “vegetable eating” (to live on vegetables)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_53", native: "체지방", english: "body fat", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_54", native: "초콜릿", english: "chocolate", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_55", native: "태도", english: "an attitude", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_56", native: "편식", english: "unhealthy diet; unhealthy dietary preference; poor eating (habit); “skewed eating”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_57", native: "프로그램", english: "a program", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_58", native: "해소(하다)", english: "a solution; a settlement; a dissolution “solving and quenching” (to solve; to settle; to dissolve)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_59", native: "효과", english: "effect; effectiveness", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_60", native: "노인", english: "an aged person; elderly; the aged; “old person”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_61", native: "인스턴트 식품", english: "fast food; precooked food; “instant food”", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_62", native: "자연", english: "nature", unit: 8, chapter: 32, type: "noun" },
  { id: "u8_c32_63", native: "조절(하다)", english: "regulation; adjustment; control; tuning (to regulate; to adjust; to control; to tune)", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_64", native: "아/어 보이다", english: "to appear to be …; to seem to be …", unit: 8, chapter: 32, type: "verb" },
  { id: "u8_c32_65", native: "군것질(하다)", english: "eating between meals (to eat between meals)", unit: 8, chapter: 32, type: "verb" },
];
