export const chapter22 = [
    { id: "u6_c22_01", native: "결레질(하다)", english: "cleaning (to clean the floor)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_02", native: "나누다", english: "to divide; to share", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_03", native: "놓다", english: "to put; to place; to leave", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_04", native: "다림질(하다)", english: "ironing (to iron)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_05", native: "돌보다", english: "to look after; to take care of", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_06", native: "막내", english: "youngest (child/sibling)", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_07", native: "먼지", english: "dust", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_08", native: "버리다", english: "to throw away; to discard", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_09", native: "벗다", english: "to take off (clothes/shoes)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_10", native: "살림(하다)", english: "housekeeping; living (to keep house)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_11", native: "서로", english: "each other; mutually", unit: 6, chapter: 22, type: "adverb" },
    { id: "u6_c22_12", native: "쓰레기", english: "trash; garbage", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_13", native: "쓸다", english: "to sweep", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_14", native: "장(을) 보다", english: "to go grocery shopping", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_15", native: "떨다/털다", english: "to shake off; to dust", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_16", native: "항상", english: "always", unit: 6, chapter: 22, type: "adverb" },
    { id: "u6_c22_17", native: "혼자(서)", english: "alone; by oneself", unit: 6, chapter: 22, type: "adverb" },
    { id: "u6_c22_18", native: "관리비", english: "maintenance fee", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_19", native: "관리사무소", english: "management office", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_20", native: "기분", english: "mood; feeling", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_21", native: "기쁘다", english: "to be glad; to be happy", unit: 6, chapter: 22, type: "adjective" },
    { id: "u6_c22_22", native: "나쁘다", english: "to be bad", unit: 6, chapter: 22, type: "adjective" },
    { id: "u6_c22_23", native: "난방", english: "heating", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_24", native: "문제", english: "problem", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_25", native: "변기", english: "toilet bowl", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_26", native: "보일러", english: "boiler; heating system", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_27", native: "불친절(하다)", english: "unfriendly; unkind", unit: 6, chapter: 22, type: "adjective" },
    { id: "u6_c22_28", native: "새다", english: "to leak", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_29", native: "수도", english: "water supply; faucet", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_30", native: "수리(하다)", english: "repair (to repair)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_31", native: "슬프다", english: "to be sad", unit: 6, chapter: 22, type: "adjective" },
    { id: "u6_c22_32", native: "이미", english: "already", unit: 6, chapter: 22, type: "adverb" },
    { id: "u6_c22_33", native: "전기", english: "electricity", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_34", native: "-지", english: "question ending (seeking agreement)", unit: 6, chapter: 22, type: "particle" },
    { id: "u6_c22_35", native: "처리(하다/되다)", english: "handling; processing (to handle / to be handled)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_36", native: "화(가 나다)", english: "anger (to get angry)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_37", native: "-거나/든지", english: "or; whether...or", unit: 6, chapter: 22, type: "particle" },
    { id: "u6_c22_38", native: "교육", english: "education", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_39", native: "-기 위해서", english: "in order to; for the purpose of", unit: 6, chapter: 22, type: "particle" },
    { id: "u6_c22_40", native: "~네", english: "I see that... (surprise/realization)", unit: 6, chapter: 22, type: "particle" },
    { id: "u6_c22_41", native: "물가", english: "prices; cost of living", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_42", native: "~비", english: "~ cost; ~ expense", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_43", native: "빛", english: "light", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_44", native: "식비", english: "food expenses", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_45", native: "아끼다", english: "to save; to economize; to cherish", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_46", native: "오락", english: "entertainment; recreation", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_47", native: "오르다", english: "to rise; to go up", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_48", native: "외식", english: "eating out", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_49", native: "월급", english: "monthly salary; paycheck", unit: 6, chapter: 22, type: "noun" },
    { id: "u6_c22_50", native: "~을/를 위해(서)", english: "for the sake of; for", unit: 6, chapter: 22, type: "particle" },
    { id: "u6_c22_51", native: "자꾸", english: "repeatedly; again and again", unit: 6, chapter: 22, type: "adverb" },
    { id: "u6_c22_52", native: "저축/저금(하다)", english: "savings (to save money)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_53", native: "절약(하다)", english: "saving; economizing (to save)", unit: 6, chapter: 22, type: "verb" },
    { id: "u6_c22_54", native: "줄이다", english: "to reduce; to cut down", unit: 6, chapter: 22, type: "verb" },
];
