export const chapter42 = [
  { id: "u11_c42_01", native: "가수", english: "a singer", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_02", native: "거리", english: "a street", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_03", native: "고속철(도)/KTX", english: "a high-speed train/Korea Train eXpress; “high-speed rail”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_04", native: "군함", english: "a warship; “military battleship”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_05", native: "그네타기", english: "swinging", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_06", native: "그립다", english: "to miss (a person)", unit: 11, chapter: 42, type: "adjective" },
  { id: "u11_c42_07", native: "기지", english: "a (military) base, a station", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_08", native: "벚꽃", english: "cherry blossoms; “cherry flower”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_09", native: "별", english: "a star", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_10", native: "(보름)달", english: "the (full) moon", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_11", native: "불꽃놀이", english: "fireworks; “fire flower play”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_12", native: "사랑(하다/받다)", english: "love (to love/to be loved)", unit: 11, chapter: 42, type: "verb" },
  { id: "u11_c42_13", native: "사정", english: "circumstances; a situation", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_14", native: "소극장", english: "a small-scale theater", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_15", native: "연날리기", english: "kite flying", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_16", native: "연인", english: "a lover; a person in a romantic relationship", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_17", native: "열다/열리다", english: "to hold (an event)/to be held", unit: 11, chapter: 42, type: "verb" },
  { id: "u11_c42_18", native: "예술", english: "art; “artistic skill”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_19", native: "오곡밥", english: "a five-grain meal (that consists of rice, barley, millet, bean, and proso millet)", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_20", native: "임시", english: "temporary", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_21", native: "장터", english: "a marketplace", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_22", native: "전시품", english: "an exhibit; a floor sample", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_23", native: "전야제", english: "an event on the eve (of a festival, etc.)", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_24", native: "절(하다)", english: "a traditional Korean bow; a deep bow", unit: 11, chapter: 42, type: "verb" },
  { id: "u11_c42_25", native: "젊은이", english: "a youth; a young person", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_26", native: "조선시대", english: "the Joseon Dynasty period", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_27", native: "정월 대보름", english: "the day of the first full moon in the lunar year", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_28", native: "줄타기", english: "tightrope walking; “rope riding”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_29", native: "지다", english: "to set (the sun/the moon/a star)", unit: 11, chapter: 42, type: "verb" },
  { id: "u11_c42_30", native: "초가집", english: "a thatched-roof house; thatched house", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_31", native: "카페", english: "a cafe", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_32", native: "킬로미터", english: "kilometer; km", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_33", native: "태국", english: "Thailand", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_34", native: "파전", english: "green onion pancake; scallion pancake", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_35", native: "펜션", english: "a pension; a small European-style hotel; a vacation house", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_36", native: "해", english: "the sun", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_37", native: "해(산)물", english: "seafood; “things from the sea”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_38", native: "혼례", english: "a (traditional) wedding", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_39", native: "화가", english: "a painter; “picture professional”", unit: 11, chapter: 42, type: "noun" },
  { id: "u11_c42_40", native: "화랑/갤러리", english: "an art gallery; “picture gallery”", unit: 11, chapter: 42, type: "noun" },
];
