export const chapter24 = [
    { id: "u6_c24_01", native: "공병", english: "engineer (military branch)", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_02", native: "군대", english: "military; army", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_03", native: "기갑", english: "armored (branch)", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_04", native: "까다롭다", english: "to be picky; to be strict", unit: 6, chapter: 24, type: "adjective" },
    { id: "u6_c24_05", native: "병과", english: "military branch; specialty", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_06", native: "보병", english: "infantry", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_07", native: "복무(하다)", english: "military service (to serve)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_08", native: "상관", english: "superior; senior officer", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_09", native: "여군", english: "female soldier", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_10", native: "의무", english: "duty; obligation", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_11", native: "입대(하다)", english: "enlistment (to enlist)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_12", native: "전방", english: "front line", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_13", native: "제대(하다)", english: "discharge (to be discharged)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_14", native: "지원(하다)", english: "support; application (to apply)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_15", native: "통신(하다)", english: "communication (to communicate)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_16", native: "포병", english: "artillery", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_17", native: "후방", english: "rear area", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_18", native: "훈련(하다/받다)", english: "training (to train / to receive training)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_19", native: "훈련소", english: "training center; boot camp", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_20", native: "휴가", english: "leave; vacation", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_21", native: "휴학(하다)", english: "leave of absence (to take leave)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_22", native: "교관", english: "instructor; drill instructor", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_23", native: "교대(하다)", english: "shift change (to change shifts)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_24", native: "군화", english: "military boots", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_25", native: "권총", english: "pistol", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_26", native: "대검", english: "bayonet", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_27", native: "던지다", english: "to throw", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_28", native: "메다", english: "to carry on shoulder; to wear (bag)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_29", native: "방독면", english: "gas mask", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_30", native: "방탄헬멧", english: "bulletproof helmet", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_31", native: "보급품", english: "supplies; provisions", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_32", native: "보초(서다)", english: "guard duty (to stand guard)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_33", native: "소총", english: "rifle", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_34", native: "수류탄", english: "hand grenade", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_35", native: "수통", english: "canteen; water bottle", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_36", native: "신체검사(하다)", english: "physical examination (to have a physical)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_37", native: "쓰다", english: "to write; to use", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_38", native: "완전무장(하다)", english: "full combat gear (to be fully armed)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_39", native: "윗몸 일으키기", english: "sit-up", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_40", native: "유격훈련", english: "guerrilla training", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_41", native: "-(으/느)나고 하다", english: "to say that one is ~ing", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_42", native: "-(으)라고 하다", english: "to tell someone to do", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_43", native: "-자고 하다", english: "to suggest doing", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_44", native: "전투훈련", english: "combat training", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_45", native: "제식훈련", english: "drill training; close-order drill", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_46", native: "집합(하다)", english: "assembly (to assemble)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_47", native: "천막/텐트", english: "tent", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_48", native: "체력훈련", english: "physical training", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_49", native: "총알", english: "bullet", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_50", native: "탄약", english: "ammunition", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_51", native: "팔 굽혀 펴기", english: "push-up", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_52", native: "행군(하다)", english: "march (to march)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_53", native: "헬기/헬리콥터", english: "helicopter", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_54", native: "화생방훈련", english: "CBRN training (chemical, biological, radiological, nuclear)", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_55", native: "군수과", english: "logistics section", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_56", native: "담당(하다)", english: "in charge (to be in charge)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_57", native: "대대", english: "battalion", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_58", native: "~밖에 + negative verb", english: "only; nothing but", unit: 6, chapter: 24, type: "particle" },
    { id: "u6_c24_59", native: "배치(하다/되다)", english: "assignment; deployment (to assign / to be assigned)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_60", native: "번역(하다/되다)", english: "translation (to translate / to be translated)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_61", native: "부사관", english: "non-commissioned officer (NCO)", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_62", native: "분대", english: "squad", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_63", native: "분대장", english: "squad leader", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_64", native: "사단", english: "division", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_65", native: "소대", english: "platoon", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_66", native: "소속(되다)", english: "affiliation (to belong to)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_67", native: "작전과", english: "operations section", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_68", native: "정보과", english: "intelligence section", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_69", native: "중대", english: "company", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_70", native: "여단", english: "brigade", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_71", native: "연대", english: "regiment", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_72", native: "인사과", english: "personnel section", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_73", native: "일정", english: "schedule; itinerary", unit: 6, chapter: 24, type: "noun" },
    { id: "u6_c24_74", native: "통역(하다)", english: "interpretation (to interpret)", unit: 6, chapter: 24, type: "verb" },
    { id: "u6_c24_75", native: "합동", english: "joint; combined", unit: 6, chapter: 24, type: "noun" },
];
