export const chapter34 = [
  { id: "u9_c34_01", native: "강의(하다)", english: "a lecture (to give a lecture; to lecture)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_02", native: "~같이/처럼 /같은", english: "like", unit: 9, chapter: 34, type: "particle" },
  { id: "u9_c34_03", native: "건축공학", english: "architectural engineering", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_04", native: "경영학", english: "(the study of) business administration", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_05", native: "경제학", english: "(the study of) economics", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_06", native: "과정/코스", english: "a course; curriculum", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_07", native: "국문학", english: "(the study of ) Korean literature", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_08", native: "그만두다", english: "to quit; to stop; to give up", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_09", native: "등록(하다)", english: "registration (to register)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_10", native: "등록금", english: "tuition; “registration money”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_11", native: "마치다", english: "to finish; to end; to complete", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_12", native: "~ 말고/–지 말고", english: "(do) not … but", unit: 9, chapter: 34, type: "particle" },
  { id: "u9_c34_13", native: "박사", english: "a doctoral degree; a person with a Ph.D. (degree)", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_14", native: "복수전공(하다)", english: "double major (to double-major in)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_15", native: "복학(하다)", english: "coming back to school (from a temporary leave); “recovering school” (to come back to school)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_16", native: "부담(하다/되다)", english: "a burden (to bear a burden/to be burdensome)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_17", native: "부전공(하다)", english: "a minor (area/study); “secondary major” (to minor in ~)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_18", native: "부족(하다)", english: "lacking; insufficiency; “not enough” (to lack; to be insufficient)", unit: 9, chapter: 34, type: "adjective" },
  { id: "u9_c34_19", native: "수강(하다)", english: "taking/attending a lecture/course; “receiving a lecture” (to take a lecture/course)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_20", native: "신문방송학", english: "(the study of) journalism; “study of newspapers and broadcasting”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_21", native: "신입생", english: "a freshman; “newly entering student”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_22", native: "심리학", english: "(the study of) psychology; “study of mentality”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_23", native: "아르바이트", english: "a part-time job; an odd job (from the German word arbeit)", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_24", native: "어학 연수", english: "foreign language study (abroad); “language research and study”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_25", native: "어학원", english: "a language institute", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_26", native: "영문학", english: "(the study of) English literature", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_27", native: "–(으)면 –(으)ㄹ수록", english: "the more … (the more)", unit: 9, chapter: 34, type: "particle" },
  { id: "u9_c34_28", native: "인턴(사원)", english: "an intern", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_29", native: "일자리", english: "a job; “work spot”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_30", native: "자격", english: "a qualification", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_31", native: "자격증", english: "a certificate; a license", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_32", native: "자취(하다)", english: "living away from one’s family and cooking food for oneself; self boarding; “self-cooking” (to cook food for oneself)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_33", native: "전공(하다)", english: "a major (to major in)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_34", native: "제공(하다/되다)", english: "providing (to provide/to be provided)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_35", native: "충분(하다)", english: "sufficiency (to be enough; to be sufficient)", unit: 9, chapter: 34, type: "adjective" },
  { id: "u9_c34_36", native: "취업/취직(하다)", english: "getting a job; employment; “acquiring a job” (to get a job; to be employed)", unit: 9, chapter: 34, type: "verb" },
  { id: "u9_c34_37", native: "컴퓨터공학", english: "(the study of) computer engineering", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_38", native: "축제", english: "a festival “celebrative ritual”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_39", native: "학비", english: "a school expense; tuition", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_40", native: "학사", english: "a bachelor’s (degree); a person with a bachelor’s (degree)", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_41", native: "학생회", english: "a student association; the student body; “students meeting”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_42", native: "학위", english: "an academic degree", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_43", native: "학점", english: "(college) credit; a unit; “learning points”", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_44", native: "회화", english: "a conversation", unit: 9, chapter: 34, type: "noun" },
  { id: "u9_c34_45", native: "화학", english: "(the study of) chemistry", unit: 9, chapter: 34, type: "noun" },
];
