export const chapter5 = [
    { id: "u2_c5_01", native: "가끔", english: "sometimes; occasionally", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_02", native: "~까지", english: "till; until; by", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_03", native: "끝나다", english: "to end; to be over", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_04", native: "매일", english: "every day", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_05", native: "반", english: "a half; half of", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_06", native: "~번", english: "(a number of) times; number~", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_07", native: "보내다", english: "to send", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_08", native: "~부터", english: "from (time/place)", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_09", native: "~분", english: "minute", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_10", native: "~시", english: "hour; o'clock", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_11", native: "시간", english: "an hour (duration); time", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_12", native: "시작(하다)", english: "to start; to begin", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_13", native: "언제", english: "when", unit: 2, chapter: 5, type: "pronoun" },
    { id: "u2_c5_14", native: "얼마나", english: "how much; how many; how long", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_15", native: "~에", english: "at; in; on; to (location/time)", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_16", native: "오전", english: "a.m.; morning", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_17", native: "오후", english: "p.m.; afternoon", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_18", native: "자주", english: "often; frequently", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_19", native: "저녁", english: "evening; dinner", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_20", native: "점심", english: "lunch; lunch time", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_21", native: "~주/~주일", english: "a week", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_22", native: "~쯤", english: "about; approximately", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_23", native: "군복", english: "a military uniform", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_24", native: "늘", english: "always; all the time", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_25", native: "다음", english: "next; the following", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_26", native: "돌아가다", english: "to return; to go back", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_27", native: "오다", english: "to come", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_28", native: "마시다", english: "to drink", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_29", native: "말하기", english: "speaking", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_30", native: "샤워(하다)", english: "to take a shower", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_31", native: "세수(하다)", english: "to wash one's face", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_32", native: "수업을 듣다", english: "to take a class; to listen to a class", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_33", native: "씻다", english: "to wash; to rinse", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_34", native: "-아서/-어서", english: "and then; because; so", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_35", native: "아침", english: "a.m.; morning; breakfast", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_36", native: "~에/~에서", english: "at; in; from (location)", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_37", native: "연습(하다)", english: "to practice", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_38", native: "이를 닦다", english: "to brush one's teeth", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_39", native: "일어나다", english: "to get up; to wake up", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_40", native: "입다", english: "to wear (clothes)", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_41", native: "정도", english: "about; approximately; degree", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_42", native: "가르치다", english: "to teach", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_43", native: "금요일", english: "Friday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_44", native: "너(↓)", english: "you (casual)", unit: 2, chapter: 5, type: "pronoun" },
    { id: "u2_c5_45", native: "~년", english: "a year", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_46", native: "등산(하다)", english: "to hike; hiking", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_47", native: "매주", english: "every week", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_48", native: "목요일", english: "Thursday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_49", native: "밤", english: "night; the nighttime", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_50", native: "수영(하다)", english: "to swim; swimming", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_51", native: "수요일", english: "Wednesday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_52", native: "~에게/~한테/~께(↑)", english: "to (person) - honorific", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_53", native: "~월", english: "a month", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_54", native: "월요일", english: "Monday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_55", native: "~일", english: "a day (date)", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_56", native: "일요일", english: "Sunday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_57", native: "일찍", english: "early", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_58", native: "~전에/-기 전에", english: "before; prior to", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_59", native: "지난", english: "last; the past", unit: 2, chapter: 5, type: "determiner" },
    { id: "u2_c5_60", native: "지내다", english: "to live; to stay; to get along", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_61", native: "천", english: "cloth; about (approx)", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_62", native: "토요일", english: "Saturday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_63", native: "함께", english: "together", unit: 2, chapter: 5, type: "adverb" },
    { id: "u2_c5_64", native: "화요일", english: "Tuesday", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_65", native: "~후에/-(으)니 후에", english: "after", unit: 2, chapter: 5, type: "particle" },
    { id: "u2_c5_66", native: "하루", english: "a day", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_67", native: "마시다", english: "to drink", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_68", native: "세수(하다)", english: "to wash one's face", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_69", native: "씻다", english: "to wash; to rinse", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_70", native: "이를 닦다", english: "to brush one's teeth", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_71", native: "입다", english: "to wear (clothes)", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_72", native: "일어나다", english: "to get up; to wake up; to rise", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_73", native: "가르치다", english: "to teach", unit: 2, chapter: 5, type: "verb" },
    { id: "u2_c5_74", native: "군복", english: "a military uniform; “military clothes”", unit: 2, chapter: 5, type: "noun" },
    { id: "u2_c5_75", native: "너(↓)", english: "you (casual)", unit: 2, chapter: 5, type: "pronoun" },
];
