export const chapter39 = [
  { id: "u10_c39_01", native: "강도", english: "a robber", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_02", native: "거리", english: "distance; space", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_03", native: "건널목", english: "a crossing; “crossing neck”", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_04", native: "겁(주다/먹다)", english: "fear; fright (to threaten; “to give fear”/to be frightened; “to eat fear”)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_05", native: "괴롭히다", english: "to harass; to afflict; to torment", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_06", native: "그러니까", english: "therefore; thus; and so", unit: 10, chapter: 39, type: "adverb" },
  { id: "u10_c39_07", native: "금품", english: "money and valuables", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_08", native: "단속(하다)", english: "crackdown (to crack down)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_09", native: "도둑", english: "a thief; a burglar", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_10", native: "도둑질(하다)", english: "burglary; stealing (to steal; to burglarize)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_11", native: "도로", english: "a road; a street", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_12", native: "도망가다/도망치다", english: "to escape; to flee; to run away", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_13", native: "당하다", english: "to suffer", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_14", native: "마구", english: "carelessly; recklessly; relentlessly", unit: 10, chapter: 39, type: "adverb" },
  { id: "u10_c39_15", native: "목격자", english: "an eyewitness", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_16", native: "몸싸움(하다/벌이다)", english: "a fight (involving grabbing, pushing, shoving, etc.); “body fight” (to have a physical fight)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_17", native: "무단", english: "without permission; without warning; without notice", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_18", native: "벌금", english: "a fine; a penalty; a forfeit “punishment money”", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_19", native: "벌이다", english: "to start (a fight); to stage", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_20", native: "범인", english: "a criminal; a culprit", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_21", native: "법", english: "the law; piece of legislation", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_22", native: "복면", english: "a (ski) mask", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_23", native: "불량(하다)", english: "delinquency; faulty; “not good” (to be delinquent; to be bad)", unit: 10, chapter: 39, type: "adjective" },
  { id: "u10_c39_24", native: "빼앗다/빼앗기다", english: "to rob; to strip/to be robbed", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_25", native: "사건", english: "a (criminal) incident; an affair; a case", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_26", native: "상당하다/상당히", english: "to be considerable/considerably; remarkably", unit: 10, chapter: 39, type: "adjective" },
  { id: "u10_c39_27", native: "상습적(으로)", english: "habitual(ly)", unit: 10, chapter: 39, type: "adverb" },
  { id: "u10_c39_28", native: "상황", english: "a situation; condition", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_29", native: "소매치기(하다)", english: "a pickpocket; “pocket hitting” (to pickpocket)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_30", native: "순서", english: "an order; sequence", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_31", native: "정지(하다)", english: "stop; halt (to stop; to halt)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_32", native: "제한(하다)", english: "a limit; restriction (to limit; to restrict)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_33", native: "잔소리(하다)", english: "nagging; “petty sound” (to nag)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_34", native: "지나(가)다", english: "to pass by; to go by; “pass and go”", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_35", native: "차다", english: "to kick", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_36", native: "체포(하다/되다)", english: "arrest; apprehension; capture (to arrest/to be arrested)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_37", native: "퇴학(시키다/당하다)", english: "expulsion (from school) (to expel a student from school/to be expelled from school)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_38", native: "폭력", english: "violence; brute force; “violent force”", unit: 10, chapter: 39, type: "noun" },
  { id: "u10_c39_39", native: "폭행(하다)", english: "a (physical) assault; a violent act (to do violence; to assault)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_40", native: "해결(하다/되다)", english: "a solution; a settlement (to solve/to be solved)", unit: 10, chapter: 39, type: "verb" },
  { id: "u10_c39_41", native: "협박(하다)", english: "a threat; blackmail; intimidation (to threaten; to intimidate)", unit: 10, chapter: 39, type: "verb" },
];
