export const chapter36 = [
  { id: "u9_c36_01", native: "an attributive form + 줄 몰랐다", english: "I wasn’t aware; I didn’t know", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_02", native: "an attributive form + 줄 알았다", english: "I thought … (but I was wrong)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_03", native: "간단히", english: "simply; briefly", unit: 9, chapter: 36, type: "adverb" },
  { id: "u9_c36_04", native: "개업(하다)", english: "opening of a business; commencement of practice (to open a business)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_05", native: "규모", english: "a scale; a scope", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_06", native: "구내", english: "premises; precinct; a compound; “inside the structure”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_07", native: "노후", english: "one’s old age; “old after”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_08", native: "능력", english: "ability; capability; competence", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_09", native: "답답하다", english: "to be stuffy; to be suffocating", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_10", native: "답장(하다)", english: "a (written) reply; a reply letter (to reply)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_11", native: "대기업", english: "a large enterprise; a conglomerate; “large business”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_12", native: "대리", english: "a deputy; “proxy”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_13", native: "대인관계", english: "interpersonal relationship; social network", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_14", native: "넓히다", english: "to widen; to expand", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_15", native: "보고서", english: "a written report", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_16", native: "보너스", english: "a bonus", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_17", native: "반복(하다/되다)", english: "repetition; reiteration (to repeat; to reiterate; to do over again/to be repeated)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_18", native: "밤새", english: "all night long; through the night", unit: 9, chapter: 36, type: "adverb" },
  { id: "u9_c36_19", native: "불만", english: "dissatisfaction; discontent", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_20", native: "불만족(스럽다)", english: "dissatisfaction; discontent (to dissatisfy/to be dissatisfying)", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_21", native: "바이어", english: "a buyer; a buying agent from abroad", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_22", native: "사내", english: "the compound (of a company); “inside the company”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_23", native: "사표/사직서([를] 내다)", english: "resignation; a letter of resignation (to resign)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_24", native: "상사", english: "one’s superior; a senior official", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_25", native: "성공(하다)", english: "success; achievement; accomplishment (to succeed; to be successful)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_26", native: "수입(하다)", english: "import (to import)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_27", native: "수출(하다)", english: "export; exportation (to export)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_28", native: "야근(하다)", english: "night duty; night work; night shift (to take night duty; to work overtime into the night)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_29", native: "여유(롭다)", english: "a surplus; a margin; time (to spare); (to be free [of obligations])", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_30", native: "연금", english: "a pension; “annual money”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_31", native: "연봉", english: "an annual salary", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_32", native: "이직(하다)", english: "change of occupation (to change one’s occupation)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_33", native: "익숙하다", english: "to be familiar; to be well acquainted", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_34", native: "인생", english: "one’s life; “human life”", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_35", native: "인정(하다/받다)", english: "recognition; acknowledgment; confirmation; approval (to recognize; to admit; to approve/to be recognized)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_36", native: "일과", english: "a daily task; daily work; (daily) routine", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_37", native: "자영업", english: "self-run business; self-employment", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_38", native: "(자원)봉사(하다)", english: "volunteer service (to serve as a volunteer)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_39", native: "자유(롭다)", english: "freedom; liberty (to be free; to be liberal; to be unrestricted)", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_40", native: "작성(하다/되다)", english: "filling out (a form) (to fill out/to be filled out)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_41", native: "정년퇴직", english: "retirement (at normal retirement age)", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_42", native: "정장(하다)", english: "full dress; formal dress; “correct dress” (to wear full dress)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_43", native: "제~", english: "optional prefix for an ordinal", unit: 9, chapter: 36, type: "particle" },
  { id: "u9_c36_44", native: "지겹다", english: "to be boring; to be tedious; to be wearisome; to be tiresome", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_45", native: "지원(하다)", english: "support; aid (to support)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_46", native: "창업(하다)", english: "inauguration of an enterprise; foundation of a business (to found a business)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_47", native: "퇴직금", english: "a retirement allowance; a retirement benefit", unit: 9, chapter: 36, type: "noun" },
  { id: "u9_c36_48", native: "활용(하다)", english: "use; utilization (to use; to utilize)", unit: 9, chapter: 36, type: "verb" },
  { id: "u9_c36_49", native: "만족(하다/스럽다)", english: "satisfaction (to satisfy/to be satisfying)", unit: 9, chapter: 36, type: "adjective" },
  { id: "u9_c36_50", native: "–다(가) 보니(까)", english: "conjunctive ending used to express the speaker’s own discovery/realization of something while engaging in an activity", unit: 9, chapter: 36, type: "particle" },
  { id: "u9_c36_51", native: "–다고", english: "for a statement used as the object in a sentence", unit: 9, chapter: 36, type: "particle" },
  { id: "u9_c36_52", native: "–은/는 대로", english: "as soon as", unit: 9, chapter: 36, type: "particle" },
  { id: "u9_c36_53", native: "–(이)나", english: "a noun marker", unit: 9, chapter: 36, type: "particle" },
];
