export const chapter11 = [
    { id: "u3_c11_01", native: "~곳", english: "place", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_02", native: "교포", english: "Korean living abroad; overseas Korean", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_03", native: "근무(하다)", english: "work; duty (to work)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_04", native: "그림", english: "picture; painting; drawing", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_05", native: "다니다", english: "to attend; to go regularly", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_06", native: "대부분", english: "most; majority", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_07", native: "-(으)ㄹ 때", english: "when; at the time when", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_08", native: "만", english: "only", unit: 3, chapter: 11, type: "particle" },
    { id: "u3_c11_09", native: "사업(하다)", english: "business (to do business)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_10", native: "사회", english: "society", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_11", native: "~세(대)", english: "~ generation", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_12", native: "정말", english: "really; truly", unit: 3, chapter: 11, type: "adverb" },
    { id: "u3_c11_13", native: "어리다", english: "to be young", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_14", native: "역", english: "station", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_15", native: "유학생", english: "international student; exchange student", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_16", native: "~(으)로", english: "toward; by way of; with", unit: 3, chapter: 11, type: "particle" },
    { id: "u3_c11_17", native: "이민", english: "immigration; emigration", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_18", native: "인구", english: "population", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_19", native: "한글", english: "Hangul (Korean alphabet)", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_20", native: "한인", english: "Korean (person)", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_21", native: "-겠", english: "will; shall; probably (future/conjecture)", unit: 3, chapter: 11, type: "particle" },
    { id: "u3_c11_22", native: "깨끗하다", english: "to be clean", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_23", native: "다르다", english: "to be different", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_24", native: "달리", english: "differently; otherwise", unit: 3, chapter: 11, type: "adverb" },
    { id: "u3_c11_25", native: "더럽다", english: "to be dirty", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_26", native: "돕다", english: "to help", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_27", native: "무료", english: "free (of charge)", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_28", native: "묵다", english: "to stay (at a hotel); to lodge", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_29", native: "비다", english: "to be empty; to be vacant", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_30", native: "비상구", english: "emergency exit", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_31", native: "서비스", english: "service", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_32", native: "수건", english: "towel", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_33", native: "수영장", english: "swimming pool", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_34", native: "숙박비", english: "accommodation fee; room charge", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_35", native: "스위트룸", english: "suite room", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_36", native: "시끄럽다", english: "to be noisy", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_37", native: "옮기다", english: "to move; to transfer", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_38", native: "욕실", english: "bathroom", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_39", native: "이용(하다)", english: "use (to use)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_40", native: "일반실", english: "standard room", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_41", native: "체크아웃(하다)", english: "checkout (to check out)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_42", native: "체크인(하다)", english: "check-in (to check in)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_43", native: "필요하다", english: "to need; to be necessary", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_44", native: "프린트(데스크)", english: "front desk", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_45", native: "할인(하다/받다)", english: "discount (to discount / to receive discount)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_46", native: "~호", english: "~ (room) number", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_47", native: "호텔", english: "hotel", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_48", native: "국", english: "soup; country", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_49", native: "그렇지만", english: "but; however", unit: 3, chapter: 11, type: "adverb" },
    { id: "u3_c11_50", native: "냄새", english: "smell; odor", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_51", native: "달다", english: "to be sweet", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_52", native: "뜨겁다", english: "to be hot (temperature)", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_53", native: "맛", english: "taste; flavor", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_54", native: "배(가) 부르다", english: "to be full (after eating)", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_55", native: "별로", english: "not particularly; not much", unit: 3, chapter: 11, type: "adverb" },
    { id: "u3_c11_56", native: "소금", english: "salt", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_57", native: "수저", english: "spoon and chopsticks; cutlery", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_58", native: "손가락", english: "finger", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_59", native: "시다", english: "to be sour", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_60", native: "식혜", english: "sweet rice drink", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_61", native: "시원하다", english: "to be cool; to be refreshing", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_62", native: "싱겁다", english: "to be bland; to be not salty", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_63", native: "쓰다", english: "to be bitter; to write; to use", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_64", native: "젓가락", english: "chopsticks", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_65", native: "-지만", english: "but; although", unit: 3, chapter: 11, type: "particle" },
    { id: "u3_c11_66", native: "-지 못하다", english: "cannot; unable to", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_67", native: "-지 않다", english: "not (negation)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_68", native: "짜다", english: "to be salty", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_69", native: "차다", english: "to be cold (weather/food)", unit: 3, chapter: 11, type: "adjective" },
    { id: "u3_c11_70", native: "차리다", english: "to prepare; to set (table)", unit: 3, chapter: 11, type: "verb" },
    { id: "u3_c11_71", native: "천천히", english: "slowly", unit: 3, chapter: 11, type: "adverb" },
    { id: "u3_c11_72", native: "포크", english: "fork", unit: 3, chapter: 11, type: "noun" },
    { id: "u3_c11_73", native: "후식", english: "dessert", unit: 3, chapter: 11, type: "noun" },
];
