export const chapter3 = [
    { id: "u1_c3_01", native: "강", english: "river", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_02", native: "거실", english: "living room", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_03", native: "~ 개", english: "~ things (counter)", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_04", native: "그래서", english: "so / therefore", unit: 1, chapter: 3, type: "adverb" },
    { id: "u1_c3_05", native: "근처", english: "nearby / neighborhood", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_06", native: "나무", english: "tree", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_07", native: "넓다", english: "to be spacious", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_08", native: "~도", english: "also (particle)", unit: 1, chapter: 3, type: "particle" },
    { id: "u1_c3_09", native: "마당", english: "yard", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_10", native: "많다", english: "to be many", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_11", native: "바다", english: "ocean", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_12", native: "방", english: "room", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_13", native: "부엌", english: "kitchen", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_14", native: "산", english: "mountain", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_15", native: "작다", english: "to be small", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_16", native: "좋다", english: "to be good", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_17", native: "집", english: "house", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_18", native: "차고", english: "garage", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_19", native: "층", english: "floor", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_20", native: "침실", english: "bedroom", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_21", native: "크다", english: "to be big", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_22", native: "화장실", english: "bathroom", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_23", native: "검은색", english: "black (color)", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_24", native: "검정", english: "black", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_25", native: "노란색", english: "yellow (color)", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_26", native: "노랑", english: "yellow", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_27", native: "뒤", english: "behind", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_28", native: "밀", english: "bottom", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_29", native: "아래", english: "under", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_30", native: "밖", english: "outside", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_31", native: "불편", english: "inconvenient", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_32", native: "빨간색", english: "red (color)", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_33", native: "빨강", english: "red", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_34", native: "소파", english: "sofa", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_35", native: "아파트", english: "apartment", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_36", native: "안", english: "inside", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_37", native: "앞", english: "front", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_38", native: "~에 있다", english: "to exist / have", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_39", native: "~에 없다", english: "to not exist / have", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_40", native: "옆", english: "next to", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_41", native: "오른쪽", english: "right side", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_42", native: "옷", english: "clothes", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_43", native: "옷장", english: "closet", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_44", native: "왼쪽", english: "left side", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_45", native: "위", english: "above", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_46", native: "의자", english: "chair", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_47", native: "이~", english: "this", unit: 1, chapter: 3, type: "determiner" },
    { id: "u1_c3_48", native: "그~", english: "that", unit: 1, chapter: 3, type: "determiner" },
    { id: "u1_c3_49", native: "저~", english: "that over there", unit: 1, chapter: 3, type: "determiner" },
    { id: "u1_c3_50", native: "창문", english: "window", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_51", native: "책", english: "book", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_52", native: "책상", english: "desk", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_53", native: "책장", english: "bookshelf", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_54", native: "침대", english: "bed", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_55", native: "카메라", english: "camera", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_56", native: "커튼", english: "curtain", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_57", native: "컴퓨터", english: "computer", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_58", native: "테이블", english: "table", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_59", native: "텔레비전", english: "television", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_60", native: "파란색", english: "blue (color)", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_61", native: "파랑", english: "blue", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_62", native: "프린터", english: "printer", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_63", native: "하얀색", english: "white (color)", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_64", native: "하양", english: "white", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_65", native: "공부하다", english: "to study", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_66", native: "듣다", english: "to listen", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_67", native: "먹다", english: "to eat", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_68", native: "밥", english: "rice / meal", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_69", native: "보다", english: "to see", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_70", native: "빨래하다", english: "to do laundry", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_71", native: "설거지하다", english: "to do dishes", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_72", native: "숙제하다", english: "to do homework", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_73", native: "쉬다", english: "to rest", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_74", native: "식사하다", english: "to have a meal", unit: 1, chapter: 3, type: "adjective" },
    { id: "u1_c3_75", native: "신문", english: "newspaper", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_76", native: "요리하다", english: "to cook", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_77", native: "운동하다", english: "to exercise", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_78", native: "~을/를", english: "object marker", unit: 1, chapter: 3, type: "particle" },
    { id: "u1_c3_79", native: "음악", english: "music", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_80", native: "읽다", english: "to read", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_81", native: "자다", english: "to sleep (casual)", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_82", native: "주무시다", english: "to sleep (honorific)", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_83", native: "주말", english: "weekend", unit: 1, chapter: 3, type: "noun" },
    { id: "u1_c3_84", native: "청소하다", english: "to clean", unit: 1, chapter: 3, type: "verb" },
    { id: "u1_c3_85", native: "텔레비전", english: "television", unit: 1, chapter: 3, type: "noun" },
];
