export const chapter7 = [
    { id: "u2_c7_01", native: "가게", english: "a store; a shop", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_02", native: "걸리다", english: "to take (time); to hang", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_03", native: "기름", english: "oil; gas (fuel)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_04", native: "꽃집", english: "a flower shop", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_05", native: "넣다", english: "to put in; to insert", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_06", native: "돈", english: "money", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_07", native: "~등", english: "etc.; and so on", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_08", native: "말기다", english: "to entrust; to leave with", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_09", native: "물건", english: "thing; item; goods", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_10", native: "백화점", english: "a department store", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_11", native: "사다", english: "to buy", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_12", native: "생일/생신(↑)", english: "birthday (honorific)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_13", native: "서점", english: "a bookstore", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_14", native: "세탁소", english: "a dry cleaner; a laundromat", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_15", native: "쇼핑센터", english: "shopping center", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_16", native: "시내", english: "downtown; city center", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_17", native: "약", english: "medicine", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_18", native: "약국", english: "a pharmacy; a drug store", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_19", native: "영화관", english: "movie theater", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_20", native: "은행", english: "a bank", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_21", native: "이야기/얘기(하다)", english: "story; talk (to talk)", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_22", native: "제과점/빵집", english: "a bakery", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_23", native: "주유소", english: "a gas station", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_24", native: "찾다", english: "to find; to look for", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_25", native: "커피숍", english: "coffee shop", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_26", native: "갖다 주다", english: "to bring and give", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_27", native: "계산서", english: "bill; check", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_28", native: "김밥", english: "gimbap; seaweed rice roll", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_29", native: "김치(찌개)", english: "kimchi (stew)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_30", native: "만두", english: "dumpling", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_31", native: "맛있다", english: "to be delicious", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_32", native: "맥주", english: "beer", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_33", native: "맵다", english: "to be spicy", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_34", native: "물", english: "water", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_35", native: "반찬", english: "side dish", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_36", native: "받다", english: "to receive; to get", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_37", native: "배(가) 고프다", english: "to be hungry", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_38", native: "~ 병", english: "~ bottle (counter)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_39", native: "불고기", english: "bulgogi (grilled beef)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_40", native: "비빔밥", english: "bibimbap", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_41", native: "사이다", english: "cider; soda", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_42", native: "신용카드", english: "credit card", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_43", native: "-아/어서", english: "and then; because", unit: 2, chapter: 7, type: "particle" },
    { id: "u2_c7_44", native: "음료수", english: "beverage; drink", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_45", native: "음식", english: "food", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_46", native: "~ 인분", english: "~ servings (counter)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_47", native: "~ 잔", english: "~ glass/cup (counter)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_48", native: "주다/드리다", english: "to give (humble)", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_49", native: "시키다/주문하다", english: "to order", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_50", native: "콜라", english: "cola", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_51", native: "갈색", english: "brown (color)", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_52", native: "-게", english: "adverbial ending", unit: 2, chapter: 7, type: "particle" },
    { id: "u2_c7_53", native: "그런데", english: "but; however; by the way", unit: 2, chapter: 7, type: "adverb" },
    { id: "u2_c7_54", native: "길다/길게", english: "to be long", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_55", native: "남자", english: "man; male", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_56", native: "마음에 들어요", english: "to like it; it suits my taste", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_57", native: "머리", english: "head; hair", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_58", native: "미용실/머리방", english: "hair salon; beauty salon", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_59", native: "삼푸(하다)", english: "shampoo (to shampoo)", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_60", native: "손님", english: "customer; guest", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_61", native: "~아/어 주다/드리다(↑)", english: "to do for someone (honorific)", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_62", native: "어울리다", english: "to suit; to match; to get along", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_63", native: "어서 오세요", english: "Welcome! (please come in)", unit: 2, chapter: 7, type: "interjection" },
    { id: "u2_c7_64", native: "얼마예요?", english: "How much is it?", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_65", native: "여자", english: "woman; female", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_66", native: "염색(하다)", english: "dye (to dye hair)", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_67", native: "유행", english: "fashion; trend", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_68", native: "예쁘다", english: "to be pretty", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_69", native: "예약(하다)", english: "reservation (to reserve)", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_70", native: "-(으)르까요?", english: "Shall we ...? / Would you like to ...?", unit: 2, chapter: 7, type: "verb" },
    { id: "u2_c7_71", native: "좀", english: "a little; please (softener)", unit: 2, chapter: 7, type: "adverb" },
    { id: "u2_c7_72", native: "질다", english: "to be salty", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_73", native: "짧다", english: "to be short", unit: 2, chapter: 7, type: "adjective" },
    { id: "u2_c7_74", native: "커트", english: "cut; haircut", unit: 2, chapter: 7, type: "noun" },
    { id: "u2_c7_75", native: "파마(하다)", english: "perm (to get a perm)", unit: 2, chapter: 7, type: "verb" },
];
