export const chapter51 = [
  { id: "u13_c51_01", native: "가계", english: "a household budget; “household counting”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_02", native: "가득(하다)", english: "fully (to be full; to be filled up)", unit: 13, chapter: 51, type: "adjective" },
  { id: "u13_c51_03", native: "가치(관)", english: "values; (one’s) sense of values;“view of value”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_04", native: "과소비(하다)", english: "excessive spending; overspending (to spend excessively; to overspend)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_05", native: "과시(하다)", english: "showing off (to show off)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_06", native: "과시욕", english: "a desire for showing off", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_07", native: "관계", english: "a relation; connection", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_08", native: "경쟁력", english: "competitiveness; competitive edge; “competition power”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_09", native: "기준", english: "standards; criteria", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_10", native: "기러기", english: "a wild goose", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_11", native: "꼴찌", english: "the last (in ranking); the bottom", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_12", native: "끼니", english: "a meal", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_13", native: "낭비(하다)", english: "waste; squandering (to waste; to squander)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_14", native: "만연(하다/되다)", english: "rampancy (to be rampant)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_15", native: "명품 선호", english: "a preference for famous name-brand merchandise", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_16", native: "명품", english: "a famous brand; a prestigious item; “name item”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_17", native: "무분별(하다)", english: "indiscretion; imprudence; recklessness (to be indiscreet; to be imprudent; to be reckless)", unit: 13, chapter: 51, type: "adjective" },
  { id: "u13_c51_18", native: "무상", english: "free of charge; without cost; “without repaying”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_19", native: "무시(하다)", english: "disregard; neglect; “without seeing” (to disregard; to neglect; to ignore)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_20", native: "미혼", english: "single; unmarried; “not married”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_21", native: "반영(하다/되다)", english: "reflection (to reflect/to be reflected)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_22", native: "배려(하다)", english: "consideration; care (to be considerate; to care [about])", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_23", native: "배우자", english: "a spouse", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_24", native: "보육(하다)", english: "childcare; “preserving and upbringing” (to take care of children)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_25", native: "브랜드", english: "a brand; a make", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_26", native: "부유층", english: "the rich; the upper class; the haves", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_27", native: "사치(하다)", english: "a luxury; an extravagance (to be luxurious; to be extravagant)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_28", native: "생산성", english: "productivity", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_29", native: "성별", english: "gender; sex", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_30", native: "실망(하다)", english: "disappointment; “losing hope” (to be disappointed)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_31", native: "실제(로)", english: "in reality; actually", unit: 13, chapter: 51, type: "adverb" },
  { id: "u13_c51_32", native: "심지어", english: "even", unit: 13, chapter: 51, type: "adverb" },
  { id: "u13_c51_33", native: "심화(시키다/되다)", english: "deepening (to deepen; to intensify/to be deepened; to be intensified)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_34", native: "약하다", english: "to be weak; to be feeble; to be light", unit: 13, chapter: 51, type: "adjective" },
  { id: "u13_c51_35", native: "약화(시키다/되다)", english: "weakening (to weaken/to be weakened)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_36", native: "어학(원)", english: "language (institute)", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_37", native: "열풍", english: "a fever; a frenzy; fever pitch; bandwagon", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_38", native: "예금(하다)", english: "savings; deposit (to save money in the bank)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_39", native: "유급", english: "paid", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_40", native: "유도(하다/되다)", english: "an inducement; (to induce/to be induced)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_41", native: "입시", english: "an entrance examination", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_42", native: "잠재력", english: "potential; potentiality; “potential power”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_43", native: "전담", english: "exclusive charge", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_44", native: "전담(하다)", english: "being in full charge; “exclusively carrying (a burden on the shoulders)” (to be in full charge; to be in exclusive charge)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_45", native: "전액", english: "full amount (of money); total amount", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_46", native: "제시(하다/되다)", english: "suggestion; proposal; presentation; showing (to suggest; to propose/to be suggested; to be proposed)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_47", native: "조기", english: "early (period)", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_48", native: "중(요)시하다", english: "to put emphasis on; to lay stress on", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_49", native: "짝", english: "a pair; a mate", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_50", native: "채우다", english: "to fill in; to pack", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_51", native: "평가(하다/받다)", english: "evaluation (to evaluate/to be evaluated)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_52", native: "혜택", english: "a benefit", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_53", native: "확대(하다/되다)", english: "expansion; enlargement (to expand/to be expanded; to be enlarged)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_54", native: "애용(하다)", english: "habitual/frequent use (of a certain item because you like it); “love using” (to use favorably)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_55", native: "원어민", english: "a native speaker; “original language person”", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_56", native: "송금(하다)", english: "remittance; “sending money” (to wire or send money)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_57", native: "저출산", english: "low birthrate", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_58", native: "출산(하다)", english: "childbirth; delivery (of a child) (to give birth)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_59", native: "취학(하다/시키다)", english: "enrollment in school; entering school (to enroll in school; to enter school)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_60", native: "사례", english: "an example", unit: 13, chapter: 51, type: "noun" },
  { id: "u13_c51_61", native: "이별(하다)", english: "a parting; a farewell (to part)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_62", native: "헤어지다", english: "to part; to break up (with someone)", unit: 13, chapter: 51, type: "verb" },
  { id: "u13_c51_63", native: "~ 정도", english: "degree; limit", unit: 13, chapter: 51, type: "noun" },
];
