export const chapter27 = [
  { id: "u7_c27_01", native: "걱정(하다/되다)", english: "worry; concern (to be worried; to be concerned)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_02", native: "~ 겸", english: "concurrently; as well as", unit: 7, chapter: 27, type: "particle" },
  { id: "u7_c27_03", native: "고민(하다/이다)", english: "agony; anguish; worry (to be in agony; to be worried)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_04", native: "과장", english: "a manager; “section chief”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_05", native: "기대(하다/되다)", english: "expectation; anticipation (to expect/to be expected)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_06", native: "기억(하다/나다)", english: "memory; recall; memorization (to recall; to remember)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_07", native: "기회", english: "an opportunity; a chance", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_08", native: "~ 달", english: "a month", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_09", native: "–랍니다/래요", english: "contracted form of an indirectly quoted command/request", unit: 7, chapter: 27, type: "particle" },
  { id: "u7_c27_10", native: "–냡니다/냬요", english: "contracted form of an indirectly quoted question", unit: 7, chapter: 27, type: "particle" },
  { id: "u7_c27_11", native: "–답니다/대요", english: "contracted form of an indirectly quoted statement", unit: 7, chapter: 27, type: "particle" },
  { id: "u7_c27_12", native: "–잡니다/재요", english: "contracted form of an indirectly quoted suggestion", unit: 7, chapter: 27, type: "particle" },
  { id: "u7_c27_13", native: "동료", english: "a peer; a co-worker; a colleague", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_14", native: "동문/동창", english: "an alumnus; “(people who enter) the same door”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_15", native: "–는 중이다/~중이다", english: "in the middle of; in the process of", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_16", native: "부서", english: "one’s (duty) post; one’s station", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_17", native: "부인 (↑)", english: "a wife; Mrs. [title]", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_18", native: "부장", english: "a general manager; “department chief”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_19", native: "빠지다", english: "to be absent", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_20", native: "사장", english: "the president of a company; “company chief”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_21", native: "색다르다", english: "to be unusual; to be uncommon; to be unique", unit: 7, chapter: 27, type: "adjective" },
  { id: "u7_c27_22", native: "선배", english: "a senior person or elder in an organization; “front in the group”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_23", native: "세제", english: "detergent; “cleansing medicine”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_24", native: "승진(하다/되다)", english: "promotion; advancement (to be promoted)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_25", native: "약속(하다)", english: "an appointment; a promise (to make an appointment; to promise)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_26", native: "연락(하다/되다)", english: "contact (to contact; to get in touch with)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_27", native: "연말", english: "the year-end; the end of the year", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_28", native: "입사(하다)", english: "joining a company; “entering a company” (to join a company)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_29", native: "잊다", english: "to forget", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_30", native: "적다", english: "to write down; to jot down", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_31", native: "집들이(하다)", english: "a housewarming party (to have a housewarming party)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_32", native: "추천(하다/받다)", english: "a recommendation (to recommend/to be recommended)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_33", native: "친목회/친목 모임", english: "a social/convivial gathering; a (friendly) get-together; “friendship and harmony meeting”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_34", native: "최근", english: "recent; recently; “the most recent”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_35", native: "퇴직(하다)", english: "retirement; retiring from office; “off the job” (to retire)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_36", native: "(학)과", english: "a department; a course of study; a school subject", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_37", native: "학번", english: "year of college entry; “class number”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_38", native: "화장지/휴지", english: "toilet paper", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_39", native: "환영(하다)", english: "a welcome (to welcome)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_40", native: "회관", english: "an assembly hall", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_41", native: "회식(하다)", english: "a company lunch /dinner (to have a company lunch/dinner)", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_42", native: "후배", english: "a junior or younger person in an organization; “back in the group”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_43", native: "~회", english: "a gathering; a meeting; a convention; a party", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_44", native: "수첩", english: "a pocketbook; “handbook”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_45", native: "송년회", english: "an end-of-year party; “good-bye old year meeting”", unit: 7, chapter: 27, type: "noun" },
  { id: "u7_c27_46", native: "–아/어 버리다", english: "auxiliary verb implying that an action is completed and is irreversible or no longer available", unit: 7, chapter: 27, type: "verb" },
  { id: "u7_c27_47", native: "–(으)ㄹ래(요)", english: "will; would like to; want to", unit: 7, chapter: 27, type: "verb" },
];
