export const chapter15 = [
    { id: "u4_c15_01", native: "남부", english: "southern part", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_02", native: "남한/대한민국", english: "South Korea / Republic of Korea", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_03", native: "남해", english: "South Sea", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_04", native: "(도)시", english: "province / city", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_05", native: "~도", english: "~ island / province", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_06", native: "동부", english: "eastern part", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_07", native: "동해", english: "East Sea", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_08", native: "북부", english: "northern part", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_09", native: "서부", english: "western part", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_10", native: "서해", english: "West Sea", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_11", native: "섬", english: "island", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_12", native: "아름답다", english: "to be beautiful", unit: 4, chapter: 15, type: "adjective" },
    { id: "u4_c15_13", native: "유명하다", english: "to be famous", unit: 4, chapter: 15, type: "adjective" },
    { id: "u4_c15_14", native: "중부", english: "central part", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_15", native: "지도", english: "map", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_16", native: "지방", english: "province; region; countryside", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_17", native: "해수욕장", english: "beach; seaside resort", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_18", native: "한반도", english: "Korean Peninsula", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_19", native: "북한/조선 민주주의 인민공화국", english: "North Korea / Democratic People's Republic of Korea", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_20", native: "기념관", english: "memorial hall; museum", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_21", native: "기온", english: "temperature (air)", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_22", native: "나라/국가", english: "country; nation; state", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_23", native: "-는데/(으)ㄴ데", english: "and; but; while (background)", unit: 4, chapter: 15, type: "particle" },
    { id: "u4_c15_24", native: "~도", english: "~ also; too", unit: 4, chapter: 15, type: "particle" },
    { id: "u4_c15_25", native: "미군", english: "U.S. military; American soldier", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_26", native: "미사일", english: "missile", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_27", native: "분단(되다)", english: "division (to be divided)", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_28", native: "섭씨", english: "Celsius", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_29", native: "싸우다", english: "to fight", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_30", native: "-아/어지다", english: "to become ~ (change of state)", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_31", native: "영상", english: "above zero (temperature)", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_32", native: "영향", english: "influence; effect", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_33", native: "육이오", english: "June 25 (Korean War outbreak)", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_34", native: "일어나다", english: "to happen; to occur; to get up", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_35", native: "전쟁", english: "war", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_36", native: "참전(하다)", english: "participation in war (to participate in war)", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_37", native: "최고", english: "the highest; the best", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_38", native: "최저", english: "the lowest", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_39", native: "탱크", english: "tank (military vehicle)", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_40", native: "통일(하다/되다)", english: "unification (to unify / to be unified)", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_41", native: "화씨", english: "Fahrenheit", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_42", native: "휴전(하다/되다)", english: "armistice; ceasefire (to cease fire)", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_43", native: "가운데", english: "in the middle; among", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_44", native: "공식적", english: "official; formal", unit: 4, chapter: 15, type: "adjective" },
    { id: "u4_c15_45", native: "관광객", english: "tourist", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_46", native: "(국)기", english: "national flag", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_47", native: "대표", english: "representative", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_48", native: "-아/어도", english: "even if; although", unit: 4, chapter: 15, type: "particle" },
    { id: "u4_c15_49", native: "안내원", english: "guide; receptionist", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_50", native: "~에게서/한테서", english: "from (person)", unit: 4, chapter: 15, type: "particle" },
    { id: "u4_c15_51", native: "오래되다", english: "to be old (time)", unit: 4, chapter: 15, type: "adjective" },
    { id: "u4_c15_52", native: "외국인", english: "foreigner", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_53", native: "인상적", english: "impressive", unit: 4, chapter: 15, type: "adjective" },
    { id: "u4_c15_54", native: "자유", english: "freedom; liberty", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_55", native: "주변", english: "surroundings; vicinity", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_56", native: "찍다", english: "to take (photo); to stamp", unit: 4, chapter: 15, type: "verb" },
    { id: "u4_c15_57", native: "관문점/공동경비구역", english: "Joint Security Area (JSA) / Panmunjom", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_58", native: "평화", english: "peace", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_59", native: "휴전선", english: "armistice line; DMZ line", unit: 4, chapter: 15, type: "noun" },
    { id: "u4_c15_60", native: "회의실", english: "conference room; meeting room", unit: 4, chapter: 15, type: "noun" },
];
