export const chapter29 = [
  { id: "u8_c29_01", native: "가렵다", english: "to be itchy", unit: 8, chapter: 29, type: "adjective" },
  { id: "u8_c29_02", native: "간", english: "a liver", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_03", native: "검사(하다/받다)", english: "examination; inspection; checkup (to examine/to test/to inspect)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_04", native: "검진(하다/받다)", english: "a medical checkup (to give a medical examination/to receive a medical examination)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_05", native: "결과", english: "result; outcome; consequence", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_06", native: "고생(하다)", english: "a hard life; “suffering life” (to suffer hardships)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_07", native: "구역질([이] 나다)", english: "nausea (to feel nauseated)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_08", native: "내과", english: "internal medicine; “in(side) department”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_09", native: "넘다", english: "to exceed; to go over; to be more than", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_10", native: "독감", english: "influenza; the flu; “severe cold”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_11", native: "대변(보다)", english: "stool; feces; “big excrement” (to have a bowel movement; “see big excrement”)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_12", native: "맥박", english: "pulsation; pulse", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_13", native: "목이 쉬다", english: "to get hoarse", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_14", native: "몸살([이] 나다)", english: "a body ache (from fatigue or overwork); to ache all over (from fatigue or overwork)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_15", native: "물리치료", english: "physical therapy", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_16", native: "바르다", english: "to apply", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_17", native: "병원", english: "hospital; “illness house”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_18", native: "복통", english: "a stomachache", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_19", native: "산부인과", english: "obstetrics and gynecology; “birth women department”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_20", native: "살이 빠지다", english: "to lose weight; “the flesh is lost”", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_21", native: "살이 찌다", english: "to put on weight; “the flesh fattens”", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_22", native: "식욕", english: "an appetite; “food desire”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_23", native: "소아과", english: "pediatrics; “small child department”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_24", native: "수술(하다/받다)", english: "a surgery (to perform a surgical operation for/to receive a surgical operation for)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_25", native: "수치", english: "numerical value; numerical figure", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_26", native: "스트레스", english: "stress", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_27", native: "신장", english: "height; “body length”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_28", native: "안과", english: "ophthalmology; “eye department”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_29", native: "알레르기/알러지", english: "allergy", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_30", native: "어지럽다", english: "to be dizzy", unit: 8, chapter: 29, type: "adjective" },
  { id: "u8_c29_31", native: "연고", english: "an ointment", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_32", native: "외과", english: "the department of surgery; “outside department”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_33", native: "우선", english: "first (of all); above all", unit: 8, chapter: 29, type: "adverb" },
  { id: "u8_c29_34", native: "임신(하다)", english: "pregnancy (to become pregnant)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_35", native: "입원(하다)", english: "hospitalization; “entering an institute” (to be hospitalized)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_36", native: "이/이빨 (↓)", english: "a tooth", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_37", native: "이상", english: "disorder; abnormality; “different from the usual”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_38", native: "재다", english: "to measure", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_39", native: "정상(이다)", english: "normality (to be normal)", unit: 8, chapter: 29, type: "adjective" },
  { id: "u8_c29_40", native: "진료(하다/받다)", english: "medical examination and treatment (to examine and treat/to get treatment)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_41", native: "진찰(하다/받다)", english: "medical examination (to examine/to get a medical exam)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_42", native: "체온", english: "body temperature", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_43", native: "체중/몸무게", english: "body weight", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_44", native: "치과", english: "dentistry; “tooth department”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_45", native: "치료(하다/받다)", english: "treatment; care; cure (to treat [an injury]/to get treatment)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_46", native: "치통", english: "a toothache", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_47", native: "콜레스테롤", english: "cholesterol", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_48", native: "퇴원(하다)", english: "discharge from the hospital; “leaving an institute” (to be discharged from the hospital)", unit: 8, chapter: 29, type: "verb" },
  { id: "u8_c29_49", native: "통증", english: "pain; “pain symptom”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_50", native: "혈압", english: "blood pressure", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_51", native: "혈액", english: "blood; “blood fluid”", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_52", native: "환자", english: "a patient", unit: 8, chapter: 29, type: "noun" },
  { id: "u8_c29_53", native: "–(으)ㄴ 지 ~(이/가) 되다", english: "It has been (time length) since", unit: 8, chapter: 29, type: "verb" },
];
