export const chapter9 = [
    { id: "u3_c9_01", native: "국", english: "soup; country", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_02", native: "기다리다", english: "to wait", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_03", native: "남기다", english: "to leave (behind); to save", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_04", native: "다시", english: "again; once more", unit: 3, chapter: 9, type: "adverb" },
    { id: "u3_c9_05", native: "문자", english: "text message; character", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_06", native: "메시지/메세지", english: "message", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_07", native: "바쁘다", english: "to be busy", unit: 3, chapter: 9, type: "adjective" },
    { id: "u3_c9_08", native: "보내다", english: "to send", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_09", native: "부탁(하다)/부탁드리다(↑)", english: "request (to request) - honorific", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_10", native: "여보세요", english: "Hello? (on phone)", unit: 3, chapter: 9, type: "interjection" },
    { id: "u3_c9_11", native: "음성", english: "voice", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_12", native: "~의", english: "possessive particle", unit: 3, chapter: 9, type: "particle" },
    { id: "u3_c9_13", native: "잠시만/잠깐만", english: "just a moment; wait a second", unit: 3, chapter: 9, type: "adverb" },
    { id: "u3_c9_14", native: "전화(를) 걸다", english: "to make a phone call", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_15", native: "중학교", english: "middle school", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_16", native: "통화 중", english: "on the phone; line busy", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_17", native: "핸드폰/휴대폰", english: "cell phone; mobile phone", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_18", native: "나흘", english: "four days", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_19", native: "~ 때", english: "when; at the time of", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_20", native: "~(으)로", english: "toward; by way of; with (instrument)", unit: 3, chapter: 9, type: "particle" },
    { id: "u3_c9_21", native: "방학", english: "school vacation; break", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_22", native: "~박~일", english: "~ nights ~ days", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_23", native: "비행기", english: "airplane", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_24", native: "사흘", english: "three days", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_25", native: "아직", english: "still; yet; not yet", unit: 3, chapter: 9, type: "adverb" },
    { id: "u3_c9_26", native: "이틀", english: "two days", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_27", native: "-(으)ㄹ 거다", english: "will ~ (future)", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_28", native: "-(으)ㄹ 수 있다/없다", english: "can / cannot", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_29", native: "특별하다", english: "to be special", unit: 3, chapter: 9, type: "adjective" },
    { id: "u3_c9_30", native: "편하다", english: "to be comfortable; to be convenient", unit: 3, chapter: 9, type: "adjective" },
    { id: "u3_c9_31", native: "표", english: "ticket", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_32", native: "한 ~", english: "about ~; around ~", unit: 3, chapter: 9, type: "determiner" },
    { id: "u3_c9_33", native: "힘들다", english: "to be hard; to be difficult; to be tiring", unit: 3, chapter: 9, type: "adjective" },
    { id: "u3_c9_34", native: "~ 것", english: "thing; fact; nominalizer", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_35", native: "~과/와", english: "and; with (and)", unit: 3, chapter: 9, type: "particle" },
    { id: "u3_c9_36", native: "노래(하다/부르다)", english: "song (to sing)", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_37", native: "머무르다/머물다", english: "to stay; to remain", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_38", native: "아마", english: "probably; perhaps", unit: 3, chapter: 9, type: "adverb" },
    { id: "u3_c9_39", native: "-(으)면", english: "if; when", unit: 3, chapter: 9, type: "particle" },
    { id: "u3_c9_40", native: "~(이)랑", english: "and; with (and - casual)", unit: 3, chapter: 9, type: "particle" },
    { id: "u3_c9_41", native: "잔치", english: "feast; party; celebration", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_42", native: "초대(하다)", english: "invitation (to invite)", unit: 3, chapter: 9, type: "verb" },
    { id: "u3_c9_43", native: "친척", english: "relatives", unit: 3, chapter: 9, type: "noun" },
    { id: "u3_c9_44", native: "환갑/회갑", english: "60th birthday celebration", unit: 3, chapter: 9, type: "noun" },
];
