export const chapter14 = [
    { id: "u4_c14_01", native: "공항철도", english: "airport railroad", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_02", native: "내려가다", english: "to go down", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_03", native: "내리다", english: "to get off; to descend", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_04", native: "~대", english: "~ (large vehicle counter)", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_05", native: "대중교통", english: "public transportation", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_06", native: "따라가다", english: "to follow", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_07", native: "리무진", english: "limousine (bus)", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_08", native: "~마다", english: "every ~", unit: 4, chapter: 14, type: "particle" },
    { id: "u4_c14_09", native: "승강기/엘리베이터", english: "elevator", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_10", native: "시청", english: "city hall", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_11", native: "~씩", english: "each; per; apiece", unit: 4, chapter: 14, type: "particle" },
    { id: "u4_c14_12", native: "안내소", english: "information desk", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_13", native: "요금", english: "fare; fee", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_14", native: "운행(하다/되다)", english: "operation (to operate / to run)", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_15", native: "~원", english: "~ won (Korean currency)", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_16", native: "택시", english: "taxi", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_17", native: "편리하다", english: "to be convenient", unit: 4, chapter: 14, type: "adjective" },
    { id: "u4_c14_18", native: "표지판", english: "signboard; sign", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_19", native: "계단", english: "stairs", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_20", native: "-고 있다/계시다(↑)", english: "to be doing (progressive) - honorific", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_21", native: "고등학교", english: "high school", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_22", native: "-기 바라다", english: "to hope; to wish", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_23", native: "금연", english: "no smoking", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_24", native: "나가다", english: "to go out; to exit", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_25", native: "대학교", english: "university; college", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_26", native: "들어오다", english: "to come in; to enter", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_27", native: "매표소", english: "ticket office; ticket booth", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_28", native: "방면", english: "direction", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_29", native: "승강장", english: "platform", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_30", native: "승차권", english: "boarding ticket; ticket", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_31", native: "자동판매기", english: "vending machine", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_32", native: "전동차", english: "electric train; subway train", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_33", native: "전철", english: "subway; electric train", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_34", native: "정거장", english: "station; stop", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_35", native: "줄", english: "line; queue", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_36", native: "출입금지", english: "no entry; do not enter", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_37", native: "~행", english: "~ bound (direction)", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_38", native: "~호선", english: "~ line (subway line)", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_39", native: "건너다", english: "to cross", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_40", native: "걷다", english: "to walk", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_41", native: "금지(하다/되다)", english: "prohibition (to prohibit / to be prohibited)", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_42", native: "기사", english: "driver", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_43", native: "나다", english: "to happen; to occur; to come out", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_44", native: "-(으)니까", english: "because; since", unit: 4, chapter: 14, type: "particle" },
    { id: "u4_c14_45", native: "보행자", english: "pedestrian", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_46", native: "사고(나다)", english: "accident (to have an accident)", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_47", native: "승용차", english: "passenger car; private car", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_48", native: "양보(하다)", english: "yield; concession (to yield)", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_49", native: "일방통행", english: "one-way traffic", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_50", native: "전용", english: "exclusive use; dedicated", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_51", native: "지하도", english: "underground passage; underpass", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_52", native: "차도/차로", english: "roadway; lane", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_53", native: "출근(하다)", english: "commute to work (to go to work)", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_54", native: "터널", english: "tunnel", unit: 4, chapter: 14, type: "noun" },
    { id: "u4_c14_55", native: "퇴근(하다)", english: "commute from work (to leave work)", unit: 4, chapter: 14, type: "verb" },
    { id: "u4_c14_56", native: "횡단보도", english: "crosswalk; pedestrian crossing", unit: 4, chapter: 14, type: "noun" },
];
