export const chapter6 = [
    { id: "u2_c6_01", native: "가을", english: "fall; autumn", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_02", native: "겨울", english: "winter", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_03", native: "계절", english: "a season", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_04", native: "구름", english: "cloud", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_05", native: "끼다", english: "(fog, cloud, dust, etc.) to form", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_06", native: "날씨", english: "weather", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_07", native: "내리다", english: "(rain, snow, etc.) to fall; to come down", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_08", native: "높다", english: "to be high; to be tall", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_09", native: "눈", english: "snow", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_10", native: "따뜻하다", english: "to be warm", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_11", native: "덥다", english: "(weather) to be hot", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_12", native: "많이", english: "a lot; much; many", unit: 2, chapter: 6, type: "adverb" },
    { id: "u2_c6_13", native: "맑다", english: "to be clear", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_14", native: "바람", english: "wind", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_15", native: "불다", english: "to blow", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_16", native: "비", english: "rain", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_17", native: "쌀쌀하다", english: "to be chilly", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_18", native: "아주", english: "very", unit: 2, chapter: 6, type: "adverb" },
    { id: "u2_c6_19", native: "안개", english: "fog", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_20", native: "여름", english: "summer", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_21", native: "춥다", english: "(weather) to be cold", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_22", native: "하늘", english: "the sky", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_23", native: "흐리다", english: "to be cloudy; to be overcast", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_24", native: "-고 싶다/고 싶어하다", english: "to want to; to wish to", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_25", native: "골프", english: "golf", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_26", native: "농구", english: "basketball", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_27", native: "독서", english: "reading (as a hobby)", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_28", native: "못 + verb", english: "cannot + verb (negation)", unit: 2, chapter: 6, type: "adverb" },
    { id: "u2_c6_29", native: "배구", english: "volleyball", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_30", native: "배우다", english: "to learn", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_31", native: "볼링", english: "bowling", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_32", native: "쉽다", english: "to be easy", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_33", native: "스노보드", english: "snowboarding", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_34", native: "스케이트", english: "skating", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_35", native: "스키", english: "skiing", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_36", native: "야구", english: "baseball", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_37", native: "어떤~", english: "what kind of ~; which ~", unit: 2, chapter: 6, type: "determiner" },
    { id: "u2_c6_38", native: "어렵다", english: "to be difficult", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_39", native: "여행(하다)", english: "travel (to travel)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_40", native: "재미있다", english: "to be interesting / fun", unit: 2, chapter: 6, type: "adjective" },
    { id: "u2_c6_41", native: "좋아하다", english: "to like", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_42", native: "축구", english: "soccer", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_43", native: "취미", english: "hobby", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_44", native: "치다", english: "to hit; to play (sports)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_45", native: "타다", english: "to ride; to take (transport)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_46", native: "탁구", english: "table tennis", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_47", native: "테니스", english: "tennis", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_48", native: "하지만", english: "but; however", unit: 2, chapter: 6, type: "adverb" },
    { id: "u2_c6_49", native: "같이", english: "together", unit: 2, chapter: 6, type: "adverb" },
    { id: "u2_c6_50", native: "계획(하다)", english: "plan (to plan)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_51", native: "골프장", english: "a golf course", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_52", native: "공원", english: "a park", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_53", native: "구경(하다)", english: "watching; sightseeing (to watch; to sightsee)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_54", native: "달리기", english: "running", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_55", native: "만나다", english: "to meet", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_56", native: "바닷가", english: "the beach; the coast; the seaside", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_57", native: "산책(하다)", english: "stroll / walk (to take a walk)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_58", native: "야영(하다)", english: "camping (to camp)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_59", native: "영화", english: "movie", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_60", native: "-(으)러 가다/오다", english: "to go/come in order to ~", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_61", native: "-(으)비시다", english: "Let's ... (suggest)", unit: 2, chapter: 6, type: "verb" },
    { id: "u2_c6_62", native: "음악", english: "music", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_63", native: "이번~", english: "this ~ (time)", unit: 2, chapter: 6, type: "determiner" },
    { id: "u2_c6_64", native: "자전거", english: "bicycle", unit: 2, chapter: 6, type: "noun" },
    { id: "u2_c6_65", native: "전화(하다)", english: "phone / to call (to make a phone call)", unit: 2, chapter: 6, type: "verb" },
];
