export const chapter35 = [
  { id: "u9_c35_01", native: "개발(하다/되다)", english: "development (to develop/to be developed)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_02", native: "개별적으로", english: "individually", unit: 9, chapter: 35, type: "adverb" },
  { id: "u9_c35_03", native: "관련(하다/되다)", english: "relation; connection (to be related; to be connected)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_04", native: "게시판", english: "a bulletin board", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_05", native: "경력", english: "(work) experience", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_06", native: "구인", english: "a job listing; “seeking a person”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_07", native: "구직(자)", english: "seeking a job (a job seeker; a job hunter)", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_08", native: "기회", english: "an opportunity", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_09", native: "내용", english: "contents; substance", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_10", native: "다국적", english: "multinational", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_11", native: "단점", english: "a weak point; shortcoming; “short point”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_12", native: "동기", english: "a motive", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_13", native: "면접([을] 보다)", english: "a face-to-face interview; “face contact” (to have a face-to-face interview)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_14", native: "면접관", english: "an interviewer", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_15", native: "무역학", english: "a study of trade", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_16", native: "박람회", english: "a fair; an expo", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_17", native: "보이다/들리다", english: "“to be seen”/“to be heard”", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_18", native: "상반기", english: "the first half of a given period or year; “the top half period”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_19", native: "서류 전형", english: "documents screening", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_20", native: "소지(하다)", english: "possession; carrying (to possess; to carry)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_21", native: "쌓다", english: "to build", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_22", native: "업데이트", english: "update", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_23", native: "우대(하다/받다)", english: "preferential treatment; special treatment (to give preferential treatment/to be given preferential treatment)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_24", native: "유리하다", english: "to be advantageous", unit: 9, chapter: 35, type: "adjective" },
  { id: "u9_c35_25", native: "유용하다", english: "to be useful", unit: 9, chapter: 35, type: "adjective" },
  { id: "u9_c35_26", native: "이, 히, 리, 기", english: "passive infixes", unit: 9, chapter: 35, type: "particle" },
  { id: "u9_c35_27", native: "이력서", english: "a resume", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_28", native: "인원", english: "the number of persons; personnel; staff", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_29", native: "임금", english: "wage; pay", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_30", native: "~자", english: "a suffix denoting a person", unit: 9, chapter: 35, type: "particle" },
  { id: "u9_c35_31", native: "자신", english: "oneself", unit: 9, chapter: 35, type: "pronoun" },
  { id: "u9_c35_32", native: "자신(감)", english: "self-confidence; “self-believing feeling”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_33", native: "적응(하다/되다)", english: "adaptation (to adapt oneself to/to be adapted to)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_34", native: "접수(하다/되다)", english: "receipt; acceptance (to receive; to accept/to be received)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_35", native: "중소기업", english: "small and medium enterprises", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_36", native: "참가(하다)", english: "participation (to participate)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_37", native: "채용(하다/되다)", english: "employment; hiring; recruitment (to employ; to hire; to recruit/to be employed)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_38", native: "철저하다", english: "to be thorough; to be exhaustive; to be perfect", unit: 9, chapter: 35, type: "adjective" },
  { id: "u9_c35_39", native: "특기", english: "one’s special ability; talent; “special skill”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_40", native: "하반기", english: "the second half of a given period or year; “the bottom half period”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_41", native: "학력", english: "schooling; educational background; “learning history”", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_42", native: "해외", english: "overseas", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_43", native: "호주", english: "Australia", unit: 9, chapter: 35, type: "noun" },
  { id: "u9_c35_44", native: "희망(하다)", english: "aspiration; hope; longing (to aspire; to hope; to long)", unit: 9, chapter: 35, type: "verb" },
  { id: "u9_c35_45", native: "장점", english: "a merit; a strength; a forte; “strong point”", unit: 9, chapter: 35, type: "noun" },
];
