export const chapter45 = [
  { id: "u12_c45_01", native: "~가량", english: "approximately; about", unit: 12, chapter: 45, type: "particle" },
  { id: "u12_c45_02", native: "감소(하다/되다)", english: "decrease (to decrease/to be decreased)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_03", native: "강수량/강우량", english: "the amount of rainfall/precipitation", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_04", native: "결항(하다/되다)", english: "cancellation of an ocean liner or flight (to cancel/to be canceled)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_05", native: "경보", english: "a warning; an alarm; “warning report”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_06", native: "고기압", english: "high atmospheric pressure", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_07", native: "공급(하다/되다)", english: "supply; provision (to supply; to provide/to be supplied; to be provided)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_08", native: "관측(하다/되다)", english: "observation (to observe/to be observed)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_09", native: "구간", english: "a section", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_10", native: "기록(하다)", english: "record-breaking (to record)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_11", native: "기상청", english: "a meteorological bureau", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_12", native: "농작물", english: "the crops; a harvest; farm produce", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_13", native: "느끼다", english: "to feel", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_14", native: "~ 등", english: "and so on; etc.", unit: 12, chapter: 45, type: "particle" },
  { id: "u12_c45_15", native: "~ 만에", english: "after the lapse (of time)", unit: 12, chapter: 45, type: "particle" },
  { id: "u12_c45_16", native: "마비(시키다/되다)", english: "paralysis (to paralyze/to be paralyzed)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_17", native: "몰아치다", english: "(storm, blizzard, etc.) to rage", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_18", native: "물결이 일다", english: "waves rise", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_19", native: "남극", english: "the South Pole; the Antarctic; “south extreme”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_20", native: "남하(하다)", english: "moving southward; “south below” (to move southward)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_21", native: "북극", english: "the North Pole; the Arctic; “north extreme”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_22", native: "북상(하다)", english: "moving northward; “north above” (to move northward)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_23", native: "보도(하다/되다)", english: "news; a report (to report/to be reported)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_24", native: "발령(하다/되다)", english: "issuing (of an order, warning, etc.) (to issue/to be issued)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_25", native: "빙하", english: "a glacier; “iced water”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_26", native: "소나기", english: "a (rain) shower", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_27", native: "상승(하다;되다)", english: "rise (to rise; to ascend; to go up)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_28", native: "산간", english: "a mountainous area; “between mountains”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_29", native: "생태계", english: "an ecosystem", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_30", native: "수확량", english: "a yield; “harvest amount”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_31", native: "전역", english: "the whole area; the whole district; the whole region", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_32", native: "전하다", english: "to report; to deliver; to convey", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_33", native: "점차(적으로)", english: "gradually", unit: 12, chapter: 45, type: "adverb" },
  { id: "u12_c45_34", native: "지정(하다/되다)", english: "designation; appointment (to designate/to be designated)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_35", native: "진동", english: "a shock; a tremor", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_36", native: "파괴(하다/되다)", english: "destruction; demolition (to destroy/to be destroyed)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_37", native: "파도가 치다", english: "waves hit", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_38", native: "폐쇄(하다;시키다/되다)", english: "closure; shutdown (to close; to shut down/to be closed)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_39", native: "~ 편", english: "a counter for regular transportation (flight, bus, train, etc.)", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_40", native: "평년", english: "an average year; a regular year", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_41", native: "한파", english: "a cold snap; “cold wave”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_42", native: "해상", english: "the sea; “above the sea”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_43", native: "해수면", english: "sea level; “sea water surface”", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_44", native: "현상", english: "a phenomenon", unit: 12, chapter: 45, type: "noun" },
  { id: "u12_c45_45", native: "확산(되다)", english: "spreading (to spread)", unit: 12, chapter: 45, type: "verb" },
  { id: "u12_c45_46", native: "휴교령", english: "an order for school closing", unit: 12, chapter: 45, type: "noun" },
];
