export const chapter19 = [
    { id: "u5_c19_01", native: "결승(전)", english: "finals; final match", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_02", native: "경기(하다)", english: "game; match (to play a game)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_03", native: "권투/복싱", english: "boxing", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_04", native: "~대", english: "~ (large vehicle / generation)", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_05", native: "대회", english: "tournament; competition", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_06", native: "따다", english: "to win; to pick; to earn", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_07", native: "비기다", english: "to tie; to draw", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_08", native: "사격", english: "shooting; marksmanship", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_09", native: "선수", english: "athlete; player", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_10", native: "~승", english: "~ win(s)", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_11", native: "시합(하다)", english: "match; game (to compete)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_12", native: "신기록을 세우다", english: "to set a new record", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_13", native: "양궁", english: "archery", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_14", native: "역도", english: "weightlifting", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_15", native: "열심히", english: "hard; diligently", unit: 5, chapter: 19, type: "adverb" },
    { id: "u5_c19_16", native: "우승(하다)", english: "victory; championship (to win)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_17", native: "유도", english: "judo", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_18", native: "육상", english: "track and field; athletics", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_19", native: "응원(하다)", english: "cheering (to cheer)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_20", native: "이기다", english: "to win; to beat", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_21", native: "준결승(전)", english: "semifinals", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_22", native: "지다", english: "to lose", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_23", native: "체조", english: "gymnastics", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_24", native: "태권도", english: "taekwondo", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_25", native: "팀", english: "team", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_26", native: "~패", english: "~ loss(es)", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_27", native: "개", english: "dog", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_28", native: "고양이", english: "cat", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_29", native: "과수원", english: "orchard; fruit farm", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_30", native: "그렇다", english: "to be so; to be that way", unit: 5, chapter: 19, type: "adjective" },
    { id: "u5_c19_31", native: "기르다", english: "to raise; to grow; to keep (pets)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_32", native: "농장", english: "farm", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_33", native: "동물", english: "animal", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_34", native: "따다", english: "to pick; to harvest", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_35", native: "먹이(주다)", english: "feed (to feed)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_36", native: "밭", english: "field; dry field", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_37", native: "새", english: "bird", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_38", native: "시골", english: "countryside; rural area", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_39", native: "심다", english: "to plant", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_40", native: "양", english: "sheep", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_41", native: "언제든지", english: "anytime; whenever", unit: 5, chapter: 19, type: "adverb" },
    { id: "u5_c19_42", native: "오리", english: "duck", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_43", native: "-(으)ㄴ 적이 있다/없다", english: "to have / not have experienced", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_44", native: "이렇다", english: "to be like this", unit: 5, chapter: 19, type: "adjective" },
    { id: "u5_c19_45", native: "저렇다", english: "to be like that", unit: 5, chapter: 19, type: "adjective" },
    { id: "u5_c19_46", native: "질문(하다)", english: "question (to ask a question)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_47", native: "참", english: "really; truly; indeed", unit: 5, chapter: 19, type: "adverb" },
    { id: "u5_c19_48", native: "체험(하다)", english: "experience (to experience)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_49", native: "토끼", english: "rabbit", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_50", native: "가입(하다/되다)", english: "membership (to join / to be joined)", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_51", native: "~끼리", english: "among themselves; with each other", unit: 5, chapter: 19, type: "particle" },
    { id: "u5_c19_52", native: "당구", english: "billiards; pool", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_53", native: "동호회", english: "club; hobby group", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_54", native: "듣다", english: "to listen; to hear", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_55", native: "등산화", english: "hiking boots", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_56", native: "무엇보다", english: "above all; more than anything", unit: 5, chapter: 19, type: "adverb" },
    { id: "u5_c19_57", native: "배드민턴", english: "badminton", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_58", native: "벤치 점프", english: "bench jump", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_59", native: "사귀다", english: "to make friends; to date", unit: 5, chapter: 19, type: "verb" },
    { id: "u5_c19_60", native: "산악", english: "mountain climbing; mountaineering", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_61", native: "스쿠버 다이빙", english: "scuba diving", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_62", native: "신청서", english: "application form", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_63", native: "~에 대한", english: "about; regarding", unit: 5, chapter: 19, type: "particle" },
    { id: "u5_c19_64", native: "오리엔테이션", english: "orientation", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_65", native: "인라인 스케이트", english: "inline skating", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_66", native: "경기", english: "game; match; competition", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_67", native: "초보자", english: "beginner", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_68", native: "친하다", english: "to be close; to be friendly", unit: 5, chapter: 19, type: "adjective" },
    { id: "u5_c19_69", native: "취미", english: "hobby", unit: 5, chapter: 19, type: "noun" },
    { id: "u5_c19_70", native: "회원", english: "member", unit: 5, chapter: 19, type: "noun" },
];
