export const chapter56 = [
  { id: "u14_c56_01", native: "갈등", english: "a conflict; strife; dissension", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_02", native: "개(발)도(상)국", english: "a developing country", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_03", native: "거대하다", english: "to be huge; to be gigantic; to be immense", unit: 14, chapter: 56, type: "adjective" },
  { id: "u14_c56_04", native: "결의(안)(하다/되다)", english: "a resolution; “resolution proposal” (to resolve/to be resolved)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_05", native: "겹치다", english: "to overlap", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_06", native: "경고(하다)", english: "a warning (to warn)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_07", native: "관세", english: "a tariff; “gateway tax”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_08", native: "근본", english: "the root; the source; the origin; “fundamental basis”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_09", native: "금세기", english: "this century", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_10", native: "기금", english: "fund", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_11", native: "기아", english: "a famine; starvation; hunger", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_12", native: "기증(하다)", english: "donation (of goods) (to donate)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_13", native: "내전", english: "a civil war; “an internal war”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_14", native: "마찰(하다)", english: "rubbing; chafing; friction (to rub)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_15", native: "말라리아", english: "malaria", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_16", native: "망명(하다)", english: "(political) asylum; exile (to seek asylum; to defect)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_17", native: "무겁다", english: "to be heavy", unit: 14, chapter: 56, type: "adjective" },
  { id: "u14_c56_18", native: "무려", english: "adjective emphasizing an unexpectedly large number", unit: 14, chapter: 56, type: "adverb" },
  { id: "u14_c56_19", native: "물리다", english: "to charge (a person with a fine, money, etc.); to levy", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_20", native: "물품", english: "goods; articles; commodity", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_21", native: "반덤핑", english: "anti-dumping", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_22", native: "반발(하다)", english: "repulsion; rebellion (to repulse; to rebel)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_23", native: "발발(하다)", english: "an outbreak (to break out)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_24", native: "벌어지다", english: "to take place; to happen", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_25", native: "보복(하다)", english: "retaliation; (to retaliate)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_26", native: "부과(하다/되다)", english: "imposition (to impose; to lay on/to be imposed)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_27", native: "부적절하다", english: "to be inappropriate", unit: 14, chapter: 56, type: "adjective" },
  { id: "u14_c56_28", native: "분규", english: "a dispute; a complication; an entanglement", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_29", native: "빈곤(하다)", english: "pauperism; poverty(to be poor)", unit: 14, chapter: 56, type: "adjective" },
  { id: "u14_c56_30", native: "빛(나다/내다)", english: "(a) light; rays; beam; a color (to shine; to beam/to make shine; to polish)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_31", native: "사막", english: "desert", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_32", native: "사상", english: "historically", unit: 14, chapter: 56, type: "adverb" },
  { id: "u14_c56_33", native: "사태", english: "a situation; a state of affairs; an incident", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_34", native: "산하", english: "under (the umbrella of a higher organization)", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_35", native: "성명", english: "a (public) declaration; a statement; an announcement; a proclamation", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_36", native: "~ 세기", english: "a century", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_37", native: "세율", english: "a rate of taxation; tax rates", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_38", native: "순방(하다)", english: "a round of calls; a round of visits; a tour (to make a round of calls; to make a tour)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_39", native: "악화(되다)", english: "deterioration (to get worse; to deteriorate)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_40", native: "언론", english: "media; press; speech; journalism", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_41", native: "에이즈", english: "AIDS (Acquired Immune Deficiency Syndrome)", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_42", native: "오아시스", english: "an oasis", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_43", native: "우물", english: "a well", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_44", native: "유혈", english: "bloodshed; “flow of blood”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_45", native: "인종", english: "a race; an ethnic group; “human species”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_46", native: "자국", english: "one’s own country", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_47", native: "자선", english: "charity; philanthropy; giving alms", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_48", native: "저렴하다", english: "to be inexpensive; to be cheap", unit: 14, chapter: 56, type: "adjective" },
  { id: "u14_c56_49", native: "적립(하다/되다)", english: "saving; accumulation (to save; to accumulate/to be saved; to be accumulated)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_50", native: "정상", english: "the top; the summit; the head of a nation", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_51", native: "제재(하다)", english: "sanctions; a restriction (to impose sanctions; to restrict)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_52", native: "조속한", english: "early and speedy", unit: 14, chapter: 56, type: "adjective" },
  { id: "u14_c56_53", native: "조약", english: "a treaty; a pact", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_54", native: "조정(하다/되다)", english: "mediation; arbitration (to mediate/to be mediated)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_55", native: "주최(하다)", english: "hosting (a meeting) (to host)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_56", native: "줄기", english: "a stem; a stream; a branch; a ray (of light)", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_57", native: "착수(하다)", english: "embarking on; launch; start; outset (to launch; to embark on)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_58", native: "참극", english: "a tragedy; an atrocity", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_59", native: "철폐(하다/되다)", english: "abolishment(to abolish/to be abolished)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_60", native: "체결(하다/되다)", english: "entering into (a contract or an agreement) (to sign [a contract]/[a contract] to be signed)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_61", native: "촉구(하다)", english: "pressing; urging(to press; to urge)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_62", native: "촉진(하다/시키다)", english: "expedite; promotion; acceleration; “pressing (a person) to move forward”(to expedite; to promote)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_63", native: "태평양", english: "the Pacific (Ocean); “great pacific ocean”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_64", native: "터전", english: "a site (for living); a lot; the grounds", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_65", native: "표면", english: "a surface", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_66", native: "(피)난민", english: "an evacuee; a refugee; “people who escape hardship”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_67", native: "해당(하다/되다)", english: "relevant; pertinent; applicable (to be relevant; to be pertinent; to be applicable; to come/to fall under [a category])", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_68", native: "해적", english: "a pirate; “sea robber”", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_69", native: "핵무기", english: "a nuclear weapon", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_70", native: "협상(하다/되다)", english: "negotiation (to negotiate/to be negotiated)", unit: 14, chapter: 56, type: "verb" },
  { id: "u14_c56_71", native: "폐결핵", english: "pulmonary tuberculosis (TB)", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_72", native: "소수", english: "a small number; a minority", unit: 14, chapter: 56, type: "noun" },
  { id: "u14_c56_73", native: "냉해", english: "cold weather damage; “cold harm”", unit: 14, chapter: 56, type: "noun" },
];
