export const chapter53 = [
  { id: "u14_c53_01", native: "가공품", english: "a processed product; finished goods", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_02", native: "~간", english: "for a duration of (time)", unit: 14, chapter: 53, type: "particle" },
  { id: "u14_c53_03", native: "강조(하다/되다)", english: "an emphasis; a stress (to emphasize/to be emphasized)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_04", native: "거부(하다/당하다)", english: "a refusal; a rejection; a disapproval; a denial (to refuse/to be refused)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_05", native: "거치다", english: "to go through; to pass through; to go by way of", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_06", native: "결핍(되다)", english: "a lack of; shortage; scarcity (to lack; to run short of)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_07", native: "계기", english: "a chance; an opportunity", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_08", native: "곡물", english: "grain", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_09", native: "공단", english: "an industrial complex; an industrial park", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_10", native: "군사분계선", english: "Military Demarcation Line (MDL)", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_11", native: "굶주리다", english: "to starve; to go hungry; to hunger for", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_12", native: "대~", english: "to(ward); against; with; on", unit: 14, chapter: 53, type: "particle" },
  { id: "u14_c53_13", native: "대사관", english: "an embassy; “big envoy house”", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_14", native: "물량", english: "the amount of materials", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_15", native: "물류", english: "distribution (of goods) originated from 물적유통", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_16", native: "민간인", english: "a civilian; a nonmilitary person", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_17", native: "배포(하다/되다)", english: "wide distribution (of newspapers or books) (to distribute/to be distributed widely)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_18", native: "분배(하다/되다)", english: "distribution (to distribute/to be distributed)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_19", native: "비정부기구", english: "NGO (nongovernmental organization)", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_20", native: "영양실조", english: "malnutrition; “loss of nutritional balance”", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_21", native: "~와/과 별도로", english: "separately; apart from; independently of", unit: 14, chapter: 53, type: "particle" },
  { id: "u14_c53_22", native: "요원", english: "a (government) agent; “important member”", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_23", native: "운송(하다/되다)", english: "transportation (to transport/to be transported)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_24", native: "원조(하다/받다)", english: "(monetary and material) aid; support (to aid/to be aided)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_25", native: "이질감", english: "sense of difference; foreignness; alienation; “different matter feeling”", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_26", native: "이탈(하다)", english: "breakaway (to break away from; to desert; to leave)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_27", native: "자산", english: "assets; property", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_28", native: "재개(하다/되다)", english: "reopening; resumption; recommencement (to resume/to be resumed)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_29", native: "저하(시키다/되다)", english: "a fall (in rate, degree, or amount); a drop; a deterioration (to lower/to be lowered)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_30", native: "정착(하다)", english: "settlement; establishment (to settle down; to establish)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_31", native: "지시(하다/내리다)", english: "directions; instructions; orders (to direct; to order)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_32", native: "진입(하다)", english: "enter; entry (to enter; to go into)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_33", native: "차별(하다/받다/당하다)", english: "discrimination; differentiation (to discriminate; to differentiate/to be discriminated [against]; to be differentiated)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_34", native: "초기", english: "beginning; the early (initial) stage", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_35", native: "추방(하다/시키다/되다)", english: "an expulsion; a deportation; exile (to expel; to deport/to be expelled; to be deported)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_36", native: "출신(이다)", english: "(one’s national, academic, political, etc.) origin (to come from)", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_37", native: "취재", english: "news coverage; news gathering; “acquire (news) material”", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_38", native: "취재(하다)", english: "news coverage; news gathering; “obtain (news) material” (to cover; to gather)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_39", native: "~측", english: "side; party", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_40", native: "친선", english: "friendly; goodwill", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_41", native: "탈북(하다)", english: "defection from North Korea; “escape from North” (to defect from North Korea)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_42", native: "탈출(하다)", english: "escape (to escape)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_43", native: "할인점", english: "a discount store", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_44", native: "실어오다/가다/나르다", english: "to transport; to carry (in a vehicle); “to load and come/go/carry”", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_45", native: "삼다", english: "to make/adopt (a person to be one’s …)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_46", native: "~(을/를) 내리다", english: "to issue (an order, a warning, etc.)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_47", native: "떳떳하다", english: "to have a clean conscience; to be honorable; to have nothing to hide", unit: 14, chapter: 53, type: "adjective" },
  { id: "u14_c53_48", native: "들어서다", english: "to enter; to go into; to step in(to)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_49", native: "배경", english: "background; “background scene”", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_50", native: "세우다", english: "to found; to establish", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_51", native: "어학(원)", english: "language (institute)", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_52", native: "애쓰다", english: "to make an effort; to exert", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_53", native: "연구(하다)", english: "research (to research)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_54", native: "업체", english: "a (business) enterprise", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_55", native: "예금(하다)", english: "savings; deposit (to save money in the bank)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_56", native: "앞장서다", english: "to take the lead", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_57", native: "주재(하다)", english: "residing; stationing (to reside/to be stationed)", unit: 14, chapter: 53, type: "verb" },
  { id: "u14_c53_58", native: "~ 톤", english: "a ton", unit: 14, chapter: 53, type: "noun" },
  { id: "u14_c53_59", native: "회담(하다/열다)", english: "a conference; a talk; “meet and talk” (to have a conference)", unit: 14, chapter: 53, type: "verb" },
];
