export const chapter8 = [
    { id: "u2_c8_01", native: "거기", english: "there", unit: 2, chapter: 8, type: "pronoun" },
    { id: "u2_c8_02", native: "놀다", english: "to play; to hang out", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_03", native: "늦게", english: "late", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_04", native: "도착(하다)", english: "arrival (to arrive)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_05", native: "돌아다니다", english: "to go around; to roam", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_06", native: "떠나다", english: "to leave (a place)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_07", native: "막히다", english: "to be blocked; to be congested", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_08", native: "바닷가", english: "seashore; beach", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_09", native: "박물관", english: "a museum", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_10", native: "선물", english: "a gift; a present", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_11", native: "아시아", english: "Asia", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_12", native: "오래", english: "for a long time; long", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_13", native: "운전(하다)", english: "driving (to drive)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_14", native: "출발(하다)", english: "departure (to depart)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_15", native: "춤(을) 추다", english: "to dance", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_16", native: "피곤하다", english: "to be tired", unit: 2, chapter: 8, type: "adjective" },
    { id: "u2_c8_17", native: "한복", english: "traditional Korean clothing", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_18", native: "날", english: "day", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_19", native: "대령", english: "Colonel (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_20", native: "대위", english: "Captain (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_21", native: "대장", english: "General (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_22", native: "만들다", english: "to make", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_23", native: "모이다", english: "to gather; to meet", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_24", native: "소령", english: "Lieutenant Colonel (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_25", native: "소위", english: "Second Lieutenant (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_26", native: "소장", english: "Major General (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_27", native: "술", english: "alcohol; liquor", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_28", native: "-아/어 보다", english: "to try doing ~", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_29", native: "어제", english: "yesterday", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_30", native: "장교", english: "officer (military)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_31", native: "장군", english: "General (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_32", native: "준위", english: "Warrant Officer (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_33", native: "준장", english: "Brigadier General (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_34", native: "중령", english: "Lieutenant Colonel (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_35", native: "중위", english: "First Lieutenant (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_36", native: "중장", english: "Lieutenant General (military rank)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_37", native: "즐겁다", english: "to be enjoyable; to be fun", unit: 2, chapter: 8, type: "adjective" },
    { id: "u2_c8_38", native: "진급(하다)", english: "promotion (to be promoted)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_39", native: "처음(으로)", english: "for the first time", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_40", native: "축하(하다)", english: "congratulation (to congratulate)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_41", native: "그냥", english: "just; simply", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_42", native: "그래", english: "yes; that's right; so", unit: 2, chapter: 8, type: "interjection" },
    { id: "u2_c8_43", native: "기념품", english: "a souvenir", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_44", native: "돌아가다", english: "to return; to go back", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_45", native: "~ 동안", english: "during; for (duration)", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_46", native: "또", english: "again; also", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_47", native: "레스토랑", english: "restaurant", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_48", native: "~만", english: "only", unit: 2, chapter: 8, type: "particle" },
    { id: "u2_c8_49", native: "바쁘다", english: "to be busy", unit: 2, chapter: 8, type: "adjective" },
    { id: "u2_c8_50", native: "수족관", english: "aquarium", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_51", native: "시험(보다)", english: "exam (to take an exam)", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_52", native: "심심하다", english: "to be bored", unit: 2, chapter: 8, type: "adjective" },
    { id: "u2_c8_53", native: "-아/어야 하다/되다", english: "must; have to", unit: 2, chapter: 8, type: "verb" },
    { id: "u2_c8_54", native: "여기저기", english: "here and there; everywhere", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_55", native: "연휴", english: "long holiday; consecutive holidays", unit: 2, chapter: 8, type: "noun" },
    { id: "u2_c8_56", native: "왜", english: "why", unit: 2, chapter: 8, type: "adverb" },
    { id: "u2_c8_57", native: "응", english: "yes (casual)", unit: 2, chapter: 8, type: "interjection" },
    { id: "u2_c8_58", native: "집안일(하다)", english: "housework (to do housework)", unit: 2, chapter: 8, type: "verb" },
];
