export const chapter44 = [
  { id: "u11_c44_01", native: "간소(화)(하다/되다)", english: "a simplification (to simplify)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_02", native: "경기장", english: "a (sports) stadium; a (sports) arena", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_03", native: "경쟁(하다)", english: "competition (to compete)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_04", native: "골(을) 넣다", english: "to score a goal; to put in a goal", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_05", native: "광장", english: "a plaza; “spacious place”", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_06", native: "금/은/동", english: "gold/silver/bronze", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_07", native: "(대)답(하다)", english: "an answer; a reply (to answer; to reply)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_08", native: "대단하다", english: "to be great; to be enormous; to be excellent", unit: 11, chapter: 44, type: "adjective" },
  { id: "u11_c44_09", native: "대항(하다)", english: "act in opposition; countering; against (to counter; to act in opposition)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_10", native: "덜다", english: "to lessen; to relieve; to reduce", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_11", native: "동계", english: "winter season", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_12", native: "매달", english: "a medal", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_13", native: "목표", english: "a goal; a target", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_14", native: "밀리다", english: "to be congested; to be backed up; “to get behind”", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_15", native: "바꾸다/바뀌다", english: "to change/to be changed", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_16", native: "본선", english: "post-preliminary matches; the finals; “main selection”", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_17", native: "본인", english: "oneself; “main person”", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_18", native: "승리(하다)", english: "victory (to win)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_19", native: "신(이) 나다", english: "to be excited", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_20", native: "안정(적)(되다)", english: "stability (stable) (to be stable)", unit: 11, chapter: 44, type: "adjective" },
  { id: "u11_c44_21", native: "역전(하다/되다)", english: "a reversal; a turnabout (victory); (to reverse/to be reversed)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_22", native: "연기(하다)", english: "acting (to act)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_23", native: "연예인", english: "an entertainer", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_24", native: "예상(하다/되다)", english: "expectancy; anticipation; prospect (to expect; to anticipate/to be expected; to be anticipated)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_25", native: "예선", english: "the preliminaries; preliminary round; preliminary selection", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_26", native: "온 ~", english: "entire; all; whole", unit: 11, chapter: 44, type: "determiner" },
  { id: "u11_c44_27", native: "올림픽", english: "Olympics", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_28", native: "응원(하다)", english: "cheering (to cheer; to root for)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_29", native: "의사", english: "intention", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_30", native: "일부", english: "a part; a portion; some", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_31", native: "장래", english: "the future", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_32", native: "재능", english: "talent; aptitude", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_33", native: "전반전", english: "the first half of a game", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_34", native: "정체(되다)", english: "stagnation (to be stagnated)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_35", native: "제사(지내다)", english: "an ancestral worship ritual (to perform an ancestral ritual)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_36", native: "제외(하다/되다)", english: "exclusion (to exclude)/to be excluded", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_37", native: "종목", english: "an event", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_38", native: "종일", english: "all day (long); “(till) end of a day”", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_39", native: "차량", english: "vehicles; cars", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_40", native: "체계적", english: "systematic", unit: 11, chapter: 44, type: "adjective" },
  { id: "u11_c44_41", native: "체증", english: "dyspepsia; (traffic) congestion; indigestion", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_42", native: "최대", english: "the biggest; the largest", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_43", native: "프로", english: "a professional; an expert", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_44", native: "프로게이머", english: "a pro(fessional) gamer", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_45", native: "피겨 스케이팅", english: "figure skating", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_46", native: "하계", english: "the summer (season)", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_47", native: "행렬", english: "a queue; a procession", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_48", native: "허락(하다)", english: "permission; approval (to permit; to approve)", unit: 11, chapter: 44, type: "verb" },
  { id: "u11_c44_49", native: "현실(적)", english: "reality; actuality", unit: 11, chapter: 44, type: "noun" },
  { id: "u11_c44_50", native: "휴양지", english: "a resort; “resting and nurturing place”", unit: 11, chapter: 44, type: "noun" },
];
