export const chapter48 = [
  { id: "u12_c48_01", native: "간접", english: "indirect", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_02", native: "감염(시키다/되다)", english: "infection (to infect/to be infected)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_03", native: "갑상선암", english: "thyroid cancer", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_04", native: "개선(하다/되다)", english: "improvement (to improve/to be improved)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_05", native: "과로(하다)", english: "overwork (to overwork)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_06", native: "꾸미다", english: "to decorate; to embellish", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_07", native: "꾸준하다", english: "to be steady; to be continuous", unit: 12, chapter: 48, type: "adjective" },
  { id: "u12_c48_08", native: "대장암", english: "colon cancer; “big intestine cancer”", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_09", native: "노약자", english: "the old and the infirm; “the old and the weak”", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_10", native: "녹지", english: "a green track of land; greens; “green land”", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_11", native: "면역(력)", english: "immunity; “immunity (power)”", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_12", native: "목돈", english: "a large sum of money", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_13", native: "발병(하다;되다)", english: "the outbreak of one’s illness (a disease breaks out); an attack (of a disease)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_14", native: "비타민", english: "a vitamin", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_15", native: "뽑다", english: "to unplug; to pull out", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_16", native: "소용(있다/없다)", english: "use (to be useful/to be useless)", unit: 12, chapter: 48, type: "adjective" },
  { id: "u12_c48_17", native: "소재", english: "basic material; basic matter", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_18", native: "수면(취하다)", english: "sleep (to get sleep)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_19", native: "신종플루", english: "H1N1; “new type flu”", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_20", native: "심장병", english: "heart disease", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_21", native: "예방접종(하다/받다)", english: "a (preventive) vaccination; a (preventive) inoculation (to vaccinate; to inoculate/to be vaccinated)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_22", native: "위생", english: "hygiene; sanitation", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_23", native: "위주(의/로)", english: "-centered; -oriented/ mainly (with/for)", unit: 12, chapter: 48, type: "particle" },
  { id: "u12_c48_24", native: "유발(하다/되다)", english: "induction; cause (to induce/to be induced)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_25", native: "유방암", english: "breast cancer", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_26", native: "정체(되다)", english: "stagnation (to be stagnated)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_27", native: "재채기(하다)", english: "sneeze (to sneeze)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_28", native: "전염(시키다/되다)", english: "contagion; infection (to infect/to be infected)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_29", native: "전염성", english: "contagious(ness); infectious(ness)", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_30", native: "전파(하다/되다)", english: "spread (of virus, message, etc.); transmission (to spread/to be transmitted)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_31", native: "(절)반", english: "a half; “half cut”", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_32", native: "제안(하다/되다)", english: "a suggestion; a proposal (to suggest/to be suggested)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_33", native: "조언(하다)", english: "advice; counsel; a tip; “assisting language” (to give advice; to counsel; to give a tip)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_34", native: "주사(놓다/맞다)", english: "an injection; a shot (to give a shot/to get a shot)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_35", native: "증세", english: "a symptom", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_36", native: "집계(하다/되다)", english: "tally; total; count (to tally/to be tallied)", unit: 12, chapter: 48, type: "verb" },
  { id: "u12_c48_37", native: "천식", english: "(bronchial) asthma", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_38", native: "천연", english: "natural", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_39", native: "폐암", english: "lung cancer", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_40", native: "플러그", english: "a plug", unit: 12, chapter: 48, type: "noun" },
  { id: "u12_c48_41", native: "탓", english: "a fault", unit: 12, chapter: 48, type: "noun" },
];
