export const chapter40 = [
  { id: "u10_c40_01", native: "가난(하다)", english: "poverty (to be poor; to be destitute)", unit: 10, chapter: 40, type: "adjective" },
  { id: "u10_c40_02", native: "가짜", english: "a fake; a counterfeit; an imitation", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_03", native: "가출(하다)", english: "running away from home; “leaving home” (to run away from home)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_04", native: "감동(적)", english: "moving; touching", unit: 10, chapter: 40, type: "adjective" },
  { id: "u10_c40_05", native: "거짓말(하다)", english: "a lie; “false language” (to lie)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_06", native: "결국", english: "finally; eventually; in the end", unit: 10, chapter: 40, type: "adverb" },
  { id: "u10_c40_07", native: "교도소", english: "a prison; “correctional place”", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_08", native: "구속(하다/되다)", english: "detention (to detain/to be detained)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_09", native: "기사", english: "a (newspaper or magazine) article", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_10", native: "납치(하다/되다;당하다)", english: "abduction; kidnapping (to kidnap/to be kidnapped)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_11", native: "도피(하다)", english: "escape; running away (to escape; to run away)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_12", native: "들키다", english: "to be caught (red-handed)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_13", native: "마약", english: "a drug; narcotics; “hemp drug”", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_14", native: "모으다", english: "to collect; to gather", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_15", native: "문제아", english: "a problem child", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_16", native: "~범", english: "a criminal; a person who committed [a crime]", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_17", native: "범죄", english: "a crime; “criminal sin”", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_18", native: "벗어나다", english: "to get out of; to break away (from); to free oneself (from)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_19", native: "복사(하다)", english: "copying (to copy; to photocopy)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_20", native: "복사기", english: "a copier; a copying machine", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_21", native: "비행 청소년", english: "a juvenile delinquent", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_22", native: "사기(치다/당하다)", english: "a fraud; a swindle (to swindle; to con/to be swindled; to be conned)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_23", native: "살인(하다)", english: "a murder; homicide; “killing a person” (to kill a person; to murder)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_24", native: "살해(하다/되다;당하다)", english: "a murder; homicide; “killing and damaging” (to murder/to be murdered)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_25", native: "사용(하다/되다)", english: "use (to use/to be used)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_26", native: "성범죄", english: "a sex crime; sex offense", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_27", native: "성폭행(하다/당하다)", english: "a sexual assault (to commit a sexual assault/to be sexually assaulted)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_28", native: "수사(하다)", english: "(police) investigation (to investigate)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_29", native: "수표", english: "a bank check", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_30", native: "시민", english: "a citizen", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_31", native: "시체", english: "a corpse; a dead body", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_32", native: "실패(하다)", english: "failure (to fail)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_33", native: "어울리다", english: "to hang out with; to associate with", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_34", native: "용돈", english: "an allowance", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_35", native: "용의자", english: "a suspect", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_36", native: "위조(하다)", english: "fabrication; forgery (to fabricate; to counterfeit; to fake)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_37", native: "유괴(하다/되다;당하다)", english: "kidnapping; abduction (to kidnap/to be kidnapped)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_38", native: "인터뷰(하다)", english: "an interview (to interview)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_39", native: "전과자", english: "an ex-convict; “person who has previous error”", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_40", native: "종업원", english: "an employee; a worker", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_41", native: "죽이다", english: "to kill", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_42", native: "중독(되다)", english: "an addiction; “(in) the middle of poison” (to be addicted)", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_43", native: "진짜", english: "really; real; genuine", unit: 10, chapter: 40, type: "adverb" },
  { id: "u10_c40_44", native: "~짜리", english: "(a thing) worth ~", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_45", native: "잡히다", english: "to be caught", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_46", native: "피우다", english: "to smoke; to set fire", unit: 10, chapter: 40, type: "verb" },
  { id: "u10_c40_47", native: "피해자", english: "a victim", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_48", native: "평범하다", english: "to be ordinary", unit: 10, chapter: 40, type: "adjective" },
  { id: "u10_c40_49", native: "혐의", english: "a suspicion; charge", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_50", native: "형(벌)", english: "a sentence; a punishment; a penalty", unit: 10, chapter: 40, type: "noun" },
  { id: "u10_c40_51", native: "형사", english: "a (police) detective; a (police) investigator; a criminal case; “criminal affair”", unit: 10, chapter: 40, type: "noun" },
];
