export const chapter4 = [
    { id: "u1_c4_01", native: "가깝다", english: "to be close / near", unit: 1, chapter: 4, type: "adjective" },
    { id: "u1_c4_02", native: "건너편", english: "opposite side", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_03", native: "맞은편", english: "opposite side", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_04", native: "건물", english: "building", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_05", native: "기숙사", english: "dormitory", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_06", native: "도서관", english: "library", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_07", native: "독일", english: "Germany", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_08", native: "러시아", english: "Russia", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_09", native: "말", english: "horse", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_10", native: "멀다", english: "to be far", unit: 1, chapter: 4, type: "adjective" },
    { id: "u1_c4_11", native: "미국", english: "USA", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_12", native: "본부", english: "headquarters", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_13", native: "불어", english: "French (language short)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_14", native: "사람", english: "person", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_15", native: "스페인", english: "Spain", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_16", native: "아랍", english: "Arab", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_17", native: "~에서", english: "at / in / from (location)", unit: 1, chapter: 4, type: "particle" },
    { id: "u1_c4_18", native: "영국", english: "UK / England", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_19", native: "영어", english: "English (language)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_20", native: "우체국", english: "post office", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_21", native: "운동장", english: "playground / sports field", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_22", native: "일본", english: "Japan", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_23", native: "일본어", english: "Japanese (language)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_24", native: "조금", english: "some", unit: 1, chapter: 4, type: "adverb" },
    { id: "u1_c4_25", native: "좀", english: "some (casual)", unit: 1, chapter: 4, type: "adverb" },
    { id: "u1_c4_26", native: "주차장", english: "parking lot", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_27", native: "중국", english: "China", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_28", native: "중국어", english: "Chinese (language)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_29", native: "프랑스", english: "France", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_30", native: "프랑스어", english: "French (language)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_31", native: "학교", english: "school", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_32", native: "한국", english: "Korea", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_33", native: "한국어", english: "Korean (language)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_34", native: "공책", english: "notebook", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_35", native: "교실", english: "classroom", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_36", native: "끄다", english: "to turn off", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_37", native: "단어", english: "vocabulary", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_38", native: "닫다", english: "to close", unit: 1, chapter: 4, type: "adjective" },
    { id: "u1_c4_39", native: "덮다", english: "to cover", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_40", native: "떠들다", english: "to make noise", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_41", native: "문", english: "door", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_42", native: "사무실", english: "office", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_43", native: "사전", english: "dictionary", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_44", native: "수업", english: "course", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_45", native: "쓰다", english: "to write", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_46", native: "쓰레기통", english: "trash can", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_47", native: "앉다", english: "to sit", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_48", native: "열다", english: "to open", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_49", native: "-(으)세요", english: "please do", unit: 1, chapter: 4, type: "particle" },
    { id: "u1_c4_50", native: "-지 마세요", english: "please don't", unit: 1, chapter: 4, type: "particle" },
    { id: "u1_c4_51", native: "일어서다", english: "to stand up", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_52", native: "자리", english: "seat", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_53", native: "줄다", english: "to decrease", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_54", native: "지우다", english: "to erase", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_55", native: "칠판", english: "blackboard", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_56", native: "켜다", english: "to turn on", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_57", native: "펴다", english: "to spread", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_58", native: "가다", english: "to go", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_59", native: "길", english: "road", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_60", native: "나오다", english: "to come out", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_61", native: "남", english: "south", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_62", native: "남쪽", english: "south (direction)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_63", native: "네 번째", english: "fourth", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_64", native: "넷째", english: "fourth (alt)", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_65", native: "돌다", english: "to turn", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_66", native: "동", english: "east", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_67", native: "동쪽", english: "east (direction)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_68", native: "두 번째", english: "second", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_69", native: "둘째", english: "second (alt)", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_70", native: "모르다", english: "to not know", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_71", native: "바로", english: "right now", unit: 1, chapter: 4, type: "adverb" },
    { id: "u1_c4_72", native: "북", english: "north", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_73", native: "북쪽", english: "north (direction)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_74", native: "사거리", english: "intersection", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_75", native: "서", english: "west", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_76", native: "서쪽", english: "west (direction)", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_77", native: "세 번째", english: "third", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_78", native: "셋째", english: "third (alt)", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_79", native: "식당", english: "restaurant / cafeteria", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_80", native: "알다", english: "to know", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_81", native: "어떻게", english: "how", unit: 1, chapter: 4, type: "adverb" },
    { id: "u1_c4_82", native: "오다", english: "to come", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_83", native: "우회전하다", english: "to turn right", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_84", native: "~(으)로", english: "toward / by way of", unit: 1, chapter: 4, type: "particle" },
    { id: "u1_c4_85", native: "~(으)나", english: "but / however", unit: 1, chapter: 4, type: "particle" },
    { id: "u1_c4_86", native: "정문", english: "main gate", unit: 1, chapter: 4, type: "noun" },
    { id: "u1_c4_87", native: "좌회전하다", english: "to turn left", unit: 1, chapter: 4, type: "verb" },
    { id: "u1_c4_88", native: "~쪽", english: "side", unit: 1, chapter: 4, type: "particle" },
    { id: "u1_c4_89", native: "곧장", english: "straight", unit: 1, chapter: 4, type: "adverb" },
    { id: "u1_c4_90", native: "첫 번째", english: "first", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_91", native: "첫째", english: "first (alt)", unit: 1, chapter: 4, type: "numeral" },
    { id: "u1_c4_92", native: "체육관", english: "gymnasium", unit: 1, chapter: 4, type: "noun" },
];
