export const chapter49 = [
  { id: "u13_c49_01", native: "거래(하다/되다)", english: "a business transaction; a trade; a deal (to do business with; to transact/to be traded)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_02", native: "개척(하다/되다)", english: "pioneering; developing (to pioneer; to develop/to be pioneered; to be developed)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_03", native: "공업", english: "the manufacturing industry", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_04", native: "구조", english: "structure", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_05", native: "국내총생산", english: "Gross Domestic Product (GDP)", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_06", native: "급감(하다)", english: "rapid decrease (to decrease rapidly)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_07", native: "급증(하다)", english: "rapid increase (to increase rapidly)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_08", native: "기계", english: "a machine", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_09", native: "농산물", english: "agricultural products", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_10", native: "농업", english: "agriculture", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_11", native: "단기(적)", english: "short-term", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_12", native: "매출", english: "sales; “selling out”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_13", native: "무역수지", english: "trade balance", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_14", native: "반도체", english: "a semiconductor", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_15", native: "비중", english: "relative importance; “relative weight”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_16", native: "산업", english: "industry", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_17", native: "서비스업", english: "a service industry", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_18", native: "석유", english: "oil; petroleum; “stone oil”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_19", native: "손해", english: "a loss; damage; harm", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_20", native: "수수료", english: "a commission; a charge", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_21", native: "수요", english: "demand", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_22", native: "수익(성)", english: "a profit (profitability)", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_23", native: "수준", english: "a level", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_24", native: "순위/~위", english: "ranking; ~th place", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_25", native: "예금(하다)", english: "savings; deposit (to save money in the bank)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_26", native: "원유", english: "crude oil; “raw oil”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_27", native: "원자재", english: "raw materials", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_28", native: "입금(하다/되다)", english: "deposit (to deposit/to be deposited)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_29", native: "장기(적)", english: "long-term", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_30", native: "장단점", english: "strength and weakness", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_31", native: "적금(에/을 들다)", english: "installment savings (to save money in an installment savings account)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_32", native: "적자", english: "a deficit; a loss; “red letter”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_33", native: "적합(하다)", english: "to be suitable", unit: 13, chapter: 49, type: "adjective" },
  { id: "u13_c49_34", native: "전반적", english: "whole; overall", unit: 13, chapter: 49, type: "adjective" },
  { id: "u13_c49_35", native: "전자", english: "electronic(s)", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_36", native: "조", english: "trillion", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_37", native: "조선", english: "shipbuilding", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_38", native: "조선업", english: "shipbuilding industry", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_39", native: "주식/증권", english: "stock", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_40", native: "주요", english: "main; principal; major", unit: 13, chapter: 49, type: "determiner" },
  { id: "u13_c49_41", native: "지급(하다/되다)", english: "payment (to pay/to be paid)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_42", native: "첨단기술", english: "cutting-edge technology; state-of-the art technology", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_43", native: "통계", english: "statistics", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_44", native: "통장", english: "a bankbook", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_45", native: "투자(하다)", english: "investment (to invest)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_46", native: "펀드", english: "a fund", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_47", native: "평균", english: "average; mean", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_48", native: "품목", english: "an item", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_49", native: "하락(하다)", english: "drop; fall; decrease (to fall)", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_50", native: "호황", english: "an economic boom", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_51", native: "흑자", english: "a surplus; “black letter”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_52", native: "내다보다", english: "to foresee; “look out”", unit: 13, chapter: 49, type: "verb" },
  { id: "u13_c49_53", native: "~년대", english: "(decade of) the ~s, as in 90년대 (the ’90s)", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_54", native: "약세", english: "weak trend (in stock, currency exchange rate, or price); “weak force”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_55", native: "강세", english: "strong trend (in stock, currency exchange rate, or price); “strong force”", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_56", native: "불황", english: "economic recession; economic slump", unit: 13, chapter: 49, type: "noun" },
  { id: "u13_c49_57", native: "지속적", english: "continuous", unit: 13, chapter: 49, type: "adjective" },
  { id: "u13_c49_58", native: "–(으)려던 참이다", english: "I was just about to do …", unit: 13, chapter: 49, type: "particle" },
  { id: "u13_c49_59", native: "~에도/–(으)ㄴ/는데도 불구하고", english: "in spite of; despite", unit: 13, chapter: 49, type: "particle" },
];
