export const chapter26 = [
  { id: "u7_c26_01", native: "강사", english: "an instructor", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_02", native: "결혼식", english: "a wedding ceremony", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_03", native: "결혼정보회사", english: "a marriage agency; “marriage information company”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_04", native: "공", english: "a ball", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_05", native: "교수", english: "a professor", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_06", native: "궁금하다", english: "to be curious; to wonder about", unit: 7, chapter: 26, type: "adjective" },
  { id: "u7_c26_07", native: "떡", english: "a rice cake", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_08", native: "돌", english: "the first birthday", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_09", native: "똑똑하다", english: "to be clever; to be bright", unit: 7, chapter: 26, type: "adjective" },
  { id: "u7_c26_10", native: "띠", english: "a birth year of the Asian zodiac", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_11", native: "마이크", english: "a mic(rophone)", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_12", native: "말", english: "a horse", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_13", native: "(맞)선(보다)", english: "an arranged meeting with a prospective bride/groom (to meet one’s prospective bride/groom in an arranged meeting)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_14", native: "미리", english: "beforehand; in advance; previously", unit: 7, chapter: 26, type: "adverb" },
  { id: "u7_c26_15", native: "백일", english: "the 100th day (since birth)", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_16", native: "뱀", english: "a snake", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_17", native: "소개팅/미팅(하다)", english: "a blind date (to go on a blind date)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_18", native: "상", english: "a (food) table", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_19", native: "상대(방)", english: "the other party; the opposite party; an opponent; a rival", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_20", native: "실", english: "thread", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_21", native: "쌀", english: "rice (as a crop); (uncooked) rice", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_22", native: "신랑", english: "a groom; “new husband”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_23", native: "신부", english: "a bride; “new wife”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_24", native: "시집(가다)", english: "getting married (for a woman); “(woman’s) in-laws’ home” (to get married)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_25", native: "용", english: "a dragon", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_26", native: "원숭이", english: "a monkey", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_27", native: "웨딩드레스", english: "a wedding dress; a wedding gown", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_28", native: "–(으)ㄴ/는 대신(에)/~ 대신(에)", english: "instead of; rather than; in place of", unit: 7, chapter: 26, type: "particle" },
  { id: "u7_c26_29", native: "–(으)ㄹ 예정/계획/생각이다", english: "to intend to; to plan to", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_30", native: "일시", english: "time and date; “day and time”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_31", native: "자라다", english: "to grow (up); to be brought up", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_32", native: "장가(가다/들다)", english: "getting married (for a man); taking a wife; “(man’s) in-laws’ home” (to get married)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_33", native: "장소", english: "a place; a location", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_34", native: "재혼(하다)", english: "remarriage; second marriage (to be remarried)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_35", native: "전문적", english: "special; expert; professional", unit: 7, chapter: 26, type: "adjective" },
  { id: "u7_c26_36", native: "조건", english: "a condition; a qualification; a requirement", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_37", native: "주례(하다/서다)", english: "officiating at a wedding; an officiator of a wedding ceremony; “master of the (wedding) ceremony” (to officiate at a wedding ceremony)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_38", native: "중매(하다/서다)", english: "matchmaking (to matchmake; to act as a go-between)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_39", native: "쥐", english: "a rat; a mouse", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_40", native: "참", english: "really; truly; truth", unit: 7, chapter: 26, type: "adverb" },
  { id: "u7_c26_41", native: "참석(하다)", english: "attendance; participation (to attend; to be present at)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_42", native: "청첩장", english: "a wedding invitation; “wedding invitation card”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_43", native: "초대장", english: "an invitation; “invitation card”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_44", native: "축의금", english: "congratulatory money", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_45", native: "칠순", english: "the 70th birthday", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_46", native: "팔순", english: "the 80th birthday", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_47", native: "호랑이", english: "a tiger", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_48", native: "활달하다", english: "to be liberal; to be broad-minded", unit: 7, chapter: 26, type: "adjective" },
  { id: "u7_c26_49", native: "행복(하다)", english: "happiness; well-being (to be happy)", unit: 7, chapter: 26, type: "adjective" },
  { id: "u7_c26_50", native: "학원", english: "a private institute; an academy", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_51", native: "피로연(하다)", english: "a wedding reception (to give a wedding reception)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_52", native: "사회(보다)", english: "a chairperson; an emcee; a master of ceremonies (to conduct a meeting or ceremony)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_53", native: "약혼(하다)", english: "an engagement; “promising a marriage” (to be engaged)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_54", native: "예물", english: "a wedding gift; “(wedding) ceremony item”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_55", native: "예식장", english: "a wedding hall; “(wedding) ceremony place”", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_56", native: "연애(하다)", english: "courting; dating (to court; to date)", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_57", native: "연필", english: "a pencil", unit: 7, chapter: 26, type: "noun" },
  { id: "u7_c26_58", native: "얼마", english: "some", unit: 7, chapter: 26, type: "determiner" },
  { id: "u7_c26_59", native: "잡다", english: "to grab; to catch", unit: 7, chapter: 26, type: "verb" },
  { id: "u7_c26_60", native: "–아/어(서) 죽겠다", english: "expression used to exaggerate feelings about a condition", unit: 7, chapter: 26, type: "verb" },
];
