export const chapter21 = [
    { id: "u6_c21_01", native: "고층", english: "high-rise; high floor", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_02", native: "다용도실", english: "utility room; multipurpose room", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_03", native: "단독주택", english: "detached house; single-family home", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_04", native: "단지", english: "apartment complex; housing complex", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_05", native: "담(장)", english: "wall; fence", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_06", native: "마루", english: "wooden floor; living room floor", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_07", native: "멀리", english: "far away", unit: 6, chapter: 21, type: "adverb" },
    { id: "u6_c21_08", native: "바닥", english: "floor; ground", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_09", native: "밭다", english: "to be wide; to be spacious", unit: 6, chapter: 21, type: "adjective" },
    { id: "u6_c21_10", native: "베란다/발코니", english: "veranda; balcony", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_11", native: "벽", english: "wall", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_12", native: "상가", english: "commercial building; shopping area", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_13", native: "새 ~", english: "new ~", unit: 6, chapter: 21, type: "determiner" },
    { id: "u6_c21_14", native: "안방", english: "master bedroom", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_15", native: "어둡다", english: "to be dark", unit: 6, chapter: 21, type: "adjective" },
    { id: "u6_c21_16", native: "온돌", english: "ondol (Korean floor heating)", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_17", native: "이사(하다)", english: "moving (to move house)", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_18", native: "정원", english: "garden; yard", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_19", native: "지붕", english: "roof", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_20", native: "천장", english: "ceiling", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_21", native: "특히", english: "especially; particularly", unit: 6, chapter: 21, type: "adverb" },
    { id: "u6_c21_22", native: "편의시설", english: "convenience facilities", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_23", native: "현관", english: "entrance; front door", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_24", native: "계약(하다)", english: "contract (to make a contract)", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_25", native: "계약금", english: "down payment; deposit", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_26", native: "공기", english: "air", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_27", native: "공인중개사", english: "licensed real estate agent", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_28", native: "구하다", english: "to look for; to find", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_29", native: "꽤", english: "quite; fairly; pretty", unit: 6, chapter: 21, type: "adverb" },
    { id: "u6_c21_30", native: "나머지", english: "the rest; remainder", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_31", native: "나중에", english: "later; in the future", unit: 6, chapter: 21, type: "adverb" },
    { id: "u6_c21_32", native: "낫다", english: "to be better; to recover", unit: 6, chapter: 21, type: "adjective" },
    { id: "u6_c21_33", native: "-(으)려고 하다", english: "to intend to; to plan to", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_34", native: "보증금", english: "security deposit", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_35", native: "부동산", english: "real estate", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_36", native: "월세", english: "monthly rent", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_37", native: "전망", english: "view; prospect", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_38", native: "전세", english: "key money; lump-sum deposit", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_39", native: "지역", english: "area; region; district", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_40", native: "-(으)ㄴ/는 편이다", english: "to tend to be; relatively", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_41", native: "~평", english: "~ pyeong (Korean area unit)", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_42", native: "한겨울에", english: "in midwinter", unit: 6, chapter: 21, type: "adverb" },
    { id: "u6_c21_43", native: "환경", english: "environment; surroundings", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_44", native: "광고", english: "advertisement", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_45", native: "도시가스", english: "city gas", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_46", native: "~동", english: "~ building; ~ dong (district)", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_47", native: "모든", english: "all; every", unit: 6, chapter: 21, type: "determiner" },
    { id: "u6_c21_48", native: "벌써", english: "already", unit: 6, chapter: 21, type: "adverb" },
    { id: "u6_c21_49", native: "신청(하다)", english: "application (to apply)", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_50", native: "싸다", english: "to be cheap; to be inexpensive", unit: 6, chapter: 21, type: "adjective" },
    { id: "u6_c21_51", native: "알리다", english: "to inform; to let know", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_52", native: "-(으)르까 하다", english: "to think about ~ing; to consider", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_53", native: "(~을/를) 싫어하다", english: "to dislike", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_54", native: "(~이/가)싫다", english: "to dislike; to hate", unit: 6, chapter: 21, type: "adjective" },
    { id: "u6_c21_55", native: "이삿짐", english: "moving baggage; household goods", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_56", native: "이삿짐 센터", english: "moving company", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_57", native: "전화국", english: "telephone company", unit: 6, chapter: 21, type: "noun" },
    { id: "u6_c21_58", native: "정리(하다/되다)", english: "arrangement (to arrange / to be arranged)", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_59", native: "정하다", english: "to decide; to set", unit: 6, chapter: 21, type: "verb" },
    { id: "u6_c21_60", native: "정확하다", english: "to be accurate; to be correct", unit: 6, chapter: 21, type: "adjective" },
    { id: "u6_c21_61", native: "평일", english: "weekday", unit: 6, chapter: 21, type: "noun" },
];
