export const chapter47 = [
  { id: "u12_c47_01", native: "겉", english: "a surface; a face; a facade", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_02", native: "경차", english: "a compact car; “a light car”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_03", native: "공해", english: "pollution; “public hazard”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_04", native: "과다(하다)", english: "an excess; a superabundance; “excessively a lot” (to be excessive/ superabundant)", unit: 12, chapter: 47, type: "adjective" },
  { id: "u12_c47_05", native: "구체적(이다)", english: "(to be) concrete; (to be) specific", unit: 12, chapter: 47, type: "adjective" },
  { id: "u12_c47_06", native: "꽁초", english: "a cigarette butt", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_07", native: "냉방", english: "air conditioning; air cooling; “cool room”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_08", native: "더럽히다", english: "to make unclean; to defile; to soil", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_09", native: "뚜껑", english: "a lid; a cover; a cap", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_10", native: "말리다", english: "to dry (laundry, fish, etc.); to dehydrate (a thing)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_11", native: "매연", english: "sooty smoke; exhaust gas", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_12", native: "물기", english: "wetness; dampness; “water feel”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_13", native: "물질", english: "matter; substance; material", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_14", native: "비닐봉지", english: "a plastic bag; “vinyl bag”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_15", native: "비료", english: "a fertilizer", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_16", native: "뿌리다", english: "to sprinkle; to scatter; to spray", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_17", native: "소각(하다/되다)", english: "burning up; incineration; destruction by fire (to incinerate/to be incinerated)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_18", native: "수거(하다/되다)", english: "collection (and taking away of things) (to collect/to be collected)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_19", native: "시장", english: "a mayor; “city chief”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_20", native: "식물", english: "a plant; plant life; vegetation; “planted thing”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_21", native: "실천(하다/되다)", english: "practice; putting (something) into practice (to practice/to be practiced)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_22", native: "썩다", english: "to become rotten; to decay; to corrode", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_23", native: "알루미늄", english: "aluminum", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_24", native: "압축(하다/되다)", english: "compression; flattening (to compress; to flatten/to be compressed; to be flattened)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_25", native: "없애다", english: "to get rid of; to remove", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_26", native: "에너지", english: "energy", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_27", native: "온실가스", english: "a greenhouse gas; “warm room gas”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_28", native: "요령", english: "a knack; a way; trickery", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_29", native: "우유", english: "milk; “cow milk”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_30", native: "유리", english: "glass", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_31", native: "자원", english: "resources", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_32", native: "자제(하다)", english: "refraining from (doing something); self-control (to refrain from; control oneself)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_33", native: "재활용", english: "recycling", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_34", native: "종량제", english: "the meter-rate system", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_35", native: "지나치다", english: "to go too far; to be too much; to be extreme", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_36", native: "짜다", english: "to squeeze; to wring", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_37", native: "캔", english: "a can", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_38", native: "캠페인(하다)", english: "a campaign; a drive (to campaign)", unit: 12, chapter: 47, type: "verb" },
  { id: "u12_c47_39", native: "친환경", english: "environment-friendly; eco-friendly; “pro-environment”", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_40", native: "팩", english: "a pack; a carton", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_41", native: "폐기물", english: "a disposable item; a useless item", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_42", native: "폐수", english: "wastewater", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_43", native: "폐지", english: "waste paper", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_44", native: "플라스틱", english: "plastics; a plastic", unit: 12, chapter: 47, type: "noun" },
  { id: "u12_c47_45", native: "홍보(하다)", english: "public relations; publicity (public) information; publicity (to do PR; to inform the public)", unit: 12, chapter: 47, type: "verb" },
];
