export const chapter50 = [
  { id: "u13_c50_01", native: "가리키다", english: "to point to; to denote; to mean", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_02", native: "감시(하다/받다)", english: "watch; guard; lookout; vigil; surveillance (to watch/to be watched)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_03", native: "개표(하다)", english: "the counting of votes; “opening a ballot” (to open the ballots)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_04", native: "검찰청", english: "public prosecutors office; “prosecutors bureau”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_05", native: "고소(하다/당하다)", english: "a complaint; an accusation; a legal action (to accuse; to be accused)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_06", native: "공정하다", english: "to be fair; to be equitable; to be impartial", unit: 13, chapter: 50, type: "adjective" },
  { id: "u13_c50_07", native: "구성(하다/되다)", english: "formation; composition; makeup (to form; to compose/to be composed of; to be made up of)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_08", native: "국무", english: "state affairs; “nation’s duties”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_09", native: "국회", english: "the National Assembly; “national meeting”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_10", native: "권한/~권", english: "authority; rights; jurisdiction; power", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_11", native: "기소(하다/되다)", english: "prosecution; indictment (to prosecute/to be prosecuted)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_12", native: "기획(하다/되다)", english: "planning; designing (to plan/to be planned)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_13", native: "낙선(하다)", english: "defeat in an election; failure in an election; “fall from a selection” (to lose an election)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_14", native: "단임(제)", english: "the single-term system; “single appointment system”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_15", native: "단체장", english: "head of the local government", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_16", native: "당선(시키다/되다)", english: "winning an election; being elected (to elect/to be elected)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_17", native: "대통령", english: "the president (of a country); “big governing”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_18", native: "도지사", english: "the governor of a province", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_19", native: "맡다", english: "to take charge of; to have custody of", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_20", native: "민사", english: "civil affairs", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_21", native: "민주주의", english: "democracy", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_22", native: "법원", english: "a court of justice; a courthouse", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_23", native: "보궐선거", english: "an election to fill a vacancy; a by-election", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_24", native: "보건", english: "health; “preservation of health”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_25", native: "~부", english: "a branch of government: “government office”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_26", native: "사법", english: "the administration of justice", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_27", native: "선거(하다)", english: "an election (to elect; to vote for)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_28", native: "선고(하다/받다)", english: "a verdict; an announcement (to sentence/to be sentenced)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_29", native: "소송(하다)", english: "a lawsuit; an action in law (to file a lawsuit)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_30", native: "~심(리)", english: "a trial; a hearing", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_31", native: "유권자", english: "an elector; a voter; “person with a right (to vote)”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_32", native: "유세(하다)", english: "stumping; a canvassing tour; a campaign (to go canvassing)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_33", native: "유죄", english: "guiltiness; guilt", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_34", native: "의원", english: "a member of the national assembly", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_35", native: "임기", english: "a term of office; “appointment term”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_36", native: "임명(하다/되다)", english: "an appointment; a nomination; designation (to appoint/to be appointed)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_37", native: "입법", english: "legislation; lawmaking; “establishing law”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_38", native: "입법부", english: "the legislative branch", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_39", native: "재임(하다/되다)", english: "serving a second term (to serve a second term/to be reappointed)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_40", native: "재판(하다/받다)", english: "a trial (to have a trial/to be on trial)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_41", native: "정당", english: "a political party", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_42", native: "정부", english: "a government", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_43", native: "정치", english: "politics; “political governing”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_44", native: "제기(하다/되다)", english: "submitting (a case to the court); bringing (an action against a person); raising (a question); (to submit/to be submitted)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_45", native: "지지(하다/받다)", english: "support; backing; espousal (to support/to be supported)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_46", native: "지휘(하다)", english: "commands; orders conducting; “giving orders with fingers” (to command; to order; to conduct)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_47", native: "집행유예", english: "probation; a suspended sentence", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_48", native: "징역", english: "imprisonment (with hard labor)", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_49", native: "총리", english: "the premier; the prime minister", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_50", native: "총선(거)", english: "a general election", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_51", native: "투명하다", english: "to be transparent", unit: 13, chapter: 50, type: "adjective" },
  { id: "u13_c50_52", native: "투표(하다)", english: "voting; ballot; poll; “throwing a ballot” (to vote)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_53", native: "판결(하다)", english: "judgment; a judicial decision (to rule; to judge)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_54", native: "피고(인)", english: "a defendant (in a civil case); the accused (in a criminal case)", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_55", native: "항소(하다)", english: "an appeal (to an intermediate appeal court) (to appeal)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_56", native: "행정", english: "administration", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_57", native: "(~)형", english: "a penalty; a punishment (for a crime)", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_58", native: "형사", english: "a criminal case", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_59", native: "후보(자)", english: "a candidate", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_60", native: "확정(하다/되다)", english: "a decision; a settlement (to decide; to settle/to be decided; to be settled)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_61", native: "지방자치", english: "local autonomy; “local self-governing”", unit: 13, chapter: 50, type: "noun" },
  { id: "u13_c50_62", native: "연임(하다/되다)", english: "serving consecutive terms; reappointment; “consecutive appointment”(to serve consecutive terms/to be reelected)", unit: 13, chapter: 50, type: "verb" },
  { id: "u13_c50_63", native: "–거든", english: "if", unit: 13, chapter: 50, type: "particle" },
];
