export const chapter20 = [
    { id: "u5_c20_01", native: "가슴", english: "chest; breast", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_02", native: "귀", english: "ear", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_03", native: "넘어지다", english: "to fall down; to trip", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_04", native: "눈", english: "eye", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_05", native: "다리", english: "leg", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_06", native: "다치다", english: "to get hurt; to be injured", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_07", native: "등", english: "back", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_08", native: "머리", english: "head; hair", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_09", native: "목", english: "neck; throat", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_10", native: "몸", english: "body", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_11", native: "무릎", english: "knee", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_12", native: "발", english: "foot", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_13", native: "발가락", english: "toe", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_14", native: "발목", english: "ankle", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_15", native: "배", english: "stomach; belly", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_16", native: "붕대(하다)", english: "bandage (to bandage)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_17", native: "생기다", english: "to happen; to occur; to be formed", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_18", native: "손", english: "hand", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_19", native: "손가락", english: "finger", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_20", native: "손목", english: "wrist", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_21", native: "아프다", english: "to be sick; to hurt", unit: 5, chapter: 20, type: "adjective" },
    { id: "u5_c20_22", native: "어깨", english: "shoulder", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_23", native: "얼굴", english: "face", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_24", native: "입", english: "mouth", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_25", native: "코", english: "nose", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_26", native: "키", english: "height; key", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_27", native: "팔", english: "arm", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_28", native: "허리", english: "waist; lower back", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_29", native: "감기", english: "cold (illness)", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_30", native: "~(에) 걸리다", english: "to catch (a cold/illness)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_31", native: "기침(하다/나다)", english: "cough (to cough)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_32", native: "낫다", english: "to get better; to recover", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_33", native: "담배", english: "cigarette; tobacco", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_34", native: "배탈(나다)", english: "stomachache (to have a stomachache)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_35", native: "복용(하다)", english: "dosage (to take medicine)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_36", native: "소화제", english: "digestive medicine", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_37", native: "설사(하다/나다)", english: "diarrhea (to have diarrhea)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_38", native: "식전", english: "before meals", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_39", native: "식후", english: "after meals", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_40", native: "알", english: "pill; tablet", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_41", native: "약사", english: "pharmacist", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_42", native: "열(나다)", english: "fever (to have a fever)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_43", native: "-자마자", english: "as soon as; right after", unit: 5, chapter: 20, type: "particle" },
    { id: "u5_c20_44", native: "증상", english: "symptom", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_45", native: "콧물(나다)", english: "runny nose (to have a runny nose)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_46", native: "토하다", english: "to vomit; to throw up", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_47", native: "피하다", english: "to avoid", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_48", native: "해열제", english: "fever reducer; antipyretic", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_49", native: "가볍다", english: "to be light; to be mild", unit: 5, chapter: 20, type: "adjective" },
    { id: "u5_c20_50", native: "구급차/앰불런스", english: "ambulance", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_51", native: "깁스(하다)", english: "cast (to put in a cast)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_52", native: "-다가", english: "while doing; and then", unit: 5, chapter: 20, type: "particle" },
    { id: "u5_c20_53", native: "다행히", english: "fortunately; luckily", unit: 5, chapter: 20, type: "adverb" },
    { id: "u5_c20_54", native: "멀어지다", english: "to get farther away", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_55", native: "목발", english: "crutch", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_56", native: "베다", english: "to cut; to slice", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_57", native: "부딪치다/부딪히다", english: "to bump into; to collide", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_58", native: "부러지다", english: "to break (bone)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_59", native: "붓다", english: "to swell", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_60", native: "-(으)ㄹ 뿐하다", english: "only; just", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_61", native: "뼈", english: "bone", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_62", native: "뼈다", english: "to break a bone", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_63", native: "상처(나다/입다)", english: "wound; injury (to get hurt)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_64", native: "심하다", english: "to be severe; to be serious", unit: 5, chapter: 20, type: "adjective" },
    { id: "u5_c20_65", native: "엑스레이(찍다)", english: "X-ray (to take an X-ray)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_66", native: "외출(하다)", english: "outing; going out (to go out)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_67", native: "응급실", english: "emergency room", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_68", native: "잠", english: "sleep", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_69", native: "진통제", english: "painkiller", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_70", native: "처방(하다)", english: "prescription (to prescribe)", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_71", native: "칼", english: "knife", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_72", native: "통증", english: "pain", unit: 5, chapter: 20, type: "noun" },
    { id: "u5_c20_73", native: "폐다", english: "to break; to fracture", unit: 5, chapter: 20, type: "verb" },
    { id: "u5_c20_74", native: "피(나다)", english: "blood (to bleed)", unit: 5, chapter: 20, type: "verb" },
];
