export const chapter38 = [
  { id: "u10_c38_01", native: "가뭄", english: "a drought", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_02", native: "건조(하다)", english: "dryness; aridity (to be dry/arid)", unit: 10, chapter: 38, type: "adjective" },
  { id: "u10_c38_03", native: "겪다", english: "to undergo; to go through; to experience", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_04", native: "그치다", english: "to stop; to cease (rain/snow)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_05", native: "구호(물)품", english: "relief items/supplies", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_06", native: "단체", english: "a group; a party; an organization", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_07", native: "대피(하다)", english: "evacuation (to evacuate)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_08", native: "도움", english: "help; assistance; “helping”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_09", native: "매몰(되다)", english: "burying (under a building) (to be buried under)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_10", native: "모금(하다)", english: "fundraising; “collecting money” (to fundraise)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_11", native: "무너지다", english: "to collapse", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_12", native: "(무)더위", english: "a (sweltering) heat spell; mugginess", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_13", native: "묻히다", english: "to be buried", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_14", native: "비누", english: "soap", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_15", native: "생존자", english: "a survivor", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_16", native: "생필품", english: "a daily necessity; “items necessary for life”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_17", native: "성금", english: "a donation; a contribution; “sincere money”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_18", native: "수색(하다)", english: "search (to search)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_19", native: "수재민", english: "flood victims; “water disaster people”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_20", native: "숨다", english: "to hide", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_21", native: "습도", english: "humidity", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_22", native: "(something) to pour", english: "(something) to pour", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_23", native: "쓰나미", english: "a tsunami; a tidal wave caused by an earthquake", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_24", native: "실내", english: "indoor; inside the room/building; “inside of the room”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_25", native: "실외", english: "outdoors; outside the room/building; “outside of the room”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_26", native: "실종(되다)", english: "missing; getting lost; “lost trace” (to disappear; to be missed)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_27", native: "얼다", english: "to freeze; to be frozen", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_28", native: "얼음", english: "ice; “freezing”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_29", native: "이상기후", english: "abnormal climate (changes)", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_30", native: "이재민", english: "a victim of natural disaster", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_31", native: "일기예보", english: "a weather forecast", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_32", native: "작업(하다)", english: "work; operations (to work; to operate)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_33", native: "잠기다", english: "to be submerged; to go underwater", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_34", native: "장마", english: "a rainy season; monsoon season", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_35", native: "재해", english: "a disaster; “disaster and damage”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_36", native: "전국적", english: "national; nationwide", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_37", native: "정전", english: "a power outage; a blackout; “stopped electricity”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_38", native: "집중(하다/되다)", english: "concentration; (to concentrate/to be concentrated)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_39", native: "천둥(치다)", english: "thunder (to thunder)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_40", native: "~철", english: "a ~ season", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_41", native: "침수(되다)", english: "submersing; “water invasion” (to be immersed; to go underwater)", unit: 10, chapter: 38, type: "verb" },
  { id: "u10_c38_42", native: "칫솔", english: "a toothbrush", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_43", native: "태풍", english: "a typhoon; “colossal wind”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_44", native: "폭설", english: "a heavy snowfall; a snowstorm; a blizzard; “violent snow”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_45", native: "폭우", english: "a heavy rainfall; torrential rain;“violent rain”", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_46", native: "호우", english: "a heavy rain; a torrential rain", unit: 10, chapter: 38, type: "noun" },
  { id: "u10_c38_47", native: "해일", english: "a tidal (storm) wave", unit: 10, chapter: 38, type: "noun" },
];
