export const chapter41 = [
  { id: "u11_c41_01", native: "가옥", english: "a house; “family house”", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_02", native: "고춧가루", english: "red pepper powder", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_03", native: "공예(품)", english: "craft(work)", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_04", native: "그릇", english: "a bowl; a container; a dish; a plate", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_05", native: "그림", english: "a picture; a drawing; a painting", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_06", native: "기와", english: "roof tiles used for a traditional Korean house", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_07", native: "기혼", english: "married; “already married”", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_08", native: "김장(하다)", english: "making kimchi for the winter (to make kimchi for the winter)", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_09", native: "내의/속옷", english: "underwear; underclothes; “inside clothes”", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_10", native: "담그다", english: "to make (kimchi); to pickle (vegetables, fish); “to soak”", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_11", native: "대문", english: "a front gate; a main gate; a main entrance; “big door”", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_12", native: "대접(하다/받다)", english: "treatment; reception (to treat/to be treated)", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_13", native: "민속", english: "folk; traditional", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_14", native: "볶다", english: "to stir-fry", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_15", native: "분홍색", english: "pink (color)", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_16", native: "붓다", english: "to pour", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_17", native: "섞다/섞이다", english: "to mix; to blend/to be mixed; to be blended", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_18", native: "세면도구", english: "toiletries; “face-washing tool”", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_19", native: "숙소", english: "a lodging; an accommodation", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_20", native: "스타일", english: "a style", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_21", native: "위치(하다)", english: "a position; a location; a site (to be located; to be situated)", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_22", native: "~을/를 포함해(서)", english: "including", unit: 11, chapter: 41, type: "particle" },
  { id: "u11_c41_23", native: "이/히/리", english: "causative infixes that turn a verb into a transitive verb", unit: 11, chapter: 41, type: "particle" },
  { id: "u11_c41_24", native: "이불", english: "a quilt; bedding", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_25", native: "익다/익히다", english: "to ripen; to mature; to age/to mature (food); to age (food)", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_26", native: "절다/절이다", english: "to be salted; to be seasoned; to be soaked/to preserve; to salt; to pickle", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_27", native: "종이", english: "paper", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_28", native: "찌다", english: "to steam", unit: 11, chapter: 41, type: "verb" },
  { id: "u11_c41_29", native: "~ 채", english: "counter for a building", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_30", native: "캐주얼(하다)", english: "casual clothes (to be casual [in attire])", unit: 11, chapter: 41, type: "adjective" },
  { id: "u11_c41_31", native: "편안하다", english: "to be comfortable; to be peaceful", unit: 11, chapter: 41, type: "adjective" },
  { id: "u11_c41_32", native: "평상시", english: "(at) ordinary times; (at) usual times", unit: 11, chapter: 41, type: "noun" },
  { id: "u11_c41_33", native: "푹", english: "thoroughly; entirely", unit: 11, chapter: 41, type: "adverb" },
  { id: "u11_c41_34", native: "화려하다", english: "to be colorful; to be fancy; to be splendid", unit: 11, chapter: 41, type: "adjective" },
  { id: "u11_c41_35", native: "희다/하얗다", english: "to be white", unit: 11, chapter: 41, type: "adjective" },
  { id: "u11_c41_36", native: "~와/과/하고 달리", english: "unlike", unit: 11, chapter: 41, type: "particle" },
  { id: "u11_c41_37", native: "~ 중에서/가운데서", english: "among; of", unit: 11, chapter: 41, type: "particle" },
];
