export const chapter46 = [
  { id: "u12_c46_01", native: "가드레일", english: "a guardrail", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_02", native: "가라앉다", english: "to sink", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_03", native: "감별(하다/되다)", english: "discerning; distinguishing (to discern; to distinguish/to be discerned)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_04", native: "경위", english: "details; particulars", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_05", native: "공장", english: "a factory; a plant; “manufacturing place”", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_06", native: "고발(하다/당하다)", english: "accusation; a charge; a report (to the authorities) (to accuse; to report/to be accused; to be reported)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_07", native: "구분/구별(하다/되다)", english: "distinguishing; sorting (to distinguish/to be distinguished)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_08", native: "긴급(하다)", english: "urgent (to be urgent)", unit: 12, chapter: 46, type: "adjective" },
  { id: "u12_c46_09", native: "뒤집히다", english: "to be turned over; to be capsized; to be reversed", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_10", native: "면하다", english: "to avoid; to escape", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_11", native: "~ 모", english: "a certain (person, object, etc.); so-and-so", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_12", native: "밀반입(하다/되다)", english: "smuggling; “secretly bringing in” (to smuggle/to be smuggled)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_13", native: "밀수(하다/되다)", english: "smuggling; “secretly transporting” (to smuggle/to be smuggled)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_14", native: "발견(하다/되다)", english: "discovery; detection (to discover/to be discovered)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_15", native: "변", english: "a mishap; a misfortune", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_16", native: "별다르다", english: "to be particular; to be special; “to be specially different”", unit: 12, chapter: 46, type: "adjective" },
  { id: "u12_c46_17", native: "보트", english: "a boat", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_18", native: "불을 지르다", english: "to set a fire willfully; to carry out arson", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_19", native: "붕괴(하다;되다)", english: "collapse (of a structure); a breakdown (to collapse)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_20", native: "비밀", english: "secret; secrecy; privacy", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_21", native: "사인", english: "a cause of death", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_22", native: "선로", english: "a railroad track; “line road”", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_23", native: "선박", english: "a (commercial) vessel; a (commercial) ship", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_24", native: "선원", english: "the crew; a crewman; a seaman; “ship member”", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_25", native: "선장", english: "a ship’s captain; a shipmaster; “ship chief”", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_26", native: "설치(하다/되다)", english: "installation (to install/to be installed)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_27", native: "악용(하다/되다)", english: "misuse; “evil use” (to misuse/to be misused)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_28", native: "압수(하다/되다)", english: "confiscation (to confiscate/to be confiscated)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_29", native: "어선", english: "a fishing boat", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_30", native: "인쇄(하다/되다)", english: "printing; presswork (to print/to be printed)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_31", native: "인양(하다/되다)", english: "bringing (a ship, dead body, etc.) up to the surface; recovering (of a ship) (to bring something up to the surface/to be brought up to the surface)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_32", native: "이송(하다/되다)", english: "transfer (of a criminal, patient, legal case, etc.) (to transfer/to be transferred)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_33", native: "이탈(하다)", english: "breakaway; desertion (to break away; to desert)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_34", native: "익사(하다)", english: "drowning; “drowning death” (to be drowned to death)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_35", native: "–아/어 있다", english: "to be in the state of ~", unit: 12, chapter: 46, type: "particle" },
  { id: "u12_c46_36", native: "(으)ㄴ 채 (로)", english: "in the state of having done (something)", unit: 12, chapter: 46, type: "particle" },
  { id: "u12_c46_37", native: "~을/를 토대로", english: "on the basis of; based upon", unit: 12, chapter: 46, type: "particle" },
  { id: "u12_c46_38", native: "출항(하다)", english: "departure from a port; “leaving the port” (to depart from a port)", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_39", native: "휩쓸리다", english: "to be swept away; to be carried away; to be swayed by", unit: 12, chapter: 46, type: "verb" },
  { id: "u12_c46_40", native: "~ 척", english: "a counter for ships or boats", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_41", native: "화", english: "a mishap; misfortune; “disaster”", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_42", native: "해(양)경(찰)", english: "coast guard; “ocean police”", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_43", native: "해양", english: "the ocean; the sea; maritime", unit: 12, chapter: 46, type: "noun" },
  { id: "u12_c46_44", native: "해역", english: "an area or section of sea", unit: 12, chapter: 46, type: "noun" },
];
