export const chapter12 = [
    { id: "u3_c12_01", native: "-게", english: "adverbial ending", unit: 3, chapter: 12, type: "particle" },
    { id: "u3_c12_02", native: "귀걸이", english: "earring", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_03", native: "깎다", english: "to cut; to discount", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_04", native: "목걸이", english: "necklace", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_05", native: "반지", english: "ring", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_06", native: "벨트", english: "belt", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_07", native: "부치다", english: "to send (by mail); to post", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_08", native: "~ 불", english: "~ dollar (US currency)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_09", native: "센트", english: "cent", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_10", native: "소포", english: "package; parcel", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_11", native: "엽서", english: "postcard", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_12", native: "우표", english: "stamp", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_13", native: "원래", english: "originally; by nature", unit: 3, chapter: 12, type: "adverb" },
    { id: "u3_c12_14", native: "~ 장", english: "~ (flat objects counter)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_15", native: "점원", english: "clerk; salesperson", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_16", native: "주인", english: "owner; proprietor", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_17", native: "지갑", english: "wallet; purse", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_18", native: "친절하다", english: "to be kind; to be friendly", unit: 3, chapter: 12, type: "adjective" },
    { id: "u3_c12_19", native: "팔찌", english: "bracelet", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_20", native: "편지", english: "letter", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_21", native: "포장(하다)", english: "packaging (to wrap; to pack)", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_22", native: "핸드백", english: "handbag", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_23", native: "고르다", english: "to choose; to select", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_24", native: "구두", english: "dress shoes; leather shoes", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_25", native: "그림(요)", english: "picture; painting", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_26", native: "끼다", english: "to wear (glasses, ring, etc.); to put on", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_27", native: "넥타이", english: "necktie", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_28", native: "맏다", english: "to wear (hat, shoes, etc. - older form)", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_29", native: "매다", english: "to tie; to wear (tie, belt)", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_30", native: "모자", english: "hat; cap", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_31", native: "뮈", english: "what (casual)", unit: 3, chapter: 12, type: "pronoun" },
    { id: "u3_c12_32", native: "바지", english: "pants; trousers", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_33", native: "보여주다", english: "to show", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_34", native: "블라우스", english: "blouse", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_35", native: "사이즈", english: "size", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_36", native: "선글라스", english: "sunglasses", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_37", native: "스웨터", english: "sweater", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_38", native: "스카프", english: "scarf", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_39", native: "스커트", english: "skirt", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_40", native: "스타킹", english: "stockings; pantyhose", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_41", native: "시계", english: "watch; clock", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_42", native: "신다", english: "to wear (shoes, socks)", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_43", native: "신발", english: "shoes", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_44", native: "쓰다", english: "to write; to use; to wear (hat)", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_45", native: "-아/어도 되다", english: "may; it's okay to", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_46", native: "안경", english: "glasses", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_47", native: "양말", english: "socks", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_48", native: "양복", english: "suit (men's)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_49", native: "와이셔츠", english: "dress shirt; button-down shirt", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_50", native: "운동화", english: "sneakers; athletic shoes", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_51", native: "원피스", english: "one-piece dress", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_52", native: "-(으)면 안되다", english: "must not; shouldn't", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_53", native: "인기", english: "popularity", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_54", native: "잠바", english: "jumper; windbreaker", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_55", native: "장갑", english: "gloves", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_56", native: "재킷", english: "jacket", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_57", native: "차다", english: "to wear (watch, belt); to kick", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_58", native: "찾다", english: "to find; to look for", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_59", native: "청바지", english: "jeans", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_60", native: "치마", english: "skirt", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_61", native: "코트", english: "coat", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_62", native: "투피스", english: "two-piece suit", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_63", native: "티셔츠", english: "T-shirt", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_64", native: "회색", english: "gray (color)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_65", native: "간장", english: "soy sauce", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_66", native: "거스름돈", english: "change (money)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_67", native: "계산(하다)", english: "calculation; bill (to calculate; to pay)", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_68", native: "계산대", english: "checkout counter", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_69", native: "고기", english: "meat", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_70", native: "고추장", english: "gochujang (red pepper paste)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_71", native: "과일", english: "fruit", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_72", native: "닭", english: "chicken", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_73", native: "- 데", english: "place; spot", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_74", native: "돼지", english: "pig; pork", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_75", native: "된장", english: "doenjang (soybean paste)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_76", native: "딸기", english: "strawberry", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_77", native: "사과", english: "apple", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_78", native: "생선", english: "fish (fresh)", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_79", native: "설탕", english: "sugar", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_80", native: "소", english: "cow; beef", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_81", native: "식초", english: "vinegar", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_82", native: "식품(점)", english: "food (store); grocery", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_83", native: "싱싱하다", english: "to be fresh", unit: 3, chapter: 12, type: "adjective" },
    { id: "u3_c12_84", native: "양념", english: "seasoning; spice", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_85", native: "팔다", english: "to sell", unit: 3, chapter: 12, type: "verb" },
    { id: "u3_c12_86", native: "포도", english: "grape", unit: 3, chapter: 12, type: "noun" },
    { id: "u3_c12_87", native: "후추", english: "pepper (spice)", unit: 3, chapter: 12, type: "noun" },
];
