export const chapter2 = [
    { id: "u1_c2_01", native: "가족", english: "family", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_02", native: "남동생", english: "younger brother", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_03", native: "누나", english: "older sister (male speaker)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_04", native: "누님", english: "older sister (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_05", native: "~ 명", english: "~ people (counter)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_06", native: "~ 분", english: "~ people (honorific counter)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_07", native: "모두", english: "all", unit: 1, chapter: 2, type: "adverb" },
    { id: "u1_c2_08", native: "다", english: "all (short)", unit: 1, chapter: 2, type: "verb" },
    { id: "u1_c2_09", native: "부모", english: "parents", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_10", native: "부모님", english: "parents (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_11", native: "아버지", english: "father", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_12", native: "아빠", english: "dad (casual)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_13", native: "아버님", english: "father (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_14", native: "어머니", english: "mother", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_15", native: "엄마", english: "mom (casual)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_16", native: "어머님", english: "mother (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_17", native: "언니", english: "older sister (female speaker)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_18", native: "여동생", english: "younger sister", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_19", native: "오빠", english: "older brother (female speaker)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_20", native: "저희", english: "we / our (humble)", unit: 1, chapter: 2, type: "pronoun" },
    { id: "u1_c2_21", native: "우리", english: "we / our (casual)", unit: 1, chapter: 2, type: "pronoun" },
    { id: "u1_c2_22", native: "~하고", english: "and / with (noun connector)", unit: 1, chapter: 2, type: "particle" },
    { id: "u1_c2_23", native: "형", english: "older brother (male speaker)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_24", native: "형님", english: "older brother (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_25", native: "형제", english: "siblings / brothers", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_26", native: "결혼하다", english: "to marry / get married", unit: 1, chapter: 2, type: "verb" },
    { id: "u1_c2_27", native: "결혼했습니다", english: "got married (past polite)", unit: 1, chapter: 2, type: "verb" },
    { id: "u1_c2_28", native: "나이", english: "age", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_29", native: "연세", english: "age (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_30", native: "남편", english: "husband", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_31", native: "딸", english: "daughter", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_32", native: "따님", english: "daughter (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_33", native: "몇", english: "how many", unit: 1, chapter: 2, type: "determiner" },
    { id: "u1_c2_34", native: "무슨", english: "what kind of / which", unit: 1, chapter: 2, type: "determiner" },
    { id: "u1_c2_35", native: "부인", english: "wife (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_36", native: "아내", english: "wife (casual)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_37", native: "~살", english: "~ years old", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_38", native: "~세", english: "~ years old (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_40", native: "아들", english: "son", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_41", native: "아드님", english: "son (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_42", native: "아이", english: "child", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_43", native: "안 + verb", english: "Verb Negation", unit: 1, chapter: 2, type: "adverb" },
    { id: "u1_c2_44", native: "없다", english: "there isn't / to not have", unit: 1, chapter: 2, type: "adjective" },
    { id: "u1_c2_45", native: "안 계시다", english: "there isn't (honorific)", unit: 1, chapter: 2, type: "adjective" },
    { id: "u1_c2_46", native: "일하다", english: "to work", unit: 1, chapter: 2, type: "verb" },
    { id: "u1_c2_47", native: "있다", english: "there is / to have", unit: 1, chapter: 2, type: "adjective" },
    { id: "u1_c2_48", native: "계시다", english: "there is (honorific)", unit: 1, chapter: 2, type: "adjective" },
    { id: "u1_c2_49", native: "할머니", english: "grandmother", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_50", native: "할머님", english: "grandmother (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_51", native: "할아버지", english: "grandfather", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_52", native: "할아버님", english: "grandfather (honorific)", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_53", native: "간호사", english: "nurse", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_54", native: "경찰관", english: "police officer", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_55", native: "-고", english: "and (connector)", unit: 1, chapter: 2, type: "particle" },
    { id: "u1_c2_56", native: "공무원", english: "public servant", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_57", native: "누구", english: "who", unit: 1, chapter: 2, type: "pronoun" },
    { id: "u1_c2_58", native: "변호사", english: "lawyer", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_59", native: "병원", english: "hospital", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_60", native: "사진", english: "photo", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_61", native: "살다", english: "to live", unit: 1, chapter: 2, type: "verb" },
    { id: "u1_c2_62", native: "소방관", english: "firefighter", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_63", native: "아주", english: "very", unit: 1, chapter: 2, type: "adverb" },
    { id: "u1_c2_64", native: "어디", english: "where", unit: 1, chapter: 2, type: "pronoun" },
    { id: "u1_c2_65", native: "~에서", english: "at / in / from", unit: 1, chapter: 2, type: "particle" },
    { id: "u1_c2_66", native: "은행원", english: "bank employee", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_67", native: "의사", english: "doctor", unit: 1, chapter: 2, type: "noun" },
    { id: "u1_c2_68", native: "젊다", english: "to be young", unit: 1, chapter: 2, type: "adjective" },
    { id: "u1_c2_69", native: "주부", english: "housewife", unit: 1, chapter: 2, type: "noun" },
];
