export const chapter16 = [
    { id: "u4_c16_01", native: "가능(하다)", english: "possible (to be possible)", unit: 4, chapter: 16, type: "adjective" },
    { id: "u4_c16_02", native: "관광(하다)", english: "sightseeing; tourism (to sightsee)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_03", native: "국내선", english: "domestic flight/line", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_04", native: "날짜", english: "date", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_05", native: "렌터카/렌트카", english: "rental car", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_06", native: "변경(하다/되다)", english: "change (to change / to be changed)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_07", native: "불가능(하다)", english: "impossible", unit: 4, chapter: 16, type: "adjective" },
    { id: "u4_c16_08", native: "상품", english: "product; goods", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_09", native: "성인", english: "adult", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_10", native: "어린이", english: "child", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_11", native: "여행사", english: "travel agency", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_12", native: "연기(하다/되다)", english: "postponement; delay (to postpone / to be delayed)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_13", native: "왕복", english: "round trip", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_14", native: "지불(하다)", english: "payment (to pay)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_15", native: "취소(하다/되다)", english: "cancellation (to cancel / to be canceled)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_16", native: "편도", english: "one way", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_17", native: "포함(하다/되다)", english: "inclusion (to include / to be included)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_18", native: "현금", english: "cash", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_19", native: "환불(하다/되다)", english: "refund (to refund / to be refunded)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_20", native: "갑자기", english: "suddenly", unit: 4, chapter: 16, type: "adverb" },
    { id: "u4_c16_21", native: "개인차", english: "individual difference; personal variation", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_22", native: "고장(나다)", english: "breakdown; malfunction (to break down)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_23", native: "고치다", english: "to fix; to repair", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_24", native: "낮", english: "daytime; noon", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_25", native: "대형", english: "large size; large scale", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_26", native: "돌려주다", english: "to return (something)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_27", native: "받데리/배터리", english: "battery", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_28", native: "보험", english: "insurance", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_29", native: "서다", english: "to stop; to stand", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_30", native: "소형", english: "small size", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_31", native: "수동식", english: "manual (transmission)", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_32", native: "시동(걸다)", english: "starting (engine) (to start the engine)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_33", native: "아무 ~(이)나", english: "any ~", unit: 4, chapter: 16, type: "determiner" },
    { id: "u4_c16_34", native: "엔진", english: "engine", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_35", native: "연기(나다)", english: "smoke (to emit smoke)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_36", native: "열쇠/키", english: "key", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_37", native: "운전면허증", english: "driver's license", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_38", native: "원하다", english: "to want", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_39", native: "-(으)ㄹ 줄 모르다/알다", english: "to not know / to know how to", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_40", native: "자동식", english: "automatic (transmission)", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_41", native: "정비소", english: "repair shop; service station", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_42", native: "중형", english: "medium size", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_43", native: "평크(나다)", english: "flat tire (to get a flat tire)", unit: 4, chapter: 16, type: "verb" },
    { id: "u4_c16_44", native: "휴게소", english: "rest area; rest stop", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_45", native: "경치", english: "scenery; view", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_46", native: "경험", english: "experience", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_47", native: "-(는)군요 / -네요", english: "I see that...; it turns out that...", unit: 4, chapter: 16, type: "particle" },
    { id: "u4_c16_48", native: "~궁", english: "~ palace", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_49", native: "마지막", english: "last; final", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_50", native: "멋있다", english: "to be cool; to be stylish", unit: 4, chapter: 16, type: "adjective" },
    { id: "u4_c16_51", native: "명소", english: "famous place; attraction", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_52", native: "문화재", english: "cultural asset; heritage", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_53", native: "불교", english: "Buddhism", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_54", native: "~사", english: "~ temple", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_55", native: "세계적", english: "world-class; global", unit: 4, chapter: 16, type: "adjective" },
    { id: "u4_c16_56", native: "-(으)면서", english: "while; and (simultaneous)", unit: 4, chapter: 16, type: "particle" },
    { id: "u4_c16_57", native: "절", english: "temple; Buddhist temple", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_58", native: "짙다", english: "to be dark; to be deep (color)", unit: 4, chapter: 16, type: "adjective" },
    { id: "u4_c16_59", native: "역사", english: "history", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_60", native: "옛날", english: "old days; ancient times", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_61", native: "운천", english: "temple name (Uncheon Temple)", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_62", native: "유적지", english: "historic site; ruins", unit: 4, chapter: 16, type: "noun" },
    { id: "u4_c16_63", native: "탑", english: "pagoda; tower", unit: 4, chapter: 16, type: "noun" },
];
