export const chapter1 = [
    { id: "u1_c1_01", native: "고맙습니다", english: "Thank you (casual)", unit: 1, chapter: 1, type: "adjective" },
    { id: "u1_c1_02", native: "감사합니다", english: "Thank you (polite)", unit: 1, chapter: 1, type: "verb" },
    { id: "u1_c1_03", native: "고향", english: "a hometown", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_04", native: "공군", english: "Air Force", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_05", native: "괜찮습니다", english: "It's okay", unit: 1, chapter: 1, type: "adjective" },
    { id: "u1_c1_06", native: "네", english: "yes", unit: 1, chapter: 1, type: "interjection" },
    { id: "u1_c1_07", native: "예", english: "yes (polite)", unit: 1, chapter: 1, type: "interjection" },
    { id: "u1_c1_08", native: "만나서 반갑습니다", english: "Nice to meet you", unit: 1, chapter: 1, type: "adjective" },
    { id: "u1_c1_09", native: "미안합니다", english: "Sorry (polite)", unit: 1, chapter: 1, type: "adjective" },
    { id: "u1_c1_10", native: "죄송합니다", english: "Sorry (formal)", unit: 1, chapter: 1, type: "adjective" },
    { id: "u1_c1_11", native: "실례합니다", english: "Excuse me", unit: 1, chapter: 1, type: "verb" },
    { id: "u1_c1_12", native: "~ 씨", english: "Mr. / Ms. (name suffix)", unit: 1, chapter: 1, type: "particle" },
    { id: "u1_c1_13", native: "아니요", english: "no", unit: 1, chapter: 1, type: "interjection" },
    { id: "u1_c1_14", native: "어디", english: "where", unit: 1, chapter: 1, type: "pronoun" },
    { id: "u1_c1_15", native: "~이/가 어떻게 되십니까?", english: "What is? (honorific)", unit: 1, chapter: 1, type: "verb" },
    { id: "u1_c1_16", native: "~은/는", english: "topic marker", unit: 1, chapter: 1, type: "particle" },
    { id: "u1_c1_17", native: "~이/가", english: "subject marker", unit: 1, chapter: 1, type: "particle" },
    { id: "u1_c1_18", native: "~이다", english: "to be (declarative)", unit: 1, chapter: 1, type: "particle" },
    { id: "u1_c1_19", native: "이름", english: "a name", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_20", native: "성함", english: "a name (honorific)", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_21", native: "제", english: "my (humble)", unit: 1, chapter: 1, type: "pronoun" },
    { id: "u1_c1_22", native: "내", english: "my (casual)", unit: 1, chapter: 1, type: "pronoun" },
    { id: "u1_c1_23", native: "처음 뵙겠습니다", english: "How do you do? (formal)", unit: 1, chapter: 1, type: "verb" },
    { id: "u1_c1_24", native: "천만에요", english: "You're welcome", unit: 1, chapter: 1, type: "interjection" },
    { id: "u1_c1_25", native: "캘리포니아", english: "California", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_26", native: "계급", english: "a (military) rank", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_27", native: "군인", english: "a serviceman", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_28", native: "그리고", english: "and (then)", unit: 1, chapter: 1, type: "adverb" },
    { id: "u1_c1_29", native: "~들", english: "plural marker", unit: 1, chapter: 1, type: "particle" },
    { id: "u1_c1_30", native: "무엇", english: "what", unit: 1, chapter: 1, type: "pronoun" },
    { id: "u1_c1_31", native: "상병", english: "E-4", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_32", native: "상사", english: "E-8", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_33", native: "~ 소개하겠습니다", english: "Let me introduce", unit: 1, chapter: 1, type: "verb" },
    { id: "u1_c1_34", native: "신병", english: "E-1", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_35", native: "원사", english: "E-9", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_36", native: "육군", english: "Army", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_37", native: "이~", english: "this (prefix)", unit: 1, chapter: 1, type: "determiner" },
    { id: "u1_c1_38", native: "~이/가 아니다", english: "is not", unit: 1, chapter: 1, type: "adjective" },
    { id: "u1_c1_39", native: "이병", english: "E-2", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_40", native: "일병", english: "E-3", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_41", native: "저", english: "I (formal)", unit: 1, chapter: 1, type: "pronoun" },
    { id: "u1_c1_42", native: "나", english: "I (casual)", unit: 1, chapter: 1, type: "pronoun" },
    { id: "u1_c1_43", native: "중사", english: "E-7", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_44", native: "직업", english: "a job / occupation", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_45", native: "친구", english: "a friend", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_46", native: "하사", english: "E-6", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_47", native: "학생", english: "a student", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_48", native: "해군", english: "Navy", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_49", native: "해병대", english: "Marine Corps", unit: 1, chapter: 1, type: "noun" },
    { id: "u1_c1_50", native: "회사원", english: "a company employee", unit: 1, chapter: 1, type: "noun" },
];
