export const chapter13 = [
    { id: "u4_c13_01", native: "국제(선)", english: "international (lines)", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_02", native: "들르다", english: "to stop by", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_03", native: "들어가다", english: "to go in; to enter", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_04", native: "면세점", english: "a duty-free shop", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_05", native: "설명(하다)", english: "explanation (to explain)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_06", native: "승객", english: "a passenger", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_07", native: "승무원", english: "a crew member; a flight attendant", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_08", native: "안내(하다)", english: "guidance (to guide; to inform)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_09", native: "안전", english: "safety", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_10", native: "~에 대해서", english: "about", unit: 4, chapter: 13, type: "particle" },
    { id: "u4_c13_11", native: "여권", english: "a passport", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_12", native: "-(으)려고", english: "(in order) to", unit: 4, chapter: 13, type: "particle" },
    { id: "u4_c13_13", native: "이륙(하다)", english: "taking off (to take off)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_14", native: "좌석", english: "a seat; seating", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_15", native: "직원", english: "staff; employee", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_16", native: "짐", english: "luggage; baggage", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_17", native: "착용(하다)", english: "wearing; putting on (to wear; to put on)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_18", native: "카운터", english: "a counter", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_19", native: "탑승(하다)", english: "boarding (to board)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_20", native: "탑승구", english: "a boarding gate", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_21", native: "탑승권", english: "a boarding pass", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_22", native: "터미널", english: "a terminal", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_23", native: "~편", english: "a flight number", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_24", native: "항공사", english: "an airline (company)", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_25", native: "기내(식)", english: "in-flight (meal)", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_26", native: "기간", english: "duration; period", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_27", native: "내다", english: "to submit; to turn in", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_28", native: "담요", english: "a blanket", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_29", native: "~ 등", english: "and so forth; etc.", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_30", native: "면세품", english: "a duty-free item", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_31", native: "목적", english: "purpose", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_32", native: "물어보다/묻다", english: "to ask", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_33", native: "비자", english: "a visa", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_34", native: "빨리", english: "quickly; fast", unit: 4, chapter: 13, type: "adverb" },
    { id: "u4_c13_35", native: "세관", english: "customs; customs house", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_36", native: "신고(하다)", english: "report; declaration (to report; to declare)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_37", native: "신고서", english: "a declaration form", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_38", native: "아무", english: "any", unit: 4, chapter: 13, type: "determiner" },
    { id: "u4_c13_39", native: "연착(하다/되다)", english: "late arrival; delay in arrival (to be delayed; to be late)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_40", native: "~(이)나", english: "or as noun connector", unit: 4, chapter: 13, type: "particle" },
    { id: "u4_c13_41", native: "입국(하다)", english: "entry into a country (to enter a country)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_42", native: "~ 중(에/에서)", english: "among; between", unit: 4, chapter: 13, type: "particle" },
    { id: "u4_c13_43", native: "착륙(하다)", english: "landing (to land)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_44", native: "출국(하다)", english: "departure from the country (to depart from the country)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_45", native: "출입국", english: "the leaving and entering of a country", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_46", native: "통과(하다)", english: "passing through (to pass through)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_47", native: "가방", english: "a bag", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_48", native: "네모나다", english: "to be rectangular", unit: 4, chapter: 13, type: "adjective" },
    { id: "u4_c13_49", native: "녹색", english: "green (color)", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_50", native: "동그랗다", english: "to be round", unit: 4, chapter: 13, type: "adjective" },
    { id: "u4_c13_51", native: "두고 내리다", english: "to leave ~ behind", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_52", native: "모양", english: "a shape", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_53", native: "바꾸다", english: "to exchange", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_54", native: "배낭", english: "a backpack", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_55", native: "보라색", english: "purple (color)", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_56", native: "세모나다", english: "to be triangular", unit: 4, chapter: 13, type: "adjective" },
    { id: "u4_c13_57", native: "센터", english: "a center", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_58", native: "-(으)려면", english: "if [you] intend to", unit: 4, chapter: 13, type: "particle" },
    { id: "u4_c13_59", native: "잃어버리다", english: "to lose", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_60", native: "주황색", english: "orange (color)", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_61", native: "지하", english: "underground; basement", unit: 4, chapter: 13, type: "noun" },
    { id: "u4_c13_62", native: "확인(하다)", english: "confirmation (to confirm)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_63", native: "환전(하다)", english: "currency exchange (to exchange money)", unit: 4, chapter: 13, type: "verb" },
    { id: "u4_c13_64", native: "환전소", english: "currency exchange office", unit: 4, chapter: 13, type: "noun" },
];
