export const chapter55 = [
  { id: "u14_c55_01", native: "가요", english: "a Korean pop song", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_02", native: "강연(하다)", english: "a lecture; an address; a discourse (to give a lecture)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_03", native: "강좌", english: "a course (of lectures); lectureship; “a (professor’s) chair”", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_04", native: "거세다", english: "to be fierce; to be tough; to be violent", unit: 14, chapter: 55, type: "adjective" },
  { id: "u14_c55_05", native: "게재(하다/되다)", english: "publication; insertion; printing (to publish/to be published)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_06", native: "경호(하다)", english: "guard (to guard)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_07", native: "관례", english: "custom; convention", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_08", native: "교과서", english: "a textbook", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_09", native: "(국)왕", english: "a king", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_10", native: "국영", english: "state-run; operated by the government", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_11", native: "극적", english: "dramatic", unit: 14, chapter: 55, type: "adjective" },
  { id: "u14_c55_12", native: "금의환향", english: "returning home in glory; “returning home in clothes of silk brocade”", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_13", native: "독학(하다)", english: "self-education; self-learning; “solo learning” (to teach oneself)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_14", native: "면담(하다)", english: "(face-to-face) talk (to have a talk)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_15", native: "문화원", english: "a cultural center", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_16", native: "발효(시키다/되다)", english: "fermentation (to ferment/to be fermented", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_17", native: "방송사", english: "a (TV/radio) broadcasting company", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_18", native: "방영(하다/되다)", english: "televising (to televise/to be televised)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_19", native: "배포(하다/되다)", english: "wide distribution (of newspapers or books) (to distribute/to be distributed widely)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_20", native: "반응(하다)", english: "reaction (to react)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_21", native: "붐", english: "boom", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_22", native: "사무총장", english: "a secretary-general", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_23", native: "수상(하다)", english: "being awarded (to be awarded)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_24", native: "시청", english: "(TV) viewing", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_25", native: "시청자", english: "a (TV) viewer", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_26", native: "싣다/실리다", english: "to carry (a story)/to be carried", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_27", native: "실감(하다/나다)", english: "realistic feeling; authentic feeling; hitting home (to feel real; to realize/to be realistic)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_28", native: "액수", english: "a sum; an amount (of money)", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_29", native: "얻다", english: "to gain; to obtain; to get", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_30", native: "영광", english: "honor; glory", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_31", native: "영접(하다)", english: "reception; greeting (a guest or VIP) (to greet a VIP; to welcome a guest)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_32", native: "원수", english: "the head of state", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_33", native: "요청(하다)", english: "request; demand (to request; to demand)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_34", native: "우수(하다)", english: "superiority; excellence (to be superior; to be excellent)", unit: 14, chapter: 55, type: "adjective" },
  { id: "u14_c55_35", native: "유산", english: "an inheritance; a legacy; a heritage", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_36", native: "의전", english: "ceremony; formality; etiquette practiced on diplomatic occasions", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_37", native: "인권", english: "human rights", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_38", native: "음반", english: "a music disc; a record", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_39", native: "전개(하다/되다)", english: "unfolding; development (to unfold)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_40", native: "전래동화", english: "a folktale; “a handed-down story for children”", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_41", native: "접근(하다)", english: "approach (to approach)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_42", native: "정서", english: "emotion; feeling; sentiment", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_43", native: "제작(하다/되다)", english: "making; production (to make; to produce/to be made; to be produced)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_44", native: "~족", english: "a race; a tribe; a group", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_45", native: "지도자", english: "a leader", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_46", native: "증진(시키다/하다/되다)", english: "enhancement; improvement (to enhance/to be enhanced)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_47", native: "채택(하다/되다)", english: "a selection (to select/to be selected)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_48", native: "체류(하다)", english: "stay (to stay)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_49", native: "추가(하다/되다)", english: "adding; additional (to add/to be added", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_50", native: "출판(하다/되다)", english: "publishing (to publish/to be published)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_51", native: "친지", english: "close friend", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_52", native: "토착어", english: "a native language; an indigenous language", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_53", native: "~ 편", english: "a counter for a movie, novel, poem, etc.", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_54", native: "편찬(하다/되다)", english: "compilation (to compile/to be compiled)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_55", native: "표기(하다/되다)", english: "inscription; transcription (to inscribe/to be inscribed)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_56", native: "풍부(하다)", english: "abundance (to be abundant)", unit: 14, chapter: 55, type: "adjective" },
  { id: "u14_c55_57", native: "한류", english: "Korean Wave; Korean Fever", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_58", native: "화해(하다)", english: "reconciliation (to reconcile)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_59", native: "환대(하다)", english: "hospitality (to give a warm welcome)", unit: 14, chapter: 55, type: "verb" },
  { id: "u14_c55_60", native: "호평", english: "a favorable comment; “good evaluation”", unit: 14, chapter: 55, type: "noun" },
  { id: "u14_c55_61", native: "훌륭하다", english: "to be excellent; to be superb", unit: 14, chapter: 55, type: "adjective" },
];
