export const chapter31 = [
  { id: "u8_c31_01", native: "과식(하다)", english: "overeating; “excessive eating” (to overeat)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_02", native: "과음(하다)", english: "excessive drinking; heavy drinking (to drink too much)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_03", native: "과체중", english: "overweight; “excessive body weight”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_04", native: "괴롭다", english: "to be (mentally) painful; to be agonizing; to be distressing", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_05", native: "규칙(적)", english: "a regulation; a rule (regular)", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_06", native: "그래도", english: "still; yet; nevertheless; however", unit: 8, chapter: 31, type: "adverb" },
  { id: "u8_c31_07", native: "눈물([이]나다)", english: "tears (to break into tears)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_08", native: "끓다/끓이다", english: "to boil (liquid)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_09", native: "날카롭다", english: "to be sharp; to be pointed; to be keen", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_10", native: "긍정적(이다)", english: "affirmative; positive (to be affirmative; to be positive)", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_11", native: "긴장(하다/되다)", english: "tension; strain; nervousness (to be tense; to be nervous)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_12", native: "만성", english: "chronic", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_13", native: "당뇨병", english: "diabetes; “sugar urine disease”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_14", native: "부정적(이다)", english: "negative (to be negative)", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_15", native: "불면증", english: "insomnia; sleeplessness; “no sleeping symptom”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_16", native: "불안(하다)", english: "uneasiness; anxiety; worry; fear (to be uneasy; to be nervous; to be unstable)", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_17", native: "비만", english: "obesity", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_18", native: "뿐(만) 아니라", english: "not only", unit: 8, chapter: 31, type: "particle" },
  { id: "u8_c31_19", native: "삼키다", english: "to swallow", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_20", native: "상담(하다)", english: "a consultation; a talk; “each other talk” (to consult)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_21", native: "상하다", english: "to go bad (food); to be spoiled; to be bruised; to be hurt", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_22", native: "상태", english: "a condition; a state; a situation", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_23", native: "성인병", english: "a geriatric disease; “adult disease”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_24", native: "식중독", english: "food poisoning; “poison in food”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_25", native: "식생활", english: "diet; “dietary life”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_26", native: "식습관", english: "eating habits; dietary habits", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_27", native: "신경([을] 쓰다)", english: "nerves (to care; to be concerned; “use a nerve”)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_28", native: "아토피", english: "atopy (a type of skin allergy)", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_29", native: "암", english: "cancer; tumor", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_30", native: "–았(었)던/–었(었)던", english: "past attributive form", unit: 8, chapter: 31, type: "particle" },
  { id: "u8_c31_31", native: "~염", english: "-itis (e.g., dermatitis and hepatitis); inflammation", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_32", native: "염증", english: "inflammation; “flame symptom”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_33", native: "예민(하다)", english: "sharpness; keenness; sensitiveness (to be sharp; to be keen; to be sensitive)", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_34", native: "예방(하다)", english: "prevention (to prevent; to take precautions)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_35", native: "위", english: "the stomach", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_36", native: "유전(되다)", english: "heredity; (genetic) inheritance (to be inherited)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_37", native: "육류", english: "meat; flesh; “flesh type”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_38", native: "–(으)니까, –아/어 보니까", english: "conjunctive ending that leads to the discovery of a fact", unit: 8, chapter: 31, type: "particle" },
  { id: "u8_c31_39", native: "의욕", english: "will; desire; volition", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_40", native: "익다/익히다", english: "to be well cooked; to be ripe/to boil; to cook", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_41", native: "(질)병/질환", english: "a disease; a sickness; a malady; a disorder", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_42", native: "짜증([이] 나다/[을] 내다)", english: "irritation; annoyance (to be irritated; to be annoyed/to act irritated)", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_43", native: "피로(하다)", english: "fatigue; exhaustion; “tiredness from (physical) labor” (to be tired)", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_44", native: "피부", english: "skin", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_45", native: "현대", english: "modern times; “modern generation”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_46", native: "호흡기", english: "the respiratory organs; “breathing vessel”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_47", native: "우울(하다)", english: "gloom; feeling low (to be gloomy; to feel low)", unit: 8, chapter: 31, type: "adjective" },
  { id: "u8_c31_48", native: "우울증", english: "depression; melancholia; hypochondria; “melancholy symptom”", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_49", native: "힘", english: "strength; force; energy", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_50", native: "풀다", english: "to resolve; to solve; to untie; to loosen", unit: 8, chapter: 31, type: "verb" },
  { id: "u8_c31_51", native: "지방", english: "fat", unit: 8, chapter: 31, type: "noun" },
  { id: "u8_c31_52", native: "황사", english: "yellow sand", unit: 8, chapter: 31, type: "noun" },
];
