export const chapter43 = [
  { id: "u11_c43_01", native: "가사", english: "household affairs; housework", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_02", native: "개신교", english: "Protestantism; “newly reformed church”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_03", native: "검사", english: "a prosecutor", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_04", native: "격주", english: "every other week; biweekly", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_05", native: "고아원", english: "an orphanage; “lone child place”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_06", native: "–곤 하다", english: "auxiliary verb that expresses common or routine occurrences of an action/event", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_07", native: "과거", english: "the past", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_08", native: "교육원", english: "an academy; an educational center", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_09", native: "교회", english: "a (Christian) church; a chapel", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_10", native: "기독교", english: "Christianity", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_11", native: "기도(하다/드리다)", english: "a prayer (to pray)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_12", native: "기부(하다)", english: "donation (of money or items) (to donate)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_13", native: "기타", english: "and others; etc.", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_14", native: "노동", english: "labor; work", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_15", native: "남", english: "another (person); other people", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_16", native: "대륙", english: "a continent; “big land”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_17", native: "대만", english: "Taiwan", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_18", native: "대하다", english: "to treat (a person)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_19", native: "도전(하다)", english: "a challenge (to challenge)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_20", native: "~ (도)중에/(–는/던) (도)중에", english: "in the middle of doing something", unit: 11, chapter: 43, type: "particle" },
  { id: "u11_c43_21", native: "문법", english: "grammar; “letter rule”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_22", native: "믿다", english: "to believe; to trust; to believe in", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_23", native: "바람직하다", english: "to be desirable; to be advisable", unit: 11, chapter: 43, type: "adjective" },
  { id: "u11_c43_24", native: "반면(에)/–(으)ㄴ/는 반면(에)", english: "on the other hand; whereas", unit: 11, chapter: 43, type: "particle" },
  { id: "u11_c43_25", native: "발전(하다/되다)", english: "development; expansion; extension; growth (to develop/to be developed)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_26", native: "복지", english: "welfare", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_27", native: "서투르다/서툴다", english: "to be unskillful; to be clumsy", unit: 11, chapter: 43, type: "adjective" },
  { id: "u11_c43_28", native: "석가탄신일", english: "Buddha’s birthday; “Sakyamuni birthday”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_29", native: "선호(하다/되다)", english: "preference (to prefer/to be preferred)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_30", native: "성당", english: "a Catholic church; a cathedral; “holy house”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_31", native: "성탄절", english: "Christmas; “holy birth day”", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_32", native: "신자", english: "a believer", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_33", native: "어색하다", english: "to be awkward", unit: 11, chapter: 43, type: "adjective" },
  { id: "u11_c43_34", native: "언어", english: "(a) language", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_35", native: "엔지니어", english: "an engineer", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_36", native: "역할", english: "a role", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_37", native: "오해(하다/받다)", english: "misunderstanding; “misinterpretation” (to misunderstand/to be misunderstood)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_38", native: "완벽(하다)", english: "perfection (to be perfect)", unit: 11, chapter: 43, type: "adjective" },
  { id: "u11_c43_39", native: "의존(하다)", english: "reliance; dependence (to depend upon; to rely on)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_40", native: "유교", english: "Confucianism", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_41", native: "유럽/구라파", english: "Europe", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_42", native: "유창하다", english: "to be fluent; to be eloquent", unit: 11, chapter: 43, type: "adjective" },
  { id: "u11_c43_43", native: "–(으)ㄴ/는데요", english: "an informal sentence ending", unit: 11, chapter: 43, type: "particle" },
  { id: "u11_c43_44", native: "의사소통(하다/되다)", english: "communication (to communicate/to be communicated)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_45", native: "이슬람교/회교", english: "Islam", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_46", native: "증가(하다/되다)", english: "increase (to increase/to be increased)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_47", native: "지위", english: "status", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_48", native: "~직", english: "a job; a position", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_49", native: "진출(하다)", english: "advancing (to a larger place to increase one’s ability, power, or territory); “advancing out” (to advance)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_50", native: "진학(하다)", english: "advancing (to a higher level of education/institution); “advancing to school” (to advance)", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_51", native: "통하다", english: "to understand each other; “flow freely (both ways)”", unit: 11, chapter: 43, type: "verb" },
  { id: "u11_c43_52", native: "풍습", english: "manners and customs; practices", unit: 11, chapter: 43, type: "noun" },
  { id: "u11_c43_53", native: "현재", english: "the present", unit: 11, chapter: 43, type: "noun" },
];
