export const chapter33 = [
  { id: "u9_c33_01", native: "각(각)", english: "respectively; each", unit: 9, chapter: 33, type: "adverb" },
  { id: "u9_c33_02", native: "결석(하다)", english: "absence (to be absent; to skip class)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_03", native: "결심(하다)", english: "a resolution; “determination of the heart” (to be determined)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_04", native: "공립", english: "public (institution, etc.); “publicly established”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_05", native: "과목", english: "a(n) (academic) subject", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_06", native: "과외(하다/받다)", english: "extracurricular work; an extracurricular lesson; “outside work” (to do an extracurricular lesson/to receive an extracurricular lesson)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_07", native: "교내", english: "in the school; on campus; intra(collegiate/school) “school inside”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_08", native: "~교시", english: "a period (of a class); an hour (of a class)", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_09", native: "교장", english: "a principal; “school chief”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_10", native: "교제(하다)", english: "association; friendship; company; dating; “meeting each other” (to associate with)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_11", native: "국립", english: "national (institution, etc.); “nationally established”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_12", native: "국어", english: "(the) Korean (language); the national language", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_13", native: "급식(하다)", english: "school lunch; (provision of school) meals (to provide meals)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_14", native: "늦잠(자다)", english: "oversleeping; “late sleep” (to oversleep)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_15", native: "–느라(고)", english: "because of (doing something); due to", unit: 9, chapter: 33, type: "particle" },
  { id: "u9_c33_16", native: "도시락", english: "a lunch box", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_17", native: "동네", english: "a (small) town; neighborhood", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_18", native: "~등/등수", english: "the ~th (in rank)/ranking", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_19", native: "반대(하다)", english: "opposition; objection (to oppose; to object)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_20", native: "방과 후", english: "after class", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_21", native: "부럽다", english: "to envy; “to be envious”", unit: 9, chapter: 33, type: "adjective" },
  { id: "u9_c33_22", native: "속상하다", english: "to be upset; to feel sore; to be vexed; “the inside hurts”", unit: 9, chapter: 33, type: "adjective" },
  { id: "u9_c33_23", native: "시간표", english: "a timetable; a (class) schedule", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_24", native: "시키다", english: "to make (a person do something)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_25", native: "–도록", english: "so that; in order to; up to the point; until", unit: 9, chapter: 33, type: "particle" },
  { id: "u9_c33_26", native: "실력", english: "ability; proficiency; competence; “real power”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_27", native: "실업계", english: "(high school) track for a vocational career", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_28", native: "의무", english: "obligation; duty; responsibility", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_29", native: "이성", english: "the opposite/other gender; “different gender”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_30", native: "입시", english: "an entrance examination; acronym for 입학 시험", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_31", native: "입학(하다)", english: "entrance into school (to enter school)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_32", native: "자율학습", english: "self-study", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_33", native: "제도", english: "a system", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_34", native: "졸업(하다)", english: "graduation (to graduate)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_35", native: "중간", english: "the middle; center; medium; interim", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_36", native: "지각(하다)", english: "being late; tardiness (to be late; to be tardy)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_37", native: "체육", english: "physical education", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_38", native: "초등학교", english: "an elementary school; “early grade school”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_39", native: "총장", english: "a president (of a university); “general chief”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_40", native: "칭찬(하다)", english: "praise; commendation (to praise; to commend; to compliment)", unit: 9, chapter: 33, type: "verb" },
  { id: "u9_c33_41", native: "(학)기말", english: "semester end; end of semester", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_42", native: "~학기", english: "a semester; “school period”", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_43", native: "~학년", english: "school year; grade", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_44", native: "한문", english: "Chinese writing", unit: 9, chapter: 33, type: "noun" },
  { id: "u9_c33_45", native: "합격(하다)", english: "passing an examination (to pass)", unit: 9, chapter: 33, type: "verb" },
];
