export const chapter18 = [
    { id: "u5_c18_01", native: "가구", english: "furniture", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_02", native: "가전제품", english: "home appliances; electronic products", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_03", native: "고객", english: "customer", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_04", native: "교환(하다)", english: "exchange (to exchange)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_05", native: "구매(하다)", english: "purchase (to purchase)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_06", native: "구입(하다)", english: "purchase (to buy)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_07", native: "남성", english: "men; male", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_08", native: "매장", english: "store; shop", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_09", native: "사은품", english: "free gift; promotional item", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_10", native: "상품권", english: "gift certificate; voucher", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_11", native: "생활(하다)", english: "life; living (to live)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_12", native: "숙녀복", english: "women's clothing", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_13", native: "신사복", english: "men's suit; formal wear", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_14", native: "신상품", english: "new product", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_15", native: "아동", english: "children", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_16", native: "여성", english: "women; female", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_17", native: "영수증", english: "receipt", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_18", native: "~용품", english: "~ goods; ~ supplies", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_19", native: "의류/~복", english: "clothing", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_20", native: "잡화", english: "miscellaneous goods; sundries", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_21", native: "주방", english: "kitchen", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_22", native: "화장품", english: "cosmetics", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_23", native: "가스레인지", english: "gas range; stove", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_24", native: "냉장고", english: "refrigerator", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_25", native: "다리미", english: "iron", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_26", native: "(똑)같다", english: "to be the same; to be identical", unit: 5, chapter: 18, type: "adjective" },
    { id: "u5_c18_27", native: "되다", english: "to become; to be possible", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_28", native: "(무)이자", english: "no interest; interest-free", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_29", native: "배달(하다)", english: "delivery (to deliver)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_30", native: "보증(하다)", english: "guarantee; warranty (to guarantee)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_31", native: "비슷하다", english: "to be similar", unit: 5, chapter: 18, type: "adjective" },
    { id: "u5_c18_32", native: "선풍기", english: "electric fan", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_33", native: "세탁기", english: "washing machine", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_34", native: "식기세척기", english: "dishwasher", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_35", native: "에어컨", english: "air conditioner", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_36", native: "-(으)르게요", english: "I will ~ (polite promise)", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_37", native: "일시불", english: "lump sum payment; cash payment", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_38", native: "전기밥솥", english: "electric rice cooker", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_39", native: "전자레인지", english: "microwave oven", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_40", native: "(진공)청소기", english: "vacuum cleaner", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_41", native: "품질", english: "quality", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_42", native: "할부", english: "installment payment", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_43", native: "감자", english: "potato", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_44", native: "공짜(로)", english: "free (of charge)", unit: 5, chapter: 18, type: "adverb" },
    { id: "u5_c18_45", native: "-기로 하다", english: "to decide to; to plan to", unit: 5, chapter: 18, type: "verb" },
    { id: "u5_c18_46", native: "~ 단", english: "~ unit; ~ piece", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_47", native: "당근", english: "carrot", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_48", native: "~만큼", english: "as much as ~; about ~", unit: 5, chapter: 18, type: "particle" },
    { id: "u5_c18_49", native: "박스", english: "box", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_50", native: "배", english: "pear; stomach", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_51", native: "복숭아", english: "peach", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_52", native: "봉지", english: "plastic bag; paper bag", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_53", native: "상자", english: "box; carton", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_54", native: "~ 송이", english: "~ bunch (flowers/vegetables)", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_55", native: "수박", english: "watermelon", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_56", native: "시금치", english: "spinach", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_57", native: "시장", english: "market", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_58", native: "신선하다", english: "to be fresh", unit: 5, chapter: 18, type: "adjective" },
    { id: "u5_c18_59", native: "아저씨", english: "uncle; mister (middle-aged man)", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_60", native: "아주머니/아줌마", english: "aunt; ma'am (middle-aged woman)", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_61", native: "양파", english: "onion", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_62", native: "오이", english: "cucumber", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_63", native: "옥수수", english: "corn", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_64", native: "채소/야채", english: "vegetables", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_65", native: "토마토", english: "tomato", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_66", native: "~ 통", english: "~ container; ~ can", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_67", native: "파", english: "green onion; scallion", unit: 5, chapter: 18, type: "noun" },
    { id: "u5_c18_68", native: "훨씬", english: "much; far; a lot more", unit: 5, chapter: 18, type: "adverb" },
];
