export const chapter25 = [
  { id: "u7_c25_01", native: "가정", english: "a home; a family; a household", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_02", native: "가지다/갖다", english: "to have; to possess", unit: 7, chapter: 25, type: "verb" },
  { id: "u7_c25_03", native: "급하다", english: "to be short-tempered; to be urgent", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_04", native: "날씬하다", english: "to be slim", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_05", native: "낳다", english: "to give birth", unit: 7, chapter: 25, type: "verb" },
  { id: "u7_c25_06", native: "내성적이다", english: "to be introspective; to be introverted; to be reserved", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_07", native: "늘다/늘어나다", english: "to increase", unit: 7, chapter: 25, type: "verb" },
  { id: "u7_c25_08", native: "다문화가정", english: "a multicultural family", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_09", native: "~ 대", english: "a generation", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_10", native: "대가족", english: "an extended family; a large family; “big family”", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_11", native: "뚱뚱하다", english: "to be fat; to be chubby", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_12", native: "따로", english: "separately; independently", unit: 7, chapter: 25, type: "adverb" },
  { id: "u7_c25_13", native: "마르다", english: "to be slender", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_14", native: "며느리/며느님 (↑)", english: "a daughter-in-law", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_15", native: "모녀", english: "mother and daughter", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_16", native: "모자", english: "mother and son", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_17", native: "부녀", english: "father and daughter", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_18", native: "부부", english: "husband and wife; a married couple", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_19", native: "부자", english: "father and son", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_20", native: "사위", english: "a son-in-law", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_21", native: "성격", english: "personality; character", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_22", native: "손녀", english: "a granddaughter", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_23", native: "손자", english: "a grandson", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_24", native: "시부모(님)", english: "(a woman’s) parents-in-law; parents of one’s husband", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_25", native: "시아버지/시아버님 (↑)", english: "(a woman’s) father-in-law", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_26", native: "시어머니/시어머님 (↑)", english: "(a woman’s) mother-in-law", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_27", native: "시집/시댁 (↑)", english: "a married woman’s in-laws’ home; (a woman’s) husband’s family", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_28", native: "식구", english: "a family member; “mouth to feed”", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_29", native: "약간", english: "a little; a bit", unit: 7, chapter: 25, type: "adverb" },
  { id: "u7_c25_30", native: "어른", english: "an adult; a senior person; an elder", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_31", native: "예전(에)", english: "in the old days; in olden times", unit: 7, chapter: 25, type: "adverb" },
  { id: "u7_c25_32", native: "의논(하다)", english: "consultation (to consult)", unit: 7, chapter: 25, type: "verb" },
  { id: "u7_c25_33", native: "이메일", english: "e-mail", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_34", native: "자녀", english: "sons and daughters; children", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_35", native: "적극적이다", english: "to be active; to be positive; to be aggressive", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_36", native: "전업주부", english: "a full-time homemaker", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_37", native: "~ 점", english: "a point; a point of view", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_38", native: "조부모(님)", english: "grandparents", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_39", native: "조용하다", english: "to be quiet; to be calm", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_40", native: "차남", english: "a second son", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_41", native: "차녀", english: "a second daughter", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_42", native: "착하다", english: "to be good-hearted; to be nice", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_43", native: "처가/처가댁 (↑)", english: "(a man’s) in-laws’ home; (a man’s) wife’s family", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_44", native: "핵가족", english: "a nuclear family; “nucleus/core family”", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_45", native: "흔하다", english: "to be common", unit: 7, chapter: 25, type: "adjective" },
  { id: "u7_c25_46", native: "–(으)ㅁ", english: "noun ending", unit: 7, chapter: 25, type: "particle" },
  { id: "u7_c25_47", native: "–잖아요", english: "verb ending used to remind what is obvious", unit: 7, chapter: 25, type: "particle" },
  { id: "u7_c25_48", native: "장남", english: "the oldest son; “big man”", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_49", native: "장녀", english: "the oldest daughter; “big woman”", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_50", native: "장인", english: "(a man’s) father-in-law", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_51", native: "장모(님)", english: "(a man’s) mother-in-law", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_52", native: "수/숫자", english: "a number; a figure", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_53", native: "삶", english: "living; life", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_54", native: "변화(하다/되다)", english: "change (to change/to be changed)", unit: 7, chapter: 25, type: "verb" },
  { id: "u7_c25_55", native: "변하다", english: "to change", unit: 7, chapter: 25, type: "verb" },
  { id: "u7_c25_56", native: "기자", english: "a journalist; a news reporter", unit: 7, chapter: 25, type: "noun" },
  { id: "u7_c25_57", native: "직장", english: "a workplace; a job", unit: 7, chapter: 25, type: "noun" },
];
