export const chapter52 = [
  { id: "u13_c52_01", native: "가장", english: "head of household; “family chief”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_02", native: "감축(하다/되다)", english: "reduction; downsizing (to reduce; to downsize/to be reduced; to be downsized)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_03", native: "강화(하다/되다)", english: "consolidation; reinforcement (to consolidate/to be reinforced)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_04", native: "고용(하다/되다)", english: "employment (to employ/to be employed)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_05", native: "구조조정", english: "a restructuring; “structure adjustment”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_06", native: "구직난", english: "difficulty finding a job", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_07", native: "권유(하다/받다)", english: "advice; persuasion (to give advice; to persuade/to be advised; to be persuaded)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_08", native: "급여", english: "pay; salary; wages", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_09", native: "기미", english: "freckles; liver spots", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_10", native: "기피(하다)", english: "avoidance; evasion (to avoid; to evade)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_11", native: "꼽다/꼽히다", english: "to count; to point out/to be counted; to be pointed out", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_12", native: "당부(하다)", english: "a request; a favor; a solicitation (to request; to solicit)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_13", native: "당연하다", english: "to be natural; to be reasonable", unit: 13, chapter: 52, type: "adjective" },
  { id: "u13_c52_14", native: "도입(하다/되다)", english: "an introduction; an adoption (to introduce; to adopt/to be introduced; to be adopted)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_15", native: "동향", english: "a tendency; a trend; a movement", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_16", native: "면제(하다/받다)", english: "an exemption (to exempt/to be exempted)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_17", native: "명예퇴직", english: "a voluntary resignation; “honorary retirement”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_18", native: "모병(하다)", english: "recruiting soldiers (to recruit soldiers)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_19", native: "미백", english: "whitening; “beautiful white”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_20", native: "미용", english: "beauty treatment; cosmetology", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_21", native: "병무청", english: "Military Manpower Administration", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_22", native: "병역", english: "military service", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_23", native: "보상(하다/받다)", english: "compensation (to compensate/to be compensated)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_24", native: "복부", english: "the abdomen; the belly; “stomach part”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_25", native: "복수", english: "multiple number; plural", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_26", native: "부작용", english: "side effects", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_27", native: "분석(하다/되다)", english: "an analysis (to analyze/to be analyzed)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_28", native: "분쟁", english: "a dispute", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_29", native: "불경기", english: "an (economic) recession; “no business”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_30", native: "비리", english: "corruption", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_31", native: "상체", english: "the upper part (of the body)", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_32", native: "성형(수술)(하다)", english: "plastic surgery; cosmetic surgery (to have plastic surgery)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_33", native: "소문", english: "a rumor; gossip; news", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_34", native: "속이다", english: "to deceive; to cheat", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_35", native: "실업자", english: "an unemployed person; “person who lost work”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_36", native: "실직(하다)", english: "losing a job/unemployment (to lose a job)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_37", native: "쌍꺼풀", english: "a double eyelid", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_38", native: "안보", english: "national security", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_39", native: "앞으로", english: "in the future; “forward on”", unit: 13, chapter: 52, type: "adverb" },
  { id: "u13_c52_40", native: "영업(하다)", english: "business; trade; a (business) operation (to run a business)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_41", native: "외모", english: "outward appearance (of a person); external features; the exterior", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_42", native: "원장", english: "the head of an organization whose name ends with 원 (院), as in 병원, 학원, and 연구원", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_43", native: "응답(~하다)", english: "a response (to respond)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_44", native: "의료", english: "medical treatment; medical service", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_45", native: "적발(하다/되다)", english: "disclosure (of a crime, fault, etc.); exposure (to disclose/to be disclosed)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_46", native: "점", english: "a mole; a birth mark; a spot; “point”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_47", native: "정신", english: "mental(ity); consciousness; mental (condition)", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_48", native: "조작(하다/되다)", english: "fabrication (to fabricate; to doctor/to be fabricated; to be doctored)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_49", native: "주근깨", english: "freckles; fleck", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_50", native: "주름(살)", english: "wrinkles; lines; crow’s feet; “wrinkled(flesh)”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_51", native: "증명서", english: "a certificate; “certification paper”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_52", native: "지키다", english: "to guard; to defend; to keep", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_53", native: "차례", english: "order (in sequence); a turn", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_54", native: "처벌(하다/받다)", english: "punishment (to punish/to be punished)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_55", native: "철저히", english: "thoroughly", unit: 13, chapter: 52, type: "adverb" },
  { id: "u13_c52_56", native: "추진(하다/되다)", english: "propulsion; drive (to propel; to drive/to be propelled; to be driven)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_57", native: "치아", english: "teeth", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_58", native: "침체(되다)", english: "stagnation; dullness; slackness (to become stagnant)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_59", native: "폐업(하다)", english: "discontinuance (of business); going out of business (to close a business; to go out of business)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_60", native: "하체", english: "the lower part (of the body)", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_61", native: "허위", english: "falsehood; untruth", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_62", native: "해고(하다/되다)", english: "layoff; termination (to lay off; to fire/to be laid off; to be fired)", unit: 13, chapter: 52, type: "verb" },
  { id: "u13_c52_63", native: "~ 이하", english: "~ and below", unit: 13, chapter: 52, type: "particle" },
  { id: "u13_c52_64", native: "징병(제)", english: "the military draft", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_65", native: "청년", english: "a youth; a young man; “green year”", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_66", native: "인력", english: "manpower; human resources", unit: 13, chapter: 52, type: "noun" },
  { id: "u13_c52_67", native: "–(으)ㄹ까 봐(서)", english: "for fear of; (being) afraid of", unit: 13, chapter: 52, type: "particle" },
];
