export const chapter37 = [
  { id: "u10_c37_01", native: "가스통", english: "a gas tank; a gas container", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_02", native: "경상(입다)", english: "a light injury; a minor wound (to sustain a light injury)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_03", native: "골목(길)", english: "an alley", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_04", native: "공포탄", english: "blank ammunition", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_05", native: "과속(하다)", english: "speeding; “excessive speed” (to speed)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_06", native: "다루다/취급하다", english: "to deal with; to handle", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_07", native: "다리", english: "a bridge", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_08", native: "달리다", english: "to run", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_09", native: "~대교", english: "a big bridge", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_10", native: "~ 덕분에/덕택에", english: "thanks to", unit: 10, chapter: 37, type: "particle" },
  { id: "u10_c37_11", native: "들이받다", english: "to run into; to bump into (physically); to ram", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_12", native: "마주 오다", english: "to come toward each other", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_13", native: "목격(하다/되다)", english: "(eye)witnessing; observation (to observe/to witness; to be observed)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_14", native: "몰다", english: "to drive (a vehicle)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_15", native: "무사(하다)", english: "safety; peace; “without an affair” (to be safe; to be peaceful)", unit: 10, chapter: 37, type: "adjective" },
  { id: "u10_c37_16", native: "번호", english: "a number", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_17", native: "보고(하다/되다)", english: "a report; a briefing (to report/to be reported)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_18", native: "부상(입다/당하다)", english: "a wound; an injury (to be injured; to sustain an injury)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_19", native: "부주의", english: "carelessness; negligence; “no caution”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_20", native: "불", english: "a fire; a light", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_21", native: "사병", english: "an enlisted man; a soldier; the ranks", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_22", native: "사상자", english: "casualties; “dead and injured people”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_23", native: "소방차", english: "a fire engine; a fire truck; “fire extinguishing vehicle”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_24", native: "소식", english: "news", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_25", native: "속도", english: "speed; velocity", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_26", native: "(술) 취하다", english: "to get drunk; to be intoxicated", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_27", native: "승합차", english: "a van; a wagon; a minibus “riding together vehicle”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_28", native: "실탄", english: "a loaded shell; a round shot; ammunition; a bullet; “real ammunition”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_29", native: "야간", english: "night; nighttime; “night interval”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_30", native: "~에 의하면", english: "according to", unit: 10, chapter: 37, type: "particle" },
  { id: "u10_c37_31", native: "엘피지", english: "liquefied petroleum gas; LPG", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_32", native: "오토바이", english: "a motorcycle", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_33", native: "용달차", english: "a delivery van/truck", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_34", native: "위반(하다)", english: "a violation; a breach (to violate; to break)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_35", native: "유조차", english: "an oil tanker", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_36", native: "음주", english: "(alcohol) drinking", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_37", native: "전복(되다)", english: "overthrow; overturn (to overturn/to be overturned)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_38", native: "전체", english: "the whole; the totality; “whole body”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_39", native: "접촉(하다/되다)", english: "touch; contact; connection (to touch; to make contact/to be connected)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_40", native: "정면", english: "the front side; the front; “correct face”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_41", native: "죽다/사망하다/숨지다/돌아가시다", english: "to die; to pass away", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_42", native: "즉시", english: "right away; immediately", unit: 10, chapter: 37, type: "adverb" },
  { id: "u10_c37_43", native: "차선", english: "a (traffic) lane; “car line”", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_44", native: "총기오발", english: "misfiring a weapon", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_45", native: "추돌(하다)", english: "a rear-end collision; “pursue and hit” (to collide from behind)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_46", native: "추락(하다)", english: "a fall; a drop; a crash (to fall; to drop; to crash)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_47", native: "추월(하다)", english: "passing; “pursue and pass” (to pass)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_48", native: "충돌(하다)", english: "a collision; a clash (to collide with)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_49", native: "타다", english: "(something) to burn; to blaze; to be on fire", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_50", native: "태우다", english: "to burn (something)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_51", native: "통제(하다/되다)", english: "control; regulation (to control; to regulate/to be controlled; to be regulated)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_52", native: "트럭", english: "a truck", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_53", native: "피해(입다/당하다)", english: "damage (to be damaged)", unit: 10, chapter: 37, type: "verb" },
  { id: "u10_c37_54", native: "현장", english: "the (actual) spot; the scene", unit: 10, chapter: 37, type: "noun" },
  { id: "u10_c37_55", native: "화물차", english: "a cargo truck", unit: 10, chapter: 37, type: "noun" },
];
