export const chapter30 = [
  { id: "u8_c30_01", native: "경우", english: "a case; a situation; an instance", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_02", native: "– 경우(에)", english: "in case; if; when", unit: 8, chapter: 30, type: "particle" },
  { id: "u8_c30_03", native: "구조(하다/되다)", english: "rescue (to rescue; to save/to be rescued)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_04", native: "구조대(원)", english: "a relief squad (member)", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_05", native: "교사", english: "a teacher; an instructor", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_06", native: "교차로", english: "an intersection; a cross street; a crossway; “intersecting roads”", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_07", native: "깊다", english: "to be deep", unit: 8, chapter: 30, type: "adjective" },
  { id: "u8_c30_08", native: "깨다/깨어나다", english: "to wake up", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_09", native: "눕다/눕히다", english: "to lie down/to lay (someone) down", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_10", native: "–는 바람에", english: "because; due to", unit: 8, chapter: 30, type: "particle" },
  { id: "u8_c30_11", native: "막다", english: "to close (off); to block; to obstruct", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_12", native: "만지다", english: "to touch; to feel; to handle", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_13", native: "맞다", english: "to be struck; to be hit; to be beaten", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_14", native: "벗기다", english: "to take off (clothes); to undress", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_15", native: "부위", english: "a part (of the body)", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_16", native: "빠지다", english: "to fall into; to be drowned; to be trapped in", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_17", native: "소독(하다)", english: "disinfection; sterilization; “dissolving poison” (to disinfect; to sterilize)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_18", native: "숨([을] 쉬다)", english: "a breath; breathing (to breathe)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_19", native: "싣다", english: "to load; to take (passengers) on board", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_20", native: "심각하다", english: "to be serious; to be grave", unit: 8, chapter: 30, type: "adjective" },
  { id: "u8_c30_21", native: "쓰러지다", english: "to collapse; to fall down", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_22", native: "–아/어 놓다", english: "auxiliary verb used to imply “to do something and keep it that way” or “to do something for future use”", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_23", native: "–아/어 두다", english: "auxiliary verb used to imply “to do something and keep it that way” or “to do something for future use”", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_24", native: "의식", english: "consciousness; awareness", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_25", native: "이/히/리/기/우/구/추", english: "causative infixes added to native verbs", unit: 8, chapter: 30, type: "particle" },
  { id: "u8_c30_26", native: "이마", english: "the forehead; the brow", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_27", native: "인공호흡", english: "CPR; “artificial breathing”", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_28", native: "일단", english: "first (of all); beforehand", unit: 8, chapter: 30, type: "adverb" },
  { id: "u8_c30_29", native: "젖다", english: "to get wet; to be damp", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_30", native: "조절(하다)", english: "regulation; adjustment; control; tuning (to regulate; to adjust; to control; to tune)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_31", native: "지혈(하다)", english: "arrest of bleeding (to stop bleeding)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_32", native: "처치(하다)", english: "handling; dealing with; (medical) treatment (to handle; to deal with)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_33", native: "침착(하다)", english: "composure; calmness (to be composed; to be cool)", unit: 8, chapter: 30, type: "adjective" },
  { id: "u8_c30_34", native: "큰일(나다)", english: "big trouble; “big work” (to have a big trouble)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_35", native: "찢다/찢어지다", english: "to tear; to rip/to be torn; to be ripped", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_36", native: "출동(하다)", english: "moving out; mobilization; being dispatched; “move out” (to move out; to be mobilized; to be dispatched)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_37", native: "출혈", english: "loss of blood; bleeding; “blood out”", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_38", native: "화상([을] 입다)", english: "a burn; “fire injury” (to sustain a burn)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_39", native: "위험(하다)", english: "danger; jeopardy; risk (to be dangerous; to be in danger)", unit: 8, chapter: 30, type: "adjective" },
  { id: "u8_c30_40", native: "유지(하다)", english: "maintenance; preservation; sustenance (to maintain; to preserve)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_41", native: "차갑다", english: "to be cold; to be chilly; to be icy", unit: 8, chapter: 30, type: "adjective" },
  { id: "u8_c30_42", native: "두드리다", english: "to pat; to tap; to knock", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_43", native: "두두다", english: "to put; to place", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_44", native: "바위", english: "a rock; a boulder", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_45", native: "기절(하다)", english: "faint; passing out; 'energy cut' (to faint; to pass out)", unit: 8, chapter: 30, type: "verb" },
  { id: "u8_c30_46", native: "보호자", english: "a guardian; “a protector”", unit: 8, chapter: 30, type: "noun" },
  { id: "u8_c30_47", native: "세다", english: "to be strong; to be powerful", unit: 8, chapter: 30, type: "adjective" },
  { id: "u8_c30_48", native: "호흡(하다)", english: "breath; respiration (to breathe)", unit: 8, chapter: 30, type: "verb" },
];
