export const chapter10 = [
    { id: "u3_c10_01", native: "가장", english: "the most; the best", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_02", native: "고속버스", english: "express bus; highway bus", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_03", native: "공항", english: "airport", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_04", native: "기차/열차", english: "train", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_05", native: "너무", english: "too; very; excessively", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_06", native: "느리다", english: "to be slow", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_07", native: "더", english: "more", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_08", native: "듣다", english: "to listen; to hear", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_09", native: "렌터카", english: "rental car", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_10", native: "배", english: "ship; boat; stomach", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_11", native: "버스", english: "bus", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_12", native: "~보다 (더)", english: "more than ~; compared to ~", unit: 3, chapter: 10, type: "particle" },
    { id: "u3_c10_13", native: "불편하다", english: "to be inconvenient; to be uncomfortable", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_14", native: "비싸다", english: "to be expensive", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_15", native: "비용", english: "cost; expense", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_16", native: "빌리다", english: "to borrow; to rent", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_17", native: "빠르다", english: "to be fast; to be quick", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_18", native: "싸다", english: "to be cheap; to be inexpensive", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_19", native: "역", english: "station", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_20", native: "적게", english: "less; a little", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_21", native: "적다", english: "to be few; to be little", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_22", native: "정류장", english: "bus stop; station", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_23", native: "지하철", english: "subway", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_24", native: "터미널", english: "terminal (bus/train)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_25", native: "항(구)", english: "port; harbor", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_26", native: "-기 때문에/~때문에", english: "because of; due to", unit: 3, chapter: 10, type: "particle" },
    { id: "u3_c10_27", native: "갈아타다", english: "to transfer; to change (vehicles)", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_28", native: "값/가격", english: "price; cost", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_29", native: "계속", english: "continuously; keep on", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_30", native: "고속도로", english: "highway; expressway", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_31", native: "공사 중", english: "under construction", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_32", native: "내다", english: "to pay; to submit", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_33", native: "내일", english: "tomorrow", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_34", native: "멀어지다", english: "to get farther away", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_35", native: "복잡하다", english: "to be complicated; to be crowded", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_36", native: "세우다", english: "to stop (a vehicle); to erect", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_37", native: "신호등", english: "traffic light", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_38", native: "오늘", english: "today", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_39", native: "(길을) 잃다", english: "to get lost", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_40", native: "입구", english: "entrance", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_41", native: "조심(하다)", english: "caution (to be careful)", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_42", native: "지금", english: "now", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_43", native: "출구", english: "exit", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_44", native: "편의점", english: "convenience store", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_45", native: "혹시", english: "by any chance; perhaps", unit: 3, chapter: 10, type: "adverb" },
    { id: "u3_c10_46", native: "가지고 가다", english: "to take (something) with one", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_47", native: "가지고 오다", english: "to bring (something)", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_48", native: "고모", english: "aunt (father's sister)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_49", native: "고모부", english: "uncle (husband of father's sister)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_50", native: "귀엽다", english: "to be cute", unit: 3, chapter: 10, type: "adjective" },
    { id: "u3_c10_51", native: "내년", english: "next year", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_52", native: "-는/(으)ㄴ/(으)ㄹ", english: "adjective/modifier ending", unit: 3, chapter: 10, type: "particle" },
    { id: "u3_c10_53", native: "데리고 가다/모시고 가다(↑)", english: "to take (someone) along - honorific", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_54", native: "데리고 오다/모시고 오다(↑)", english: "to bring (someone) - honorific", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_55", native: "되다", english: "to become; to be possible", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_56", native: "방문(하다)", english: "visit (to visit)", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_57", native: "사촌", english: "cousin", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_58", native: "여러 (가지)", english: "various; several kinds", unit: 3, chapter: 10, type: "determiner" },
    { id: "u3_c10_59", native: "올해/금년", english: "this year", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_60", native: "외삼촌", english: "uncle (mother's brother)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_61", native: "외할머니", english: "maternal grandmother", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_62", native: "외할아버지", english: "maternal grandfather", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_63", native: "이모", english: "aunt (mother's sister)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_64", native: "이모부", english: "uncle (husband of mother's sister)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_65", native: "작은", english: "small; little (younger)", unit: 3, chapter: 10, type: "determiner" },
    { id: "u3_c10_66", native: "작은아버지", english: "uncle (father's younger brother)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_67", native: "작은어머니", english: "aunt (wife of father's younger brother)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_68", native: "조카", english: "nephew; niece", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_69", native: "큰아버지", english: "uncle (father's older brother)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_70", native: "큰어머니", english: "aunt (wife of father's older brother)", unit: 3, chapter: 10, type: "noun" },
    { id: "u3_c10_71", native: "태어나다", english: "to be born", unit: 3, chapter: 10, type: "verb" },
    { id: "u3_c10_72", native: "형수", english: "sister-in-law (older brother's wife)", unit: 3, chapter: 10, type: "noun" },
];
