export const chapter23 = [
    { id: "u6_c23_01", native: "공휴일", english: "public holiday", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_02", native: "광복절", english: "Liberation Day (Aug 15)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_03", native: "국경일", english: "national holiday", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_04", native: "국군의 날", english: "Armed Forces Day", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_05", native: "기념(하다)", english: "commemoration (to commemorate)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_06", native: "꼭", english: "surely; certainly; without fail", unit: 6, chapter: 23, type: "adverb" },
    { id: "u6_c23_07", native: "달력", english: "calendar", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_08", native: "독립(하다)", english: "independence (to gain independence)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_09", native: "~ 말", english: "end of ~ (month)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_10", native: "부처님오신날", english: "Buddha's Birthday", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_11", native: "설(날)", english: "Lunar New Year", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_12", native: "이제", english: "now; from now on", unit: 6, chapter: 23, type: "adverb" },
    { id: "u6_c23_13", native: "중순", english: "middle of the month", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_14", native: "중요(하다)", english: "important", unit: 6, chapter: 23, type: "adjective" },
    { id: "u6_c23_15", native: "초순", english: "beginning of the month", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_16", native: "추석", english: "Chuseok (Korean Thanksgiving)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_17", native: "크리스마스", english: "Christmas", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_18", native: "한글날", english: "Hangul Day (Oct 9)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_19", native: "휴일", english: "holiday; day off", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_20", native: "귀성객", english: "person returning to hometown for holiday", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_21", native: "놀이", english: "play; game", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_22", native: "-다고/라고 (말)하다", english: "to say that...", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_23", native: "떡국", english: "rice cake soup", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_24", native: "명절", english: "holiday; festival", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_25", native: "묘", english: "tomb; grave", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_26", native: "북", english: "drum", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_27", native: "봄비다", english: "to be spring-like", unit: 6, chapter: 23, type: "adjective" },
    { id: "u6_c23_28", native: "새해", english: "new year", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_29", native: "성묘(하다/가다)", english: "visiting ancestral graves (to visit graves)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_30", native: "세배(하다)", english: "New Year's bow (to bow to elders)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_31", native: "송편", english: "songpyeon (half-moon rice cake)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_32", native: "양력", english: "solar calendar", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_33", native: "음력", english: "lunar calendar", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_34", native: "자기", english: "oneself", unit: 6, chapter: 23, type: "pronoun" },
    { id: "u6_c23_35", native: "전통", english: "tradition", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_36", native: "제일", english: "the most; the best", unit: 6, chapter: 23, type: "adverb" },
    { id: "u6_c23_37", native: "조상(님)", english: "ancestor", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_38", native: "차례 (를 지내다)", english: "ancestral memorial service (to hold a service)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_39", native: "찾아가다", english: "to visit; to go see", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_40", native: "(결)정(하다/되다)", english: "decision (to decide / to be decided)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_41", native: "꽃", english: "flower", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_42", native: "글씨", english: "handwriting; writing", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_43", native: "놀이공원", english: "amusement park", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_44", native: "달다", english: "to be sweet", unit: 6, chapter: 23, type: "adjective" },
    { id: "u6_c23_45", native: "동물원", english: "zoo", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_46", native: "생각(하다/나다)", english: "thought (to think / to come to mind)", unit: 6, chapter: 23, type: "verb" },
    { id: "u6_c23_47", native: "스승의 날", english: "Teacher's Day (May 15)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_48", native: "-왔/었었", english: "had done (past perfect)", unit: 6, chapter: 23, type: "particle" },
    { id: "u6_c23_49", native: "어린이날", english: "Children's Day (May 5)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_50", native: "어버이날", english: "Parents' Day (May 8)", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_51", native: "장난감", english: "toy", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_52", native: "-지(요)", english: "you know; isn't it? (seeking agreement)", unit: 6, chapter: 23, type: "particle" },
    { id: "u6_c23_53", native: "카드", english: "card", unit: 6, chapter: 23, type: "noun" },
    { id: "u6_c23_54", native: "효도관광", english: "filial piety tour; family trip", unit: 6, chapter: 23, type: "noun" },
];
