export const chapter9 = [
  { id: "u3_c9_01", native: "Telefon", english: "telephone / phone", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_02", native: "anrufen", english: "to call (by phone)", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_03", native: "telefonieren", english: "to talk on the phone", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_04", native: "Nummer", english: "number", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_05", native: "Telefonnummer", english: "phone number", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_06", native: "Anruf", english: "phone call", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_07", native: "Nachricht", english: "message", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_08", native: "SMS", english: "text message / SMS", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_09", native: "abnehmen", english: "to pick up / answer (the phone)", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_10", native: "auflegen", english: "to hang up", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_11", native: "sprechen", english: "to speak / talk", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_12", native: "Verbindung", english: "connection", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_13", native: "besetzt", english: "busy (line)", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_14", native: "erreichbar", english: "reachable / available", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_15", native: "zurückrufen", english: "to call back", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_16", native: "Anrufbeantworter", english: "answering machine", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_17", native: "klingeln", english: "to ring", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_18", native: "Hörer", english: "receiver / handset", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_19", native: "Leitung", english: "line (phone)", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_20", native: "stören", english: "to disturb / bother", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_21", native: "Moment", english: "moment", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_22", native: "Geburtstag", english: "birthday", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_23", native: "feiern", english: "to celebrate", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_24", native: "Feier", english: "celebration / party", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_25", native: "einladen", english: "to invite", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_26", native: "Einladung", english: "invitation", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_27", native: "Geschenk", english: "gift / present", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_28", native: "schenken", english: "to give (as a gift)", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_29", native: "gratulieren", english: "to congratulate", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_30", native: "Glückwunsch", english: "congratulation", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_31", native: "wünschen", english: "to wish", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_32", native: "Kuchen", english: "cake", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_33", native: "Torte", english: "gateau / layered cake", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_34", native: "Überraschung", english: "surprise", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_35", native: "überraschen", english: "to surprise", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_36", native: "Fest", english: "festival / celebration", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_37", native: "Ballon", english: "balloon", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_38", native: "Kerze", english: "candle", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_39", native: "herzlich", english: "heartfelt / warm (regards)", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_40", native: "Glückwünsche", english: "congratulations (plural)", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_41", native: "organisieren", english: "to organize", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_42", native: "stattfinden", english: "to take place", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_43", native: "absagen", english: "to cancel / decline", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_44", native: "zusagen", english: "to accept / confirm (invitation)", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_45", native: "freuen", english: "to be happy / look forward (sich freuen)", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_46", native: "Einladungskarte", english: "invitation card", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_47", native: "Gruß", english: "greeting", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_48", native: "Grüße", english: "regards / greetings", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_49", native: "Textnachricht", english: "text message", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_50", native: "Sprachnachricht", english: "voice message", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_51", native: "Videoanruf", english: "video call", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_52", native: "online", english: "online", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_53", native: "offline", english: "offline", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_54", native: "Signal", english: "signal", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_55", native: "Lautstärke", english: "volume", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_56", native: "laut", english: "loud", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_57", native: "leise", english: "quiet / soft", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_58", native: "stumm", english: "mute / silent", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_59", native: "weiterleiten", english: "to forward", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_60", native: "speichern", english: "to save", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_61", native: "löschen", english: "to delete", unit: 3, chapter: 9, type: "verb" },
  { id: "u3_c9_62", native: "Kontakt", english: "contact", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_63", native: "Adressbuch", english: "address book / contacts", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_64", native: "Anrufliste", english: "call log / call list", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_65", native: "verpasst", english: "missed", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_66", native: "dringend", english: "urgent", unit: 3, chapter: 9, type: "adjective" },
  { id: "u3_c9_67", native: "Freude", english: "joy / pleasure", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_68", native: "Jubiläum", english: "anniversary / jubilee", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_69", native: "Geburtstagskuchen", english: "birthday cake", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_70", native: "Geschenkkarte", english: "gift card", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_71", native: "Einladungsbrief", english: "invitation letter", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_72", native: "Antwort", english: "answer / reply", unit: 3, chapter: 9, type: "noun" },
  { id: "u3_c9_73", native: "bestätigen", english: "to confirm", unit: 3, chapter: 9, type: "verb" }
];
