export const chapter20 = [
  { id: "u5_c20_01", native: "Kopf", english: "head", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_02", native: "Gesicht", english: "face", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_03", native: "Auge", english: "eye", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_04", native: "Ohr", english: "ear", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_05", native: "Nase", english: "nose", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_06", native: "Mund", english: "mouth", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_07", native: "Lippe", english: "lip", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_08", native: "Zunge", english: "tongue", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_09", native: "Hals", english: "neck / throat", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_10", native: "Schulter", english: "shoulder", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_11", native: "Arm", english: "arm", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_12", native: "Ellbogen", english: "elbow", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_13", native: "Hand", english: "hand", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_14", native: "Finger", english: "finger", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_15", native: "Daumen", english: "thumb", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_16", native: "Brust", english: "chest", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_17", native: "Bauch", english: "belly / abdomen", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_18", native: "Rücken", english: "back", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_19", native: "Hüfte", english: "hip", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_20", native: "Bein", english: "leg", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_21", native: "Knie", english: "knee", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_22", native: "Fuß", english: "foot", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_23", native: "Zehe", english: "toe", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_24", native: "Haut", english: "skin", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_25", native: "Haar", english: "hair", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_26", native: "Knochen", english: "bone", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_27", native: "Muskel", english: "muscle", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_28", native: "Herz", english: "heart", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_29", native: "Schmerz", english: "pain", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_30", native: "Kopfschmerzen", english: "headache", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_31", native: "Bauchschmerzen", english: "stomach ache", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_32", native: "Rückenschmerzen", english: "backache", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_33", native: "Fieber", english: "fever", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_34", native: "Husten", english: "cough", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_35", native: "Schnupfen", english: "cold / runny nose", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_36", native: "Halsschmerzen", english: "sore throat", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_37", native: "Grippe", english: "flu", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_38", native: "Erkältung", english: "common cold", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_39", native: "Allergie", english: "allergy", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_40", native: "Ausschlag", english: "rash", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_41", native: "Schwindel", english: "dizziness", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_42", native: "Übelkeit", english: "nausea", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_43", native: "Erbrechen", english: "vomiting", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_44", native: "Durchfall", english: "diarrhoea", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_45", native: "Verletzung", english: "injury", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_46", native: "Wunde", english: "wound", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_47", native: "Blutung", english: "bleeding", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_48", native: "Bruch", english: "fracture", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_49", native: "Verstauchung", english: "sprain", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_50", native: "Prellung", english: "bruise", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_51", native: "Arzt", english: "doctor", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_52", native: "Ärztin", english: "female doctor", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_53", native: "Krankenhaus", english: "hospital", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_54", native: "Klinik", english: "clinic", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_55", native: "Apotheke", english: "pharmacy", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_56", native: "Notaufnahme", english: "emergency department", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_57", native: "Ambulanz", english: "ambulance / outpatients", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_58", native: "Station", english: "ward", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_59", native: "Patient", english: "patient", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_60", native: "Patientin", english: "female patient", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_61", native: "Krankenschwester", english: "nurse", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_62", native: "Krankenpfleger", english: "male nurse", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_63", native: "Untersuchung", english: "examination", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_64", native: "Diagnose", english: "diagnosis", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_65", native: "Behandlung", english: "treatment", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_66", native: "Therapie", english: "therapy", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_67", native: "Operation", english: "operation", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_68", native: "Tablette", english: "tablet", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_69", native: "Medikament", english: "medication", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_70", native: "Rezept", english: "prescription", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_71", native: "Verband", english: "bandage", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_72", native: "Pflaster", english: "plaster", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_73", native: "Spritze", english: "injection", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_74", native: "Impfung", english: "vaccination", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_75", native: "Blutdruck", english: "blood pressure", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_76", native: "Puls", english: "pulse", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_77", native: "Krankenversicherung", english: "health insurance", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_78", native: "Krankenwagen", english: "ambulance", unit: 5, chapter: 20, type: "noun" },
  { id: "u5_c20_79", native: "schmerzen", english: "to hurt", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_80", native: "untersuchen", english: "to examine", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_81", native: "behandeln", english: "to treat", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_82", native: "operieren", english: "to operate on", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_83", native: "heilen", english: "to heal", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_84", native: "verschreiben", english: "to prescribe", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_85", native: "einnehmen", english: "to take (medicine)", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_86", native: "impfen", english: "to vaccinate", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_87", native: "bluten", english: "to bleed", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_88", native: "husten", english: "to cough", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_89", native: "niesen", english: "to sneeze", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_90", native: "schwitzen", english: "to sweat", unit: 5, chapter: 20, type: "verb" },
  { id: "u5_c20_91", native: "krank", english: "ill / sick", unit: 5, chapter: 20, type: "adjective" },
  { id: "u5_c20_92", native: "gesund", english: "healthy", unit: 5, chapter: 20, type: "adjective" },
  { id: "u5_c20_93", native: "verletzt", english: "injured", unit: 5, chapter: 20, type: "adjective" },
  { id: "u5_c20_94", native: "akut", english: "acute", unit: 5, chapter: 20, type: "adjective" },
  { id: "u5_c20_95", native: "chronisch", english: "chronic", unit: 5, chapter: 20, type: "adjective" },
  { id: "u5_c20_96", native: "ansteckend", english: "contagious", unit: 5, chapter: 20, type: "adjective" },
  { id: "u5_c20_97", native: "schmerzhaft", english: "painful", unit: 5, chapter: 20, type: "adjective" },
];
