export const chapter23 = [
  { id: "u6_c23_01", native: "Weihnachten", english: "Christmas", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_02", native: "Ostern", english: "Easter", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_03", native: "Silvester", english: "New Year's Eve", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_04", native: "Karneval", english: "carnival", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_05", native: "Fasching", english: "carnival (southern)", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_06", native: "Pfingsten", english: "Pentecost", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_07", native: "Himmelfahrt", english: "Ascension Day", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_08", native: "Allerheiligen", english: "All Saints' Day", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_09", native: "Nikolaustag", english: "St. Nicholas Day", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_10", native: "Advent", english: "Advent", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_11", native: "Weihnachtsbaum", english: "Christmas tree", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_12", native: "Christbaum", english: "Christmas tree", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_13", native: "Osterei", english: "Easter egg", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_14", native: "Osterhase", english: "Easter bunny", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_15", native: "Tradition", english: "tradition", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_16", native: "Brauch", english: "custom", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_17", native: "Sitte", english: "custom / social norm", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_18", native: "Familienfeier", english: "family celebration", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_19", native: "Familienfest", english: "family gathering", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_20", native: "Hochzeit", english: "wedding", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_21", native: "Taufe", english: "baptism", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_22", native: "Konfirmation", english: "confirmation", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_23", native: "Kommunion", english: "First Communion", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_24", native: "Jubiläumsfeier", english: "anniversary celebration", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_25", native: "Geburtstagsparty", english: "birthday party", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_26", native: "Christkind", english: "Christ Child", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_27", native: "Weihnachtsmann", english: "Santa Claus", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_28", native: "Nikolaus", english: "St. Nicholas", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_29", native: "Engel", english: "angel", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_30", native: "Rentier", english: "reindeer", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_31", native: "Adventskalender", english: "Advent calendar", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_32", native: "Weihnachtsmarkt", english: "Christmas market", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_33", native: "Glühwein", english: "mulled wine", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_34", native: "Lebkuchen", english: "gingerbread", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_35", native: "Stollen", english: "Christmas stollen", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_36", native: "Feuerwerk", english: "fireworks", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_37", native: "Böller", english: "firecracker", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_38", native: "Neujahr", english: "New Year", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_39", native: "Neujahrsvorsatz", english: "New Year's resolution", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_40", native: "Braut", english: "bride", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_41", native: "Bräutigam", english: "groom", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_42", native: "Trauung", english: "wedding ceremony", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_43", native: "Hochzeitsfeier", english: "wedding reception", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_44", native: "Flitterwochen", english: "honeymoon", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_45", native: "Patenkind", english: "godchild", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_46", native: "Pate", english: "godfather", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_47", native: "Patin", english: "godmother", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_48", native: "feierlich", english: "festive / solemn", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_49", native: "traditionell", english: "traditional", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_50", native: "festlich", english: "festive", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_51", native: "religiös", english: "religious", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_52", native: "säkular", english: "secular", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_53", native: "beschenken", english: "to give gifts to", unit: 6, chapter: 23, type: "verb" },
  { id: "u6_c23_54", native: "schmücken", english: "to decorate", unit: 6, chapter: 23, type: "verb" },
  { id: "u6_c23_55", native: "backen", english: "to bake", unit: 6, chapter: 23, type: "verb" },
  { id: "u6_c23_56", native: "heiraten", english: "to marry", unit: 6, chapter: 23, type: "verb" },
  { id: "u6_c23_57", native: "trauen", english: "to marry (ceremony)", unit: 6, chapter: 23, type: "verb" },
  { id: "u6_c23_58", native: "taufen", english: "to baptize", unit: 6, chapter: 23, type: "verb" },
  { id: "u6_c23_59", native: "Weihnachtslied", english: "Christmas carol", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_60", native: "Adventskranz", english: "Advent wreath", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_61", native: "Geschenkpapier", english: "wrapping paper", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_62", native: "Überraschungsei", english: "surprise egg", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_63", native: "Maske", english: "mask", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_64", native: "Kostüm", english: "costume", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_65", native: "Rosenmontag", english: "Rose Monday", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_66", native: "Aschermittwoch", english: "Ash Wednesday", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_67", native: "Fastnacht", english: "carnival period", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_68", native: "Osterspaziergang", english: "Easter walk", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_69", native: "Familienessen", english: "family meal", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_70", native: "Tischrede", english: "toast speech", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_71", native: "Prosit", english: "cheers", unit: 6, chapter: 23, type: "interjection" },
  { id: "u6_c23_72", native: "fröhlich", english: "cheerful", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_73", native: "besinnlich", english: "contemplative", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_74", native: "gemütlich", english: "cozy", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_75", native: "weihnachtlich", english: "Christmassy", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_76", native: "österlich", english: "Easter-related", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_77", native: "karnevalistisch", english: "carnival-related", unit: 6, chapter: 23, type: "adjective" },
  { id: "u6_c23_78", native: "Brauchtum", english: "customs / folklore", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_79", native: "Festtag", english: "feast day", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_80", native: "Feiertag", english: "public holiday", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_81", native: "gesetzlicher Feiertag", english: "statutory holiday", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_82", native: "Bräuche", english: "customs", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_83", native: "Überlieferung", english: "handed-down tradition", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_84", native: "Familienritual", english: "family ritual", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_85", native: "Jubiläumsjahr", english: "anniversary year", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_86", native: "Gedenktag", english: "day of remembrance", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_87", native: "Namensfeier", english: "name day celebration", unit: 6, chapter: 23, type: "noun" },
  { id: "u6_c23_88", native: "Jubilar", english: "anniversary celebrant", unit: 6, chapter: 23, type: "noun" }
];
