export const chapter22 = [
  { id: "u6_c22_01", native: "Haushaltskasse", english: "household budget / petty cash", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_02", native: "Budget", english: "budget", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_03", native: "Ausgaben", english: "expenses", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_04", native: "Einnahmen", english: "income / revenue", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_05", native: "sparen", english: "to save (money)", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_06", native: "Sparbuch", english: "savings book", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_07", native: "Konto", english: "account", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_08", native: "Bankkonto", english: "bank account", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_09", native: "Girokonto", english: "checking account", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_10", native: "Sparkonto", english: "savings account", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_11", native: "Überweisung", english: "bank transfer", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_12", native: "Bargeld", english: "cash", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_13", native: "Kreditkarte", english: "credit card", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_14", native: "Gehalt", english: "salary", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_15", native: "Lohn", english: "wage", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_16", native: "Einkommen", english: "income", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_17", native: "Schulden", english: "debts", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_18", native: "Kredit", english: "loan / credit", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_19", native: "Zinsen", english: "interest", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_20", native: "Beleg", english: "receipt", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_21", native: "Sparschwein", english: "piggy bank", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_22", native: "Haushaltsgerät", english: "household appliance", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_23", native: "Putzmittel", english: "cleaning agent", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_24", native: "Reinigungsmittel", english: "cleaning product", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_25", native: "Wartung", english: "maintenance", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_26", native: "Reparatur", english: "repair", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_27", native: "Haushaltshilfe", english: "domestic help", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_28", native: "Putzfrau", english: "cleaning lady", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_29", native: "Hausmeister", english: "caretaker / janitor", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_30", native: "Mülltrennung", english: "waste separation", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_31", native: "Recycling", english: "recycling", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_32", native: "Energiekosten", english: "energy costs", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_33", native: "Stromrechnung", english: "electricity bill", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_34", native: "Gasrechnung", english: "gas bill", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_35", native: "Wasserrechnung", english: "water bill", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_36", native: "Internetrechnung", english: "internet bill", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_37", native: "ausgeben", english: "to spend", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_38", native: "überweisen", english: "to transfer (money)", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_39", native: "abbuchen", english: "to debit", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_40", native: "einzahlen", english: "to deposit", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_41", native: "abheben", english: "to withdraw", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_42", native: "leihen", english: "to borrow / lend", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_43", native: "schulden", english: "to owe", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_44", native: "tilgen", english: "to repay (debt)", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_45", native: "entsorgen", english: "to dispose of", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_46", native: "recyceln", english: "to recycle", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_47", native: "haushalten", english: "to manage household finances", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_48", native: "sparsam", english: "thrifty / economical", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_49", native: "verschwenderisch", english: "wasteful", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_50", native: "wirtschaftlich", english: "economical", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_51", native: "finanziell", english: "financial", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_52", native: "zahlungsfähig", english: "solvent", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_53", native: "zahlungsunfähig", english: "insolvent", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_54", native: "regelmäßig", english: "regular", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_55", native: "monatlich", english: "monthly", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_56", native: "jährlich", english: "annual", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_57", native: "Haushaltsplan", english: "household budget plan", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_58", native: "Kosten", english: "costs", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_59", native: "Ersparnis", english: "savings", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_60", native: "Rücklage", english: "reserve", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_61", native: "Notgroschen", english: "emergency fund", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_62", native: "Dauerauftrag", english: "standing order", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_63", native: "Lastschrift", english: "direct debit", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_64", native: "Kontostand", english: "account balance", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_65", native: "Dispokredit", english: "overdraft facility", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_66", native: "Zahlungserinnerung", english: "payment reminder", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_67", native: "Mahnung", english: "dunning letter", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_68", native: "Inkasso", english: "debt collection", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_69", native: "versichern", english: "to insure", unit: 6, chapter: 22, type: "verb" },
  { id: "u6_c22_70", native: "Hausratversicherung", english: "household contents insurance", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_71", native: "Haftpflichtversicherung", english: "liability insurance", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_72", native: "preiswert", english: "reasonably priced", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_73", native: "aufwendig", english: "costly / elaborate", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_74", native: "umsichtig", english: "prudent", unit: 6, chapter: 22, type: "adjective" },
  { id: "u6_c22_75", native: "Haushaltsführung", english: "household management", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_76", native: "Kostenkontrolle", english: "cost control", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_77", native: "Sparplan", english: "savings plan", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_78", native: "Finanzplanung", english: "financial planning", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_79", native: "Schuldenabbau", english: "debt reduction", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_80", native: "Zinseszins", english: "compound interest", unit: 6, chapter: 22, type: "noun" },
  { id: "u6_c22_81", native: "Geldanlage", english: "investment", unit: 6, chapter: 22, type: "noun" }
];
