export const chapter12 = [
  { id: "u3_c12_01", native: "Hemd", english: "shirt", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_02", native: "Hose", english: "trousers / pants", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_03", native: "Rock", english: "skirt", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_04", native: "Kleid", english: "dress", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_05", native: "Pullover", english: "sweater / pullover", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_06", native: "T-Shirt", english: "T-shirt", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_07", native: "Bluse", english: "blouse", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_08", native: "Mantel", english: "coat", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_09", native: "Socken", english: "socks", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_10", native: "Hut", english: "hat", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_11", native: "Mütze", english: "cap / beanie", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_12", native: "Schal", english: "scarf", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_13", native: "Handschuhe", english: "gloves", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_14", native: "Gürtel", english: "belt", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_15", native: "Jeans", english: "jeans", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_16", native: "Shorts", english: "shorts", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_17", native: "Anzug", english: "suit", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_18", native: "Krawatte", english: "tie", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_19", native: "Sandalen", english: "sandals", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_20", native: "Hausschuhe", english: "slippers", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_21", native: "Regenmantel", english: "raincoat", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_22", native: "Rucksack", english: "backpack", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_23", native: "Geldbeutel", english: "wallet", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_24", native: "rot", english: "red", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_25", native: "blau", english: "blue", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_26", native: "grün", english: "green", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_27", native: "gelb", english: "yellow", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_28", native: "schwarz", english: "black", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_29", native: "weiß", english: "white", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_30", native: "grau", english: "grey / gray", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_31", native: "braun", english: "brown", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_32", native: "orange", english: "orange", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_33", native: "pink", english: "pink", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_34", native: "lila", english: "purple / lilac", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_35", native: "bunt", english: "colorful", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_36", native: "Farbe", english: "color / colour", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_37", native: "Größe", english: "size", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_38", native: "eng", english: "tight", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_39", native: "locker", english: "loose", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_40", native: "kurz", english: "short", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_41", native: "lang", english: "long", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_42", native: "XL", english: "extra large", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_43", native: "L", english: "large", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_44", native: "M", english: "medium", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_45", native: "S", english: "small", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_46", native: "XS", english: "extra small", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_47", native: "Maß", english: "measurement / made-to-measure", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_48", native: "Anprobe", english: "fitting / try-on", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_49", native: "Umkleidekabine", english: "fitting room / changing room", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_50", native: "Knopf", english: "button", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_51", native: "Reißverschluss", english: "zipper", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_52", native: "Baumwolle", english: "cotton", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_53", native: "Wolle", english: "wool", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_54", native: "Leder", english: "leather", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_55", native: "Seide", english: "silk", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_56", native: "Material", english: "material / fabric", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_57", native: "Muster", english: "pattern", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_58", native: "Apfel", english: "apple", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_59", native: "Banane", english: "banana", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_60", native: "Birne", english: "pear", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_61", native: "Orange", english: "orange (fruit)", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_62", native: "Zitrone", english: "lemon", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_63", native: "Traube", english: "grape", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_64", native: "Erdbeere", english: "strawberry", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_65", native: "Tomate", english: "tomato", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_66", native: "Kartoffel", english: "potato", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_67", native: "Zwiebel", english: "onion", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_68", native: "Karotte", english: "carrot", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_69", native: "Gurke", english: "cucumber", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_70", native: "Paprika", english: "bell pepper / paprika", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_71", native: "Salat", english: "lettuce / salad", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_72", native: "Milch", english: "milk", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_73", native: "Käse", english: "cheese", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_74", native: "Butter", english: "butter", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_75", native: "Ei", english: "egg", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_76", native: "Joghurt", english: "yoghurt", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_77", native: "Wurst", english: "sausage", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_78", native: "Hähnchen", english: "chicken", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_79", native: "Fisch", english: "fish", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_80", native: "Reis", english: "rice", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_81", native: "Nudeln", english: "noodles / pasta", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_82", native: "Zucker", english: "sugar", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_83", native: "Salz", english: "salt", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_84", native: "Öl", english: "oil", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_85", native: "Packung", english: "package / pack", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_86", native: "Flasche", english: "bottle", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_87", native: "Dose", english: "can / tin", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_88", native: "Tüte", english: "bag (paper/plastic)", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_89", native: "Kilo", english: "kilo / kilogram", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_90", native: "Gramm", english: "gram", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_91", native: "Liter", english: "liter", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_92", native: "wiegen", english: "to weigh", unit: 3, chapter: 12, type: "verb" },
  { id: "u3_c12_93", native: "Stück", english: "piece / item", unit: 3, chapter: 12, type: "noun" },
  { id: "u3_c12_94", native: "Bio", english: "organic", unit: 3, chapter: 12, type: "adjective" },
  { id: "u3_c12_95", native: "Angebot", english: "offer / special", unit: 3, chapter: 12, type: "noun" }
];
