export const chapter8 = [
  { id: "u2_c8_01", native: "Reise", english: "trip / journey", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_02", native: "Urlaub", english: "holiday / vacation", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_03", native: "Fahrt", english: "ride / journey", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_04", native: "Zug", english: "train", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_05", native: "Flug", english: "flight", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_06", native: "Flugzeug", english: "airplane", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_07", native: "Flughafen", english: "airport", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_08", native: "Koffer", english: "suitcase", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_09", native: "Gepäck", english: "luggage", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_10", native: "Pass", english: "passport", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_11", native: "Visum", english: "visa", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_12", native: "Ticket", english: "ticket", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_13", native: "Reservierung", english: "reservation", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_14", native: "Ziel", english: "destination", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_15", native: "Abreise", english: "departure", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_16", native: "Ankunft", english: "arrival", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_17", native: "fliegen", english: "to fly", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_18", native: "buchen", english: "to book", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_19", native: "packen", english: "to pack", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_20", native: "übernachten", english: "to stay overnight", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_21", native: "besuchen", english: "to visit", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_22", native: "erkunden", english: "to explore", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_23", native: "Soldat", english: "soldier", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_24", native: "Offizier", english: "officer", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_25", native: "Rang", english: "rank", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_26", native: "General", english: "general", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_27", native: "Hauptmann", english: "captain", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_28", native: "Leutnant", english: "lieutenant", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_29", native: "Feldwebel", english: "sergeant", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_30", native: "Unteroffizier", english: "NCO", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_31", native: "Dienst", english: "service / duty", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_32", native: "Ausbildung", english: "training", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_33", native: "Kaserne", english: "barracks", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_34", native: "Uniform", english: "uniform", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_35", native: "Befehl", english: "order / command", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_36", native: "marschieren", english: "to march", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_37", native: "melden", english: "to report", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_38", native: "dienen", english: "to serve", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_39", native: "Land", english: "country", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_40", native: "Grenze", english: "border", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_41", native: "Ausland", english: "abroad", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_42", native: "Inland", english: "domestic", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_43", native: "Stadtplan", english: "city map", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_44", native: "Führer", english: "guide", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_45", native: "Sehenswürdigkeit", english: "sight / attraction", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_46", native: "Museum", english: "museum", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_47", native: "Schloss", english: "castle", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_48", native: "Kirche", english: "church", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_49", native: "Denkmal", english: "monument", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_50", native: "Hotel", english: "hotel", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_51", native: "Zimmer", english: "room", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_52", native: "Übernachtung", english: "overnight stay", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_53", native: "bequem", english: "comfortable", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_54", native: "unbequem", english: "uncomfortable", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_55", native: "international", english: "international", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_56", native: "national", english: "national", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_57", native: "privat", english: "private", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_58", native: "öffentlich", english: "public", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_59", native: "mitnehmen", english: "to take along", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_60", native: "zurückkommen", english: "to return", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_61", native: "weiterfahren", english: "to continue on", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_62", native: "anmelden", english: "to check in", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_63", native: "abmelden", english: "to check out", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_64", native: "vorbereiten", english: "to prepare", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_65", native: "erinnern", english: "to remember", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_66", native: "vergessen", english: "to forget", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_67", native: "wichtig", english: "important", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_68", native: "notwendig", english: "necessary", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_69", native: "praktisch", english: "practical", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_70", native: "Reiseziel", english: "travel destination", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_71", native: "Unterkunft", english: "accommodation", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_72", native: "Gast", english: "guest", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_73", native: "Rezeption", english: "reception", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_74", native: "Schlüssel", english: "key", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_75", native: "Landkarte", english: "map", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_76", native: "Information", english: "information", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_77", native: "Auskunft", english: "inquiry", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_78", native: "Fahrgast", english: "passenger", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_79", native: "Gepäckträger", english: "porter", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_80", native: "Zoll", english: "customs", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_81", native: "Kontrolle", english: "control / check", unit: 2, chapter: 8, type: "noun" },
  { id: "u2_c8_82", native: "erlauben", english: "to allow", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_83", native: "verbieten", english: "to forbid", unit: 2, chapter: 8, type: "verb" },
  { id: "u2_c8_84", native: "gültig", english: "valid", unit: 2, chapter: 8, type: "adjective" },
  { id: "u2_c8_85", native: "ungültig", english: "invalid", unit: 2, chapter: 8, type: "adjective" }
];
