export const chapter1 = [
  { id: "u1_c1_01", native: "Hallo", english: "Hello", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_02", native: "Guten Morgen", english: "Good morning", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_03", native: "Guten Tag", english: "Good day", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_04", native: "Guten Abend", english: "Good evening", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_05", native: "Gute Nacht", english: "Good night", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_06", native: "Tschüss", english: "Bye", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_07", native: "Auf Wiedersehen", english: "Goodbye", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_08", native: "Danke", english: "Thank you", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_09", native: "Bitte", english: "Please / You're welcome", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_10", native: "Entschuldigung", english: "Excuse me / Sorry", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_11", native: "Ja", english: "Yes", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_12", native: "Nein", english: "No", unit: 1, chapter: 1, type: "interjection" },
  { id: "u1_c1_13", native: "ich", english: "I", unit: 1, chapter: 1, type: "pronoun" },
  { id: "u1_c1_14", native: "du", english: "you (informal)", unit: 1, chapter: 1, type: "pronoun" },
  { id: "u1_c1_15", native: "Sie", english: "you (formal)", unit: 1, chapter: 1, type: "pronoun" },
  { id: "u1_c1_16", native: "heißen", english: "to be called", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_17", native: "sein", english: "to be", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_18", native: "kommen", english: "to come", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_19", native: "wohnen", english: "to live", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_20", native: "aus", english: "from / out of", unit: 1, chapter: 1, type: "preposition" },
  { id: "u1_c1_21", native: "in", english: "in", unit: 1, chapter: 1, type: "preposition" },
  { id: "u1_c1_22", native: "Name", english: "name", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_23", native: "aufwachen", english: "to wake up", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_24", native: "aufstehen", english: "to get up", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_25", native: "waschen", english: "to wash", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_26", native: "duschen", english: "to shower", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_27", native: "baden", english: "to bathe", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_28", native: "Zahn", english: "tooth", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_29", native: "putzen", english: "to brush / clean", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_30", native: "anziehen", english: "to put on / get dressed", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_31", native: "Kleidung", english: "clothing", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_32", native: "Frühstück", english: "breakfast", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_33", native: "frühstücken", english: "to have breakfast", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_34", native: "essen", english: "to eat", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_35", native: "trinken", english: "to drink", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_36", native: "Mittagessen", english: "lunch", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_37", native: "Abendessen", english: "dinner", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_38", native: "Hunger", english: "hunger", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_39", native: "Durst", english: "thirst", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_40", native: "gehen", english: "to go", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_41", native: "Arbeit", english: "work", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_42", native: "arbeiten", english: "to work", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_43", native: "lernen", english: "to learn / study", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_44", native: "Schule", english: "school", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_45", native: "Büro", english: "office", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_46", native: "Haus", english: "house / home", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_47", native: "verlassen", english: "to leave", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_48", native: "schlafen", english: "to sleep", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_49", native: "Bett", english: "bed", unit: 1, chapter: 1, type: "noun" },
  { id: "u1_c1_50", native: "ausruhen", english: "to rest", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_51", native: "fernsehen", english: "to watch TV", unit: 1, chapter: 1, type: "verb" },
  { id: "u1_c1_52", native: "müde", english: "tired", unit: 1, chapter: 1, type: "adjective" },
  { id: "u1_c1_53", native: "fertig", english: "finished / ready", unit: 1, chapter: 1, type: "adjective" },
  { id: "u1_c1_54", native: "gut", english: "good", unit: 1, chapter: 1, type: "adjective" },
  { id: "u1_c1_55", native: "und", english: "and", unit: 1, chapter: 1, type: "conjunction" }
];
