export const chapter13 = [
  { id: "u4_c13_01", native: "Terminal", english: "terminal", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_02", native: "Gate", english: "gate", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_03", native: "Landebahn", english: "runway", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_04", native: "Ankunftshalle", english: "arrivals hall", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_05", native: "Abflughalle", english: "departures hall", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_06", native: "Gepäckausgabe", english: "baggage claim", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_07", native: "Gepäckband", english: "baggage carousel", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_08", native: "Anzeigetafel", english: "display board / departures board", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_09", native: "Bordkarte", english: "boarding pass", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_10", native: "Einreise", english: "entry / immigration", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_11", native: "Einreisekontrolle", english: "immigration control", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_12", native: "Passkontrolle", english: "passport control", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_13", native: "Stempel", english: "stamp (passport)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_14", native: "Einreiseformular", english: "entry form / landing card", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_15", native: "Zollerklärung", english: "customs declaration", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_16", native: "landen", english: "to land", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_17", native: "vorzeigen", english: "to present / show (documents)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_18", native: "stempeln", english: "to stamp", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_19", native: "deklarieren", english: "to declare (customs)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_20", native: "durchsuchen", english: "to search / inspect (luggage)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_21", native: "Zollbeamter", english: "customs officer (male)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_22", native: "Zollbeamtin", english: "customs officer (female)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_23", native: "Grenzbeamter", english: "border officer (male)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_24", native: "Grenzbeamtin", english: "border officer (female)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_25", native: "Flugbegleiter", english: "flight attendant (male)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_26", native: "Flugbegleiterin", english: "flight attendant (female)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_27", native: "Passagier", english: "passenger", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_28", native: "Verspätung", english: "delay", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_29", native: "verspätet", english: "delayed", unit: 4, chapter: 13, type: "adjective" },
  { id: "u4_c13_30", native: "Übergepäck", english: "excess baggage", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_31", native: "Handgepäck", english: "hand luggage / carry-on", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_32", native: "Sicherheitskontrolle", english: "security check", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_33", native: "Ausgang", english: "exit", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_34", native: "Rolltreppe", english: "escalator", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_35", native: "Fahrstuhl", english: "elevator / lift", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_36", native: "Gepäckwagen", english: "luggage trolley", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_37", native: "Schalter", english: "counter / desk", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_38", native: "Fundbüro", english: "lost-and-found office", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_39", native: "abfliegen", english: "to take off / depart (plane)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_40", native: "starten", english: "to take off", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_41", native: "Flugnummer", english: "flight number", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_42", native: "Sitzplatz", english: "seat", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_43", native: "Körperscanner", english: "body scanner", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_44", native: "Metalldetektor", english: "metal detector", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_45", native: "Zollkontrolle", english: "customs inspection", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_46", native: "freigeben", english: "to clear / release (luggage)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_47", native: "beschlagnahmen", english: "to confiscate", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_48", native: "angeben", english: "to declare (items at customs)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_49", native: "Duty-free", english: "duty-free", unit: 4, chapter: 13, type: "adjective" },
  { id: "u4_c13_50", native: "Anschlussflug", english: "connecting flight", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_51", native: "Transitbereich", english: "transit area", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_52", native: "Gepäckschein", english: "baggage claim tag", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_53", native: "verloren", english: "lost", unit: 4, chapter: 13, type: "adjective" },
  { id: "u4_c13_54", native: "beschädigt", english: "damaged", unit: 4, chapter: 13, type: "adjective" },
  { id: "u4_c13_55", native: "abholen", english: "to pick up (luggage)", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_56", native: "kontrollieren", english: "to check / inspect", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_57", native: "abwarten", english: "to wait for / await", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_58", native: "Schlange", english: "queue / line", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_59", native: "anstehen", english: "to queue / stand in line", unit: 4, chapter: 13, type: "verb" },
  { id: "u4_c13_60", native: "Ausweis", english: "ID document", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_61", native: "Aufenthaltsgenehmigung", english: "residence permit", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_62", native: "Visumpflicht", english: "visa requirement", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_63", native: "visumfrei", english: "visa-free", unit: 4, chapter: 13, type: "adjective" },
  { id: "u4_c13_64", native: "Einreisestempel", english: "entry stamp", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_65", native: "Ausreisestempel", english: "exit stamp", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_66", native: "Grenzübergang", english: "border crossing", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_67", native: "Schengen", english: "Schengen (area)", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_68", native: "Landungsbrücke", english: "jet bridge / airbridge", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_69", native: "Busshuttle", english: "shuttle bus", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_70", native: "Ankunftszeit", english: "arrival time", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_71", native: "Abflugzeit", english: "departure time", unit: 4, chapter: 13, type: "noun" },
  { id: "u4_c13_72", native: "Flugsteig", english: "gate (boarding)", unit: 4, chapter: 13, type: "noun" }
];
