export const chapter2 = [
  { id: "u1_c2_01", native: "Montag", english: "Monday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_02", native: "Dienstag", english: "Tuesday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_03", native: "Mittwoch", english: "Wednesday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_04", native: "Donnerstag", english: "Thursday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_05", native: "Freitag", english: "Friday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_06", native: "Samstag", english: "Saturday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_07", native: "Sonntag", english: "Sunday", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_08", native: "Woche", english: "week", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_09", native: "Wochenende", english: "weekend", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_10", native: "Tag", english: "day", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_11", native: "Monat", english: "month", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_12", native: "Jahr", english: "year", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_13", native: "Januar", english: "January", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_14", native: "Februar", english: "February", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_15", native: "März", english: "March", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_16", native: "April", english: "April", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_17", native: "Mai", english: "May", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_18", native: "Juni", english: "June", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_19", native: "Juli", english: "July", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_20", native: "August", english: "August", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_21", native: "September", english: "September", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_22", native: "Oktober", english: "October", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_23", native: "November", english: "November", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_24", native: "Dezember", english: "December", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_25", native: "Uhr", english: "clock / o'clock", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_26", native: "Stunde", english: "hour", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_27", native: "Minute", english: "minute", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_28", native: "Zeit", english: "time", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_29", native: "Termin", english: "appointment", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_30", native: "Pause", english: "break", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_31", native: "Viertel", english: "quarter", unit: 1, chapter: 2, type: "noun" },
  { id: "u1_c2_32", native: "eins", english: "one", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_33", native: "zwei", english: "two", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_34", native: "drei", english: "three", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_35", native: "vier", english: "four", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_36", native: "fünf", english: "five", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_37", native: "sechs", english: "six", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_38", native: "sieben", english: "seven", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_39", native: "acht", english: "eight", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_40", native: "neun", english: "nine", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_41", native: "zehn", english: "ten", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_42", native: "elf", english: "eleven", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_43", native: "zwölf", english: "twelve", unit: 1, chapter: 2, type: "numeral" },
  { id: "u1_c2_44", native: "heute", english: "today", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_45", native: "morgen", english: "tomorrow", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_46", native: "gestern", english: "yesterday", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_47", native: "früh", english: "early", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_48", native: "spät", english: "late", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_49", native: "morgens", english: "in the mornings", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_50", native: "abends", english: "in the evenings", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_51", native: "jetzt", english: "now", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_52", native: "bald", english: "soon", unit: 1, chapter: 2, type: "adverb" },
  { id: "u1_c2_53", native: "nächste", english: "next", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_54", native: "letzte", english: "last", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_55", native: "frei", english: "free", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_56", native: "pünktlich", english: "on time / punctual", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_57", native: "halb", english: "half", unit: 1, chapter: 2, type: "adjective" },
  { id: "u1_c2_58", native: "um", english: "at (time)", unit: 1, chapter: 2, type: "preposition" },
  { id: "u1_c2_59", native: "vor", english: "before", unit: 1, chapter: 2, type: "preposition" },
  { id: "u1_c2_60", native: "nach", english: "after", unit: 1, chapter: 2, type: "preposition" },
  { id: "u1_c2_61", native: "planen", english: "to plan", unit: 1, chapter: 2, type: "verb" },
  { id: "u1_c2_62", native: "treffen", english: "to meet", unit: 1, chapter: 2, type: "verb" },
  { id: "u1_c2_63", native: "beginnen", english: "to begin", unit: 1, chapter: 2, type: "verb" },
  { id: "u1_c2_64", native: "enden", english: "to end", unit: 1, chapter: 2, type: "verb" },
  { id: "u1_c2_65", native: "oder", english: "or", unit: 1, chapter: 2, type: "conjunction" }
];
