export const chapter11 = [
  { id: "u3_c11_01", native: "einchecken", english: "to check in", unit: 3, chapter: 11, type: "verb" },
  { id: "u3_c11_02", native: "auschecken", english: "to check out", unit: 3, chapter: 11, type: "verb" },
  { id: "u3_c11_03", native: "Check-in", english: "check-in", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_04", native: "Check-out", english: "check-out", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_05", native: "Empfang", english: "reception / front desk", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_06", native: "Schlüsselkarte", english: "key card", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_07", native: "Etage", english: "floor / storey", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_08", native: "Stockwerk", english: "floor / level", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_09", native: "Aufzug", english: "elevator / lift", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_10", native: "Treppe", english: "stairs", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_11", native: "Einzelzimmer", english: "single room", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_12", native: "Doppelzimmer", english: "double room", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_13", native: "Suite", english: "suite", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_14", native: "Handtuch", english: "towel", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_15", native: "Bettwäsche", english: "bed linen / sheets", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_16", native: "Frühstücksbuffet", english: "breakfast buffet", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_17", native: "Halbpension", english: "half board", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_18", native: "Vollpension", english: "full board", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_19", native: "Zimmerservice", english: "room service", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_20", native: "Klimaanlage", english: "air conditioning", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_21", native: "Heizung", english: "heating", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_22", native: "Minibar", english: "minibar", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_23", native: "Safe", english: "safe (deposit box)", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_24", native: "Wlan", english: "Wi-Fi", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_25", native: "Internet", english: "internet", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_26", native: "Lobby", english: "lobby", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_27", native: "Concierge", english: "concierge", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_28", native: "Notruf", english: "emergency call", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_29", native: "Notausgang", english: "emergency exit", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_30", native: "Feueralarm", english: "fire alarm", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_31", native: "lecker", english: "delicious / tasty", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_32", native: "köstlich", english: "delicious / exquisite", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_33", native: "schmackhaft", english: "tasty / flavorful", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_34", native: "frisch", english: "fresh", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_35", native: "salzig", english: "salty", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_36", native: "süß", english: "sweet", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_37", native: "sauer", english: "sour", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_38", native: "bitter", english: "bitter", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_39", native: "scharf", english: "spicy / hot (taste)", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_40", native: "mild", english: "mild", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_41", native: "würzig", english: "spicy / aromatic", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_42", native: "fade", english: "bland / tasteless", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_43", native: "schmecken", english: "to taste / to be tasty", unit: 3, chapter: 11, type: "verb" },
  { id: "u3_c11_44", native: "Geschmack", english: "taste / flavour", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_45", native: "Qualität", english: "quality", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_46", native: "empfehlen", english: "to recommend", unit: 3, chapter: 11, type: "verb" },
  { id: "u3_c11_47", native: "Empfehlung", english: "recommendation", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_48", native: "Beschwerde", english: "complaint", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_49", native: "reklamieren", english: "to complain / make a claim", unit: 3, chapter: 11, type: "verb" },
  { id: "u3_c11_50", native: "zufrieden", english: "satisfied", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_51", native: "unzufrieden", english: "dissatisfied", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_52", native: "Na ja", english: "well / oh well", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_53", native: "Egal", english: "doesn't matter / whatever", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_54", native: "Schon gut", english: "it's fine / never mind", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_55", native: "Keine Ahnung", english: "no idea", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_56", native: "Natürlich", english: "of course / naturally", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_57", native: "Vielleicht", english: "maybe / perhaps", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_58", native: "Hoffentlich", english: "hopefully", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_59", native: "leider", english: "unfortunately", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_60", native: "zum Glück", english: "fortunately / luckily", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_61", native: "Immer noch", english: "still", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_62", native: "Noch mal", english: "again / one more time", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_63", native: "Was gibt's", english: "what's up / what's new", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_64", native: "Wie bitte", english: "pardon / excuse me", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_65", native: "Ach so", english: "oh I see / ah", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_66", native: "Genau", english: "exactly", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_67", native: "Stimmt", english: "that's right / correct", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_68", native: "Quatsch", english: "nonsense", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_69", native: "Tatsächlich", english: "actually / indeed", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_70", native: "Allerdings", english: "however / though", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_71", native: "Sowieso", english: "anyway", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_72", native: "Trotzdem", english: "nevertheless / still", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_73", native: "Außerdem", english: "besides / in addition", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_74", native: "Übrigens", english: "by the way", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_75", native: "Jedenfalls", english: "in any case / anyway", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_76", native: "Eigentlich", english: "actually / really", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_77", native: "Bestimmt", english: "certainly / definitely", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_78", native: "Wahrscheinlich", english: "probably", unit: 3, chapter: 11, type: "adverb" },
  { id: "u3_c11_79", native: "Unwahrscheinlich", english: "unlikely", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_80", native: "Möglich", english: "possible", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_81", native: "Unmöglich", english: "impossible", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_82", native: "Toll", english: "great / awesome", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_83", native: "Super", english: "super / great", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_84", native: "Prima", english: "fine / excellent", unit: 3, chapter: 11, type: "adjective" },
  { id: "u3_c11_85", native: "Schade", english: "what a pity / too bad", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_86", native: "Mist", english: "damn / crap", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_87", native: "Prost", english: "cheers", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_88", native: "Gesundheit", english: "bless you / health", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_89", native: "Willkommen", english: "welcome", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_90", native: "Auf Wiederhören", english: "goodbye (on the phone)", unit: 3, chapter: 11, type: "interjection" },
  { id: "u3_c11_91", native: "Service", english: "service", unit: 3, chapter: 11, type: "noun" },
  { id: "u3_c11_92", native: "Gastfreundschaft", english: "hospitality", unit: 3, chapter: 11, type: "noun" }
];
