export const chapter14 = [
  { id: "u4_c14_01", native: "Linie", english: "line (public transport)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_02", native: "Umstieg", english: "transfer / change (of transport)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_03", native: "Tarifzone", english: "fare zone", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_04", native: "Deutschlandticket", english: "Germany ticket (nationwide monthly pass)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_05", native: "Monatskarte", english: "monthly pass", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_06", native: "Tageskarte", english: "day ticket", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_07", native: "Kontrolleur", english: "ticket inspector", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_08", native: "Entwerter", english: "ticket validator / stamp machine", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_09", native: "Gleis", english: "track / platform (rail)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_10", native: "Bahnsteig", english: "platform", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_11", native: "Hauptbahnhof", english: "main train station", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_12", native: "Endstation", english: "terminus / last stop", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_13", native: "abbiegen", english: "to turn (left/right)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_14", native: "überqueren", english: "to cross (street)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_15", native: "folgen", english: "to follow", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_16", native: "Fußgängerüberweg", english: "pedestrian crossing", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_17", native: "Zebrastreifen", english: "zebra crossing", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_18", native: "Einbahnstraße", english: "one-way street", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_19", native: "Sackgasse", english: "dead end", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_20", native: "Kreisverkehr", english: "roundabout", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_21", native: "Tunnel", english: "tunnel", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_22", native: "Unterführung", english: "underpass", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_23", native: "Überführung", english: "overpass / flyover", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_24", native: "Schild", english: "sign / street sign", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_25", native: "Wegweiser", english: "signpost / waymarker", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_26", native: "Navigation", english: "navigation", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_27", native: "GPS", english: "GPS", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_28", native: "Großeltern", english: "grandparents", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_29", native: "Enkel", english: "grandson / grandchild (male)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_30", native: "Enkelin", english: "granddaughter", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_31", native: "Geschwister", english: "siblings", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_32", native: "Nachbar", english: "neighbour (male)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_33", native: "Nachbarin", english: "neighbour (female)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_34", native: "Nachbarschaft", english: "neighbourhood", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_35", native: "Spielplatz", english: "playground", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_36", native: "Kindergarten", english: "kindergarten / preschool", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_37", native: "Kita", english: "daycare centre (Kita)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_38", native: "Grundschule", english: "primary school", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_39", native: "Gymnasium", english: "academic secondary school", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_40", native: "Stadtteil", english: "district / neighbourhood of a city", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_41", native: "Innenstadt", english: "city centre", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_42", native: "Vorort", english: "suburb", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_43", native: "Fußweg", english: "footpath / pedestrian path", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_44", native: "Radweg", english: "cycle path", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_45", native: "Bushaltestelle", english: "bus stop", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_46", native: "Straßenbahnlinie", english: "tram line", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_47", native: "Fahrplanauskunft", english: "timetable information", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_48", native: "Verspätungsmeldung", english: "delay announcement", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_49", native: "halten", english: "to stop (vehicle)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_50", native: "verpassen", english: "to miss (a connection)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_51", native: "erreichen", english: "to reach / make (a connection)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_52", native: "wechseln", english: "to change (lines)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_53", native: "besteigen", english: "to board (vehicle)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_54", native: "absteigen", english: "to get off (vehicle)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_55", native: "Fahrtrichtung", english: "direction of travel", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_56", native: "Zielhaltestelle", english: "destination stop", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_57", native: "nächstgelegen", english: "nearest / next (stop)", unit: 4, chapter: 14, type: "adjective" },
  { id: "u4_c14_58", native: "vorherige", english: "previous (stop)", unit: 4, chapter: 14, type: "adjective" },
  { id: "u4_c14_59", native: "gegenüberliegend", english: "opposite (side)", unit: 4, chapter: 14, type: "adjective" },
  { id: "u4_c14_60", native: "parallel", english: "parallel", unit: 4, chapter: 14, type: "adjective" },
  { id: "u4_c14_61", native: "Schwiegereltern", english: "parents-in-law", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_62", native: "Schwiegersohn", english: "son-in-law", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_63", native: "Schwiegertochter", english: "daughter-in-law", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_64", native: "Stiefvater", english: "stepfather", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_65", native: "Stiefmutter", english: "stepmother", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_66", native: "Halbbruder", english: "half-brother", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_67", native: "Halbschwester", english: "half-sister", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_68", native: "Familienausflug", english: "family outing", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_69", native: "Stadtpark", english: "city park", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_70", native: "Wochenmarkt", english: "weekly market", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_71", native: "Fußgängerbereich", english: "pedestrian area", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_72", native: "Einkaufsstraße", english: "shopping street", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_73", native: "Haltepunkt", english: "stop / halt", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_74", native: "Beförderter", english: "passenger (transported person)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_75", native: "Schwarzfahrer", english: "fare dodger", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_76", native: "Bußgeld", english: "fine (penalty)", unit: 4, chapter: 14, type: "noun" },
  { id: "u4_c14_77", native: "entwerten", english: "to validate (a ticket)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_78", native: "durchsagen", english: "to announce (over loudspeaker)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_79", native: "anschließen", english: "to connect (to another line)", unit: 4, chapter: 14, type: "verb" },
  { id: "u4_c14_80", native: "Stadtverkehr", english: "city transport / urban traffic", unit: 4, chapter: 14, type: "noun" }
];
