export const chapter15 = [
  { id: "u4_c15_01", native: "Bundesland", english: "federal state", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_02", native: "Hauptstadt", english: "capital city", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_03", native: "Meer", english: "sea", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_04", native: "Nordsee", english: "North Sea", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_05", native: "Ostsee", english: "Baltic Sea", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_06", native: "Rhein", english: "Rhine (river)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_07", native: "Elbe", english: "Elbe (river)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_08", native: "Donau", english: "Danube (river)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_09", native: "Alpen", english: "Alps", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_10", native: "Schwarzwald", english: "Black Forest", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_11", native: "Berlin", english: "Berlin", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_12", native: "München", english: "Munich", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_13", native: "Hamburg", english: "Hamburg", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_14", native: "Köln", english: "Cologne", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_15", native: "Frankfurt", english: "Frankfurt", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_16", native: "Dresden", english: "Dresden", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_17", native: "Leipzig", english: "Leipzig", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_18", native: "Stuttgart", english: "Stuttgart", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_19", native: "Mauer", english: "wall (esp. Berlin Wall)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_20", native: "Berliner Mauer", english: "Berlin Wall", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_21", native: "DDR", english: "GDR / East Germany", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_22", native: "BRD", english: "FRG / West Germany", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_23", native: "Westberlin", english: "West Berlin", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_24", native: "Ostberlin", english: "East Berlin", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_25", native: "Checkpoint", english: "checkpoint", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_26", native: "Flucht", english: "escape / flight", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_27", native: "Flüchtling", english: "refugee / escapee", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_28", native: "Stasi", english: "Stasi (East German secret police)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_29", native: "Wiedervereinigung", english: "reunification", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_30", native: "Teilung", english: "division / partition", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_31", native: "vereinigen", english: "to reunite / unify", unit: 4, chapter: 15, type: "verb" },
  { id: "u4_c15_32", native: "teilen", english: "to divide / split", unit: 4, chapter: 15, type: "verb" },
  { id: "u4_c15_33", native: "Osten", english: "the East", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_34", native: "Westen", english: "the West", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_35", native: "Norden", english: "the North", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_36", native: "Süden", english: "the South", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_37", native: "Bundesrepublik", english: "Federal Republic", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_38", native: "Geschichte", english: "history", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_39", native: "historisch", english: "historical", unit: 4, chapter: 15, type: "adjective" },
  { id: "u4_c15_40", native: "Gedenkstätte", english: "memorial site", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_41", native: "Todesstreifen", english: "death strip (border zone)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_42", native: "Grenzübergangsstelle", english: "border crossing point", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_43", native: "Mauergedenkstätte", english: "Wall memorial", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_44", native: "Fall der Mauer", english: "fall of the Wall", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_45", native: "neunzehnhundertneunundachtzig", english: "1989", unit: 4, chapter: 15, type: "numeral" },
  { id: "u4_c15_46", native: "neunzehnhundertneunzig", english: "1990", unit: 4, chapter: 15, type: "numeral" },
  { id: "u4_c15_47", native: "Ostdeutschland", english: "East Germany (region)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_48", native: "Westdeutschland", english: "West Germany (region)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_49", native: "Bundesrepublik Deutschland", english: "Federal Republic of Germany", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_50", native: "Deutsche Demokratische Republik", english: "German Democratic Republic", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_51", native: "passierbar", english: "passable (border)", unit: 4, chapter: 15, type: "adjective" },
  { id: "u4_c15_52", native: "überwinden", english: "to overcome / surmount (the Wall)", unit: 4, chapter: 15, type: "verb" },
  { id: "u4_c15_53", native: "trennen", english: "to separate", unit: 4, chapter: 15, type: "verb" },
  { id: "u4_c15_54", native: "wiedervereinen", english: "to reunify", unit: 4, chapter: 15, type: "verb" },
  { id: "u4_c15_55", native: "Erinnerung", english: "memory / remembrance", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_56", native: "Gedenken", english: "commemoration", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_57", native: "Zeitzeuge", english: "contemporary witness", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_58", native: "Dokumentation", english: "documentation / documentary", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_59", native: "Ausstellung", english: "exhibition", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_60", native: "Mauerrest", english: "remaining section of the Wall", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_61", native: "East Side Gallery", english: "East Side Gallery", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_62", native: "Brandenburger Tor", english: "Brandenburg Gate", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_63", native: "Reichstag", english: "Reichstag building", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_64", native: "Fernsehturm", english: "TV tower", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_65", native: "Küste", english: "coast", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_66", native: "Gebirge", english: "mountain range", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_67", native: "Tal", english: "valley", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_68", native: "Hochebene", english: "plateau", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_69", native: "Seenplatte", english: "lake district", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_70", native: "Insel", english: "island", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_71", native: "Halbinsel", english: "peninsula", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_72", native: "Bundeshauptstadt", english: "federal capital", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_73", native: "Landeshauptstadt", english: "state capital", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_74", native: "Einwohner", english: "inhabitant / resident", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_75", native: "Bevölkerungszahl", english: "population figure", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_76", native: "Fläche", english: "area (of land)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_77", native: "Staatsgrenze", english: "national border", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_78", native: "Nachbarland", english: "neighbouring country", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_79", native: "Mitteleuropa", english: "Central Europe", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_80", native: "Westeuropa", english: "Western Europe", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_81", native: "Osteuropa", english: "Eastern Europe", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_82", native: "Kalter Krieg", english: "Cold War", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_83", native: "Eiserner Vorhang", english: "Iron Curtain", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_84", native: "Friedliche Revolution", english: "Peaceful Revolution", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_85", native: "Wende", english: "the Turn (reunification period)", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_86", native: "Einheitsvertrag", english: "Unification Treaty", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_87", native: "Tag der Deutschen Einheit", english: "German Unity Day", unit: 4, chapter: 15, type: "noun" },
  { id: "u4_c15_88", native: "bundesweit", english: "nationwide / federal-wide", unit: 4, chapter: 15, type: "adjective" }
];
