export const chapter18 = [
  { id: "u5_c18_01", native: "Waschmaschine", english: "washing machine", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_02", native: "Trockner", english: "tumble dryer", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_03", native: "Spülmaschine", english: "dishwasher", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_04", native: "Kühlschrank", english: "refrigerator", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_05", native: "Gefrierschrank", english: "freezer", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_06", native: "Herd", english: "stove / cooker", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_07", native: "Ofen", english: "oven", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_08", native: "Mikrowelle", english: "microwave", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_09", native: "Kaffeemaschine", english: "coffee machine", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_10", native: "Toaster", english: "toaster", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_11", native: "Mixer", english: "blender / mixer", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_12", native: "Wasserkocher", english: "electric kettle", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_13", native: "Dunstabzugshaube", english: "cooker hood", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_14", native: "Staubsauger", english: "vacuum cleaner", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_15", native: "Bügeleisen", english: "iron", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_16", native: "Bügelbrett", english: "ironing board", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_17", native: "Föhn", english: "hair dryer", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_18", native: "Fernseher", english: "television", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_19", native: "Laptop", english: "laptop", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_20", native: "Smartphone", english: "smartphone", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_21", native: "Tablet", english: "tablet", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_22", native: "Drucker", english: "printer", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_23", native: "Scanner", english: "scanner", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_24", native: "Lautsprecher", english: "loudspeaker", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_25", native: "Kopfhörer", english: "headphones", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_26", native: "Ladegerät", english: "charger", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_27", native: "Akku", english: "rechargeable battery", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_28", native: "Kabel", english: "cable", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_29", native: "Stecker", english: "plug", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_30", native: "Steckdose", english: "power socket", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_31", native: "Adapter", english: "adapter", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_32", native: "Router", english: "router", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_33", native: "WLAN", english: "Wi-Fi", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_34", native: "Bildschirm", english: "screen / monitor", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_35", native: "Tastatur", english: "keyboard", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_36", native: "Computermaus", english: "computer mouse", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_37", native: "Webcam", english: "webcam", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_38", native: "Festplatte", english: "hard drive", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_39", native: "USB-Stick", english: "USB stick", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_40", native: "Klimagerät", english: "air-conditioning unit", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_41", native: "Heizkörper", english: "radiator", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_42", native: "Thermostat", english: "thermostat", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_43", native: "Stehlampe", english: "floor lamp", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_44", native: "Glühbirne", english: "light bulb", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_45", native: "Batterie", english: "battery", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_46", native: "Fernbedienung", english: "remote control", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_47", native: "Konsole", english: "games console", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_48", native: "Kamera", english: "camera", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_49", native: "Objektiv", english: "camera lens", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_50", native: "einschalten", english: "to switch on", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_51", native: "ausschalten", english: "to switch off", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_52", native: "aufladen", english: "to charge", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_53", native: "verkabeln", english: "to wire / cable up", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_54", native: "installieren", english: "to install", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_55", native: "reparieren", english: "to repair", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_56", native: "ersetzen", english: "to replace", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_57", native: "benutzen", english: "to use", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_58", native: "funktionieren", english: "to function / work", unit: 5, chapter: 18, type: "verb" },
  { id: "u5_c18_59", native: "defekt", english: "defective", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_60", native: "energiesparend", english: "energy-saving", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_61", native: "kabellos", english: "wireless", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_62", native: "tragbar", english: "portable", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_63", native: "hochwertig", english: "high-quality", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_64", native: "kostspielig", english: "costly / expensive", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_65", native: "brandneu", english: "brand-new", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_66", native: "gebraucht", english: "used / second-hand", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_67", native: "modern", english: "modern", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_68", native: "handlich", english: "handy / convenient", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_69", native: "zuverlässig", english: "reliable", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_70", native: "geräuschvoll", english: "noisy", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_71", native: "geräuscharm", english: "quiet / low-noise", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_72", native: "leistungsstark", english: "powerful", unit: 5, chapter: 18, type: "adjective" },
  { id: "u5_c18_73", native: "Garantie", english: "warranty", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_74", native: "Kassenbon", english: "sales receipt", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_75", native: "Lieferung", english: "delivery", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_76", native: "Versand", english: "shipping", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_77", native: "Rücksendung", english: "return shipment", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_78", native: "Umtausch", english: "exchange", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_79", native: "Marke", english: "brand", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_80", native: "Modell", english: "model", unit: 5, chapter: 18, type: "noun" },
  { id: "u5_c18_81", native: "Garantiezeit", english: "warranty period", unit: 5, chapter: 18, type: "noun" },
];
