export const chapter3 = [
  { id: "u1_c3_01", native: "Frühling", english: "spring", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_02", native: "Sommer", english: "summer", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_03", native: "Herbst", english: "autumn / fall", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_04", native: "Winter", english: "winter", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_05", native: "Jahreszeit", english: "season", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_06", native: "Wetter", english: "weather", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_07", native: "Sonne", english: "sun", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_08", native: "Regen", english: "rain", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_09", native: "Schnee", english: "snow", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_10", native: "Wind", english: "wind", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_11", native: "Wolke", english: "cloud", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_12", native: "Himmel", english: "sky", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_13", native: "Temperatur", english: "temperature", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_14", native: "Grad", english: "degree", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_15", native: "Sturm", english: "storm", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_16", native: "Nebel", english: "fog", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_17", native: "Blitz", english: "lightning", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_18", native: "Eis", english: "ice", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_19", native: "Hitze", english: "heat", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_20", native: "Kälte", english: "cold / coldness", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_21", native: "sonnig", english: "sunny", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_22", native: "regnerisch", english: "rainy", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_23", native: "windig", english: "windy", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_24", native: "bewölkt", english: "cloudy", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_25", native: "kalt", english: "cold", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_26", native: "warm", english: "warm", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_27", native: "heiß", english: "hot", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_28", native: "kühl", english: "cool", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_29", native: "trocken", english: "dry", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_30", native: "nass", english: "wet", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_31", native: "schön", english: "nice / beautiful", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_32", native: "schlecht", english: "bad", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_33", native: "dunkel", english: "dark", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_34", native: "hell", english: "bright / light", unit: 1, chapter: 3, type: "adjective" },
  { id: "u1_c3_35", native: "regnen", english: "to rain", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_36", native: "schneien", english: "to snow", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_37", native: "scheinen", english: "to shine", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_38", native: "spazieren", english: "to stroll / walk for pleasure", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_39", native: "laufen", english: "to walk / run", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_40", native: "fahren", english: "to drive / ride", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_41", native: "bleiben", english: "to stay", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_42", native: "ausgehen", english: "to go out", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_43", native: "öffnen", english: "to open", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_44", native: "schließen", english: "to close", unit: 1, chapter: 3, type: "verb" },
  { id: "u1_c3_45", native: "draußen", english: "outside", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_46", native: "drinnen", english: "inside", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_47", native: "Park", english: "park", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_48", native: "Straße", english: "street", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_49", native: "Fenster", english: "window", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_50", native: "Tür", english: "door", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_51", native: "Regenschirm", english: "umbrella", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_52", native: "Jacke", english: "jacket", unit: 1, chapter: 3, type: "noun" },
  { id: "u1_c3_53", native: "es", english: "it", unit: 1, chapter: 3, type: "pronoun" },
  { id: "u1_c3_54", native: "aber", english: "but", unit: 1, chapter: 3, type: "conjunction" },
  { id: "u1_c3_55", native: "weil", english: "because", unit: 1, chapter: 3, type: "conjunction" },
  { id: "u1_c3_56", native: "wenn", english: "if / when", unit: 1, chapter: 3, type: "conjunction" },
  { id: "u1_c3_57", native: "sehr", english: "very", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_58", native: "oft", english: "often", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_59", native: "manchmal", english: "sometimes", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_60", native: "immer", english: "always", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_61", native: "nie", english: "never", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_62", native: "hier", english: "here", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_63", native: "dort", english: "there", unit: 1, chapter: 3, type: "adverb" },
  { id: "u1_c3_64", native: "mit", english: "with", unit: 1, chapter: 3, type: "preposition" },
  { id: "u1_c3_65", native: "ohne", english: "without", unit: 1, chapter: 3, type: "preposition" },
  { id: "u1_c3_66", native: "für", english: "for", unit: 1, chapter: 3, type: "preposition" },
  { id: "u1_c3_67", native: "bei", english: "at / near", unit: 1, chapter: 3, type: "preposition" },
  { id: "u1_c3_68", native: "zu", english: "to", unit: 1, chapter: 3, type: "preposition" },
  { id: "u1_c3_69", native: "von", english: "from / of", unit: 1, chapter: 3, type: "preposition" },
  { id: "u1_c3_70", native: "an", english: "at / on", unit: 1, chapter: 3, type: "preposition" }
];
