export const chapter6 = [
  { id: "u2_c6_01", native: "Fußball", english: "football / soccer", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_02", native: "Tennis", english: "tennis", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_03", native: "Basketball", english: "basketball", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_04", native: "Handball", english: "handball", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_05", native: "Volleyball", english: "volleyball", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_06", native: "das Schwimmen", english: "swimming", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_07", native: "schwimmen", english: "to swim", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_08", native: "das Radfahren", english: "cycling", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_09", native: "radfahren", english: "to cycle", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_10", native: "das Wandern", english: "hiking", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_11", native: "wandern", english: "to hike", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_12", native: "das Joggen", english: "jogging", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_13", native: "joggen", english: "to jog", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_14", native: "Ski", english: "ski", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_15", native: "skifahren", english: "to ski", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_16", native: "Ball", english: "ball", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_17", native: "Schläger", english: "racket / bat", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_18", native: "Helm", english: "helmet", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_19", native: "Schuhe", english: "shoes", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_20", native: "Trikot", english: "jersey", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_21", native: "Mannschaft", english: "team", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_22", native: "Spieler", english: "player (male)", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_23", native: "Spielerin", english: "player (female)", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_24", native: "Trainer", english: "coach (male)", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_25", native: "Trainerin", english: "coach (female)", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_26", native: "Platz", english: "court / pitch", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_27", native: "Feld", english: "field", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_28", native: "Halle", english: "sports hall", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_29", native: "Schwimmbad", english: "swimming pool", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_30", native: "Strand", english: "beach", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_31", native: "Wald", english: "forest", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_32", native: "Berg", english: "mountain", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_33", native: "See", english: "lake", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_34", native: "Fluss", english: "river", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_35", native: "Fahrrad", english: "bicycle", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_36", native: "trainieren", english: "to train", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_37", native: "üben", english: "to practice", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_38", native: "gewinnen", english: "to win", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_39", native: "verlieren", english: "to lose", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_40", native: "mitmachen", english: "to join in", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_41", native: "teilnehmen", english: "to participate", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_42", native: "passen", english: "to suit / be suitable", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_43", native: "geeignet", english: "suitable", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_44", native: "ungünstig", english: "unfavorable", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_45", native: "aktiv", english: "active", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_46", native: "fit", english: "fit", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_47", native: "anstrengend", english: "strenuous", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_48", native: "gefährlich", english: "dangerous", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_49", native: "entspannend", english: "relaxing", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_50", native: "herausfordernd", english: "challenging", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_51", native: "Übung", english: "exercise", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_52", native: "Wettkampf", english: "competition", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_53", native: "Sieg", english: "victory", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_54", native: "Niederlage", english: "defeat", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_55", native: "Training", english: "training", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_56", native: "Freizeitaktivität", english: "leisure activity", unit: 2, chapter: 6, type: "noun" },
  { id: "u2_c6_57", native: "trotzdem", english: "nevertheless", unit: 2, chapter: 6, type: "adverb" },
  { id: "u2_c6_58", native: "deshalb", english: "therefore", unit: 2, chapter: 6, type: "adverb" },
  { id: "u2_c6_59", native: "wegen", english: "because of", unit: 2, chapter: 6, type: "preposition" },
  { id: "u2_c6_60", native: "trotz", english: "despite", unit: 2, chapter: 6, type: "preposition" },
  { id: "u2_c6_61", native: "unter", english: "under / in (conditions)", unit: 2, chapter: 6, type: "preposition" },
  { id: "u2_c6_62", native: "sich bewegen", english: "to move / exercise", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_63", native: "auspowern", english: "to work out hard", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_64", native: "wählen", english: "to choose", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_65", native: "entscheiden", english: "to decide", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_66", native: "bevorzugen", english: "to prefer", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_67", native: "vermeiden", english: "to avoid", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_68", native: "abwechseln", english: "to alternate / vary", unit: 2, chapter: 6, type: "verb" },
  { id: "u2_c6_69", native: "sportlich", english: "sporty / athletic", unit: 2, chapter: 6, type: "adjective" },
  { id: "u2_c6_70", native: "draussen aktiv sein", english: "to be active outdoors", unit: 2, chapter: 6, type: "verb" }
]

6;
