export const chapter24 = [
  { id: "u6_c24_01", native: "Wehrdienst", english: "military service", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_02", native: "Wehrpflicht", english: "conscription", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_03", native: "Bundeswehr", english: "German Armed Forces", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_04", native: "Rekrut", english: "recruit", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_05", native: "Grundausbildung", english: "basic training", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_06", native: "Einberufung", english: "call-up order", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_07", native: "Dienstgrad", english: "rank", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_08", native: "Gefreiter", english: "private first class", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_09", native: "Obergefreiter", english: "lance corporal", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_10", native: "Hauptgefreiter", english: "senior private", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_11", native: "Stabsgefreiter", english: "staff private", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_12", native: "Oberstabsgefreiter", english: "senior staff private", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_13", native: "Stabsunteroffizier", english: "staff NCO", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_14", native: "Oberfeldwebel", english: "staff sergeant", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_15", native: "Hauptfeldwebel", english: "master sergeant", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_16", native: "Stabsfeldwebel", english: "sergeant major", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_17", native: "Oberstabsfeldwebel", english: "senior sergeant major", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_18", native: "Oberleutnant", english: "first lieutenant", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_19", native: "Major", english: "major", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_20", native: "Oberstleutnant", english: "lieutenant colonel", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_21", native: "Oberst", english: "colonel", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_22", native: "Brigadegeneral", english: "brigadier general", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_23", native: "Generalmajor", english: "major general", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_24", native: "Generalleutnant", english: "lieutenant general", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_25", native: "Kasernenleben", english: "barracks life", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_26", native: "Übungsgelände", english: "training ground", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_27", native: "Waffe", english: "weapon", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_28", native: "Gewehr", english: "rifle", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_29", native: "Stiefel", english: "boots", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_30", native: "Ausrüstung", english: "equipment", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_31", native: "Auftrag", english: "mission", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_32", native: "Disziplin", english: "discipline", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_33", native: "Kamerad", english: "comrade", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_34", native: "Kameradschaft", english: "camaraderie", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_35", native: "Lehrgang", english: "training course", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_36", native: "Ausbilder", english: "instructor", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_37", native: "Kompanie", english: "company", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_38", native: "Bataillon", english: "battalion", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_39", native: "Regiment", english: "regiment", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_40", native: "Brigade", english: "brigade", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_41", native: "Division", english: "division", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_42", native: "einberufen", english: "to call up", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_43", native: "ausbilden", english: "to train", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_44", native: "befolgen", english: "to obey", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_45", native: "antreten", english: "to fall in", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_46", native: "abtreten", english: "to fall out", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_47", native: "verteidigen", english: "to defend", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_48", native: "kämpfen", english: "to fight", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_49", native: "militärisch", english: "military", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_50", native: "dienstlich", english: "duty-related", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_51", native: "pflichtbewusst", english: "conscientious", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_52", native: "diszipliniert", english: "disciplined", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_53", native: "tapfer", english: "brave", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_54", native: "loyal", english: "loyal", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_55", native: "kameradschaftlich", english: "comradely", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_56", native: "Wehrpflichtiger", english: "conscript", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_57", native: "Zeitsoldat", english: "fixed-term soldier", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_58", native: "Berufssoldat", english: "career soldier", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_59", native: "Reserve", english: "reserve forces", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_60", native: "Reservist", english: "reservist", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_61", native: "Einsatz", english: "deployment", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_62", native: "Auslandseinsatz", english: "overseas deployment", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_63", native: "Friedensmission", english: "peacekeeping mission", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_64", native: "NATO", english: "NATO", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_65", native: "Bündnis", english: "alliance", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_66", native: "Sicherheitspolitik", english: "security policy", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_67", native: "Rekrutierung", english: "recruitment", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_68", native: "Eignungstest", english: "aptitude test", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_69", native: "Musterung", english: "fitness examination", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_70", native: "tauglich", english: "fit for service", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_71", native: "untauglich", english: "unfit for service", unit: 6, chapter: 24, type: "adjective" },
  { id: "u6_c24_72", native: "verweigern", english: "to refuse", unit: 6, chapter: 24, type: "verb" },
  { id: "u6_c24_73", native: "Kriegsdienstverweigerer", english: "conscientious objector", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_74", native: "Zivildienst", english: "alternative civilian service", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_75", native: "Bundesfreiwilligendienst", english: "federal voluntary service", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_76", native: "Kasernenordnung", english: "barracks regulations", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_77", native: "Stubenappell", english: "room inspection", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_78", native: "Wache", english: "guard duty", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_79", native: "Posten", english: "sentry post", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_80", native: "Ablösung", english: "guard relief", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_81", native: "Dienstende", english: "end of service", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_82", native: "Mannschaften", english: "enlisted ranks / crews", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_83", native: "Unteroffizierskorps", english: "NCO corps", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_84", native: "Offizierskorps", english: "officer corps", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_85", native: "Truppe", english: "troops", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_86", native: "Einheit", english: "unit", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_87", native: "Formation", english: "formation", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_88", native: "Drill", english: "drill", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_89", native: "Exerzieren", english: "drill practice", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_90", native: "Schießübung", english: "shooting practice", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_91", native: "Geländeübung", english: "field exercise", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_92", native: "Nachtmarsch", english: "night march", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_93", native: "Biwak", english: "bivouac", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_94", native: "Feldlager", english: "field camp", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_95", native: "Sanitäter", english: "medic", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_96", native: "Feldküche", english: "field kitchen", unit: 6, chapter: 24, type: "noun" },
  { id: "u6_c24_97", native: "Dienstzeit", english: "period of service", unit: 6, chapter: 24, type: "noun" }
];
