export const chapter21 = [
  { id: "u6_c21_01", native: "Wohnung", english: "apartment / flat", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_02", native: "Miete", english: "rent", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_03", native: "Mieter", english: "tenant", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_04", native: "Vermieter", english: "landlord", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_05", native: "Umzug", english: "move / relocation", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_06", native: "Möbel", english: "furniture", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_07", native: "Keller", english: "basement / cellar", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_08", native: "Garage", english: "garage", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_09", native: "Dachboden", english: "attic", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_10", native: "Terrasse", english: "terrace", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_11", native: "Garten", english: "garden", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_12", native: "Hof", english: "courtyard / yard", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_13", native: "Eingang", english: "entrance", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_14", native: "Lift", english: "elevator / lift", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_15", native: "Nebenkosten", english: "additional costs / utilities", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_16", native: "Makler", english: "real estate agent", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_17", native: "Hausverwaltung", english: "property management", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_18", native: "Einzug", english: "move-in", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_19", native: "Auszug", english: "move-out", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_20", native: "Umzugskarton", english: "moving box", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_21", native: "Möbelwagen", english: "moving van", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_22", native: "Wohnungsanzeige", english: "apartment advertisement", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_23", native: "Mietpreis", english: "rental price", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_24", native: "Quadratmeter", english: "square meter", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_25", native: "Etagenwohnung", english: "apartment on a floor", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_26", native: "Erdgeschoss", english: "ground floor", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_27", native: "Obergeschoss", english: "upper floor", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_28", native: "Dachgeschoss", english: "attic floor / loft", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_29", native: "Wohnungsbesichtigung", english: "apartment viewing", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_30", native: "Vertragsende", english: "end of contract", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_31", native: "Kündigungsfrist", english: "notice period", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_32", native: "Wohnungsgeber", english: "landlord (formal)", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_33", native: "Wohnungsnehmer", english: "tenant (formal)", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_34", native: "umziehen", english: "to move house", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_35", native: "einziehen", english: "to move in", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_36", native: "ausziehen", english: "to move out", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_37", native: "renovieren", english: "to renovate", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_38", native: "einrichten", english: "to furnish / set up", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_39", native: "kündigen", english: "to terminate (contract)", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_40", native: "unterschreiben", english: "to sign", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_41", native: "prüfen", english: "to check / inspect", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_42", native: "möbliert", english: "furnished", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_43", native: "unmöbliert", english: "unfurnished", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_44", native: "günstig", english: "inexpensive / affordable", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_45", native: "ruhig", english: "quiet", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_46", native: "zentral", english: "central", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_47", native: "geräumig", english: "spacious", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_48", native: "kompakt", english: "compact", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_49", native: "renoviert", english: "renovated", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_50", native: "unvermietet", english: "unrented / vacant", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_51", native: "vermietet", english: "rented", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_52", native: "hellhörig", english: "poorly soundproofed", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_53", native: "barrierefrei", english: "barrier-free / accessible", unit: 6, chapter: 21, type: "adjective" },
  { id: "u6_c21_54", native: "Wohnfläche", english: "living space / floor area", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_55", native: "Zimmeranzahl", english: "number of rooms", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_56", native: "Kaltmiete", english: "cold rent (excl. utilities)", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_57", native: "Warmmiete", english: "warm rent (incl. utilities)", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_58", native: "Hausgeld", english: "condo fees / house dues", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_59", native: "Eigentümer", english: "owner", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_60", native: "Eigentumswohnung", english: "owner-occupied apartment", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_61", native: "Mietwohnung", english: "rental apartment", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_62", native: "WG", english: "shared apartment", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_63", native: "Mitbewohner", english: "roommate", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_64", native: "Umzugshilfe", english: "moving help", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_65", native: "Spedition", english: "moving company", unit: 6, chapter: 21, type: "noun" },
  { id: "u6_c21_66", native: "einpacken", english: "to pack", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_67", native: "auspacken", english: "to unpack", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_68", native: "transportieren", english: "to transport", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_69", native: "montieren", english: "to install / assemble", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_70", native: "einbauen", english: "to install / build in", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_71", native: "ummelden", english: "to change registration", unit: 6, chapter: 21, type: "verb" },
  { id: "u6_c21_72", native: "registrieren", english: "to register (residence)", unit: 6, chapter: 21, type: "verb" }
];
