export const chapter7 = [
  { id: "u2_c7_01", native: "Stadt", english: "city / town", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_02", native: "Zentrum", english: "center", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_03", native: "Marktplatz", english: "market square", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_04", native: "Weg", english: "way / path", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_05", native: "Richtung", english: "direction", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_06", native: "links", english: "left", unit: 2, chapter: 7, type: "adverb" },
  { id: "u2_c7_07", native: "rechts", english: "right", unit: 2, chapter: 7, type: "adverb" },
  { id: "u2_c7_08", native: "geradeaus", english: "straight ahead", unit: 2, chapter: 7, type: "adverb" },
  { id: "u2_c7_09", native: "Ecke", english: "corner", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_10", native: "Kreuzung", english: "intersection", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_11", native: "Ampel", english: "traffic light", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_12", native: "Brücke", english: "bridge", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_13", native: "Bahnhof", english: "train station", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_14", native: "Haltestelle", english: "stop (bus/tram)", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_15", native: "Bus", english: "bus", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_16", native: "Straßenbahn", english: "tram", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_17", native: "Taxi", english: "taxi", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_18", native: "Fahrkarte", english: "ticket", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_19", native: "Fahrplan", english: "timetable", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_20", native: "umsteigen", english: "to change (means of transport)", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_21", native: "einsteigen", english: "to board / get on", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_22", native: "aussteigen", english: "to get off", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_23", native: "ankommen", english: "to arrive", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_24", native: "abfahren", english: "to depart", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_25", native: "Restaurant", english: "restaurant", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_26", native: "Café", english: "café", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_27", native: "Imbiss", english: "snack bar", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_28", native: "Menü", english: "menu", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_29", native: "Speisekarte", english: "menu card", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_30", native: "bestellen", english: "to order", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_31", native: "bezahlen", english: "to pay", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_32", native: "Rechnung", english: "bill", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_33", native: "Kasse", english: "checkout / cash desk", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_34", native: "Geld", english: "money", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_35", native: "Euro", english: "euro", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_36", native: "Preis", english: "price", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_37", native: "billig", english: "cheap", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_38", native: "teuer", english: "expensive", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_39", native: "kosten", english: "to cost", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_40", native: "Laden", english: "shop", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_41", native: "Geschäft", english: "store / shop", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_42", native: "Supermarkt", english: "supermarket", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_43", native: "kaufen", english: "to buy", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_44", native: "verkaufen", english: "to sell", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_45", native: "nehmen", english: "to take", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_46", native: "geben", english: "to give", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_47", native: "suchen", english: "to look for", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_48", native: "finden", english: "to find", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_49", native: "zeigen", english: "to show", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_50", native: "fragen", english: "to ask", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_51", native: "antworten", english: "to answer", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_52", native: "verstehen", english: "to understand", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_53", native: "bringen", english: "to bring", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_54", native: "warten", english: "to wait", unit: 2, chapter: 7, type: "verb" },
  { id: "u2_c7_55", native: "Bar", english: "cash", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_56", native: "Karte", english: "card (payment)", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_57", native: "Quittung", english: "receipt", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_58", native: "Portion", english: "portion", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_59", native: "Getränk", english: "beverage", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_60", native: "Vorspeise", english: "starter", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_61", native: "Hauptgericht", english: "main course", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_62", native: "Nachtisch", english: "dessert", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_63", native: "Wasser", english: "water", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_64", native: "Brot", english: "bread", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_65", native: "Fleisch", english: "meat", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_66", native: "Gemüse", english: "vegetables", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_67", native: "Obst", english: "fruit", unit: 2, chapter: 7, type: "noun" },
  { id: "u2_c7_68", native: "schnell", english: "fast", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_69", native: "langsam", english: "slow", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_70", native: "nah", english: "near", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_71", native: "weit", english: "far", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_72", native: "direkt", english: "direct", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_73", native: "freundlich", english: "friendly", unit: 2, chapter: 7, type: "adjective" },
  { id: "u2_c7_74", native: "gegenüber", english: "opposite", unit: 2, chapter: 7, type: "preposition" },
  { id: "u2_c7_75", native: "neben", english: "next to", unit: 2, chapter: 7, type: "preposition" },
  { id: "u2_c7_76", native: "zwischen", english: "between", unit: 2, chapter: 7, type: "preposition" },
  { id: "u2_c7_77", native: "hinter", english: "behind", unit: 2, chapter: 7, type: "preposition" },
  { id: "u2_c7_78", native: "über", english: "over / above", unit: 2, chapter: 7, type: "preposition" },
  { id: "u2_c7_79", native: "durch", english: "through", unit: 2, chapter: 7, type: "preposition" },
  { id: "u2_c7_80", native: "entlang", english: "along", unit: 2, chapter: 7, type: "preposition" }
];
