export const chapter4 = [
  { id: "u1_c4_01", native: "Hobby", english: "hobby", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_02", native: "Freizeit", english: "free time / leisure", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_03", native: "Musik", english: "music", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_04", native: "hören", english: "to listen / hear", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_05", native: "Buch", english: "book", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_06", native: "lesen", english: "to read", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_07", native: "Film", english: "film / movie", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_08", native: "sehen", english: "to see / watch", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_09", native: "tanzen", english: "to dance", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_10", native: "singen", english: "to sing", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_11", native: "kochen", english: "to cook", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_12", native: "spielen", english: "to play", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_13", native: "malen", english: "to paint", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_14", native: "zeichnen", english: "to draw", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_15", native: "fotografieren", english: "to photograph", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_16", native: "reisen", english: "to travel", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_17", native: "sammeln", english: "to collect", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_18", native: "Sport", english: "sport", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_19", native: "treiben", english: "to do (sports)", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_20", native: "Kino", english: "cinema", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_21", native: "Konzert", english: "concert", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_22", native: "Theater", english: "theatre", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_23", native: "wollen", english: "to want", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_24", native: "möchten", english: "would like", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_25", native: "werden", english: "to become / will", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_26", native: "vorhaben", english: "to intend / plan to", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_27", native: "Lust", english: "desire / mood", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_28", native: "Spaß", english: "fun", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_29", native: "gerne", english: "gladly / like to", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_30", native: "lieben", english: "to love", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_31", native: "mögen", english: "to like", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_32", native: "interessieren", english: "to interest", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_33", native: "Zukunft", english: "future", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_34", native: "machen", english: "to make / do", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_35", native: "ausprobieren", english: "to try out", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_36", native: "anfangen", english: "to start", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_37", native: "aufhören", english: "to stop", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_38", native: "entspannen", english: "to relax", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_39", native: "genießen", english: "to enjoy", unit: 1, chapter: 4, type: "verb" },
  { id: "u1_c4_40", native: "Freund", english: "friend (male)", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_41", native: "Freundin", english: "friend (female)", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_42", native: "Party", english: "party", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_43", native: "Idee", english: "idea", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_44", native: "Plan", english: "plan", unit: 1, chapter: 4, type: "noun" },
  { id: "u1_c4_45", native: "vielleicht", english: "maybe", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_46", native: "sicher", english: "sure / certain", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_47", native: "möglich", english: "possible", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_48", native: "interessant", english: "interesting", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_49", native: "langweilig", english: "boring", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_50", native: "neu", english: "new", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_51", native: "alt", english: "old", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_52", native: "groß", english: "big / large", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_53", native: "klein", english: "small", unit: 1, chapter: 4, type: "adjective" },
  { id: "u1_c4_54", native: "auch", english: "also / too", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_55", native: "nur", english: "only", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_56", native: "noch", english: "still / yet", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_57", native: "schon", english: "already", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_58", native: "wieder", english: "again", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_59", native: "zusammen", english: "together", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_60", native: "allein", english: "alone", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_61", native: "gern", english: "gladly (short form)", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_62", native: "lieber", english: "preferably / rather", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_63", native: "am liebsten", english: "most preferably", unit: 1, chapter: 4, type: "adverb" },
  { id: "u1_c4_64", native: "was", english: "what", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_65", native: "wer", english: "who", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_66", native: "wo", english: "where", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_67", native: "wann", english: "when", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_68", native: "warum", english: "why", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_69", native: "wie", english: "how", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_70", native: "mein", english: "my", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_71", native: "dein", english: "your (informal)", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_72", native: "ihr", english: "her / their", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_73", native: "unser", english: "our", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_74", native: "euer", english: "your (plural informal)", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_75", native: "dieser", english: "this / that", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_76", native: "jeder", english: "every / each", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_77", native: "alle", english: "all", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_78", native: "etwas", english: "something", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_79", native: "nichts", english: "nothing", unit: 1, chapter: 4, type: "pronoun" },
  { id: "u1_c4_80", native: "jemand", english: "someone", unit: 1, chapter: 4, type: "pronoun" }
];
