export const chapter5 = [
  { id: "u2_c5_01", native: "zuerst", english: "first / at first", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_02", native: "dann", english: "then", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_03", native: "danach", english: "after that / afterwards", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_04", native: "später", english: "later", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_05", native: "schließlich", english: "finally / eventually", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_06", native: "bevor", english: "before", unit: 2, chapter: 5, type: "conjunction" },
  { id: "u2_c5_07", native: "nachdem", english: "after", unit: 2, chapter: 5, type: "conjunction" },
  { id: "u2_c5_08", native: "während", english: "during / while", unit: 2, chapter: 5, type: "preposition" },
  { id: "u2_c5_09", native: "gleichzeitig", english: "at the same time", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_10", native: "sobald", english: "as soon as", unit: 2, chapter: 5, type: "conjunction" },
  { id: "u2_c5_11", native: "mittags", english: "at midday", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_12", native: "nachmittags", english: "in the afternoon", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_13", native: "nachts", english: "at night", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_14", native: "vormittags", english: "in the morning (before noon)", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_15", native: "täglich", english: "daily", unit: 2, chapter: 5, type: "adverb" },
  { id: "u2_c5_16", native: "aufräumen", english: "to tidy up", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_17", native: "spülen", english: "to rinse / do the dishes", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_18", native: "abwaschen", english: "to wash the dishes", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_19", native: "staubsaugen", english: "to vacuum", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_20", native: "wischen", english: "to wipe / mop", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_21", native: "fegen", english: "to sweep", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_22", native: "bügeln", english: "to iron", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_23", native: "trocknen", english: "to dry", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_24", native: "falten", english: "to fold", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_25", native: "einräumen", english: "to put away", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_26", native: "ausräumen", english: "to clear out / empty", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_27", native: "helfen", english: "to help", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_28", native: "brauchen", english: "to need", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_29", native: "haben", english: "to have", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_30", native: "erledigen", english: "to complete / take care of", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_31", native: "schreiben", english: "to write", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_32", native: "tippen", english: "to type", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_33", native: "drucken", english: "to print", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_34", native: "senden", english: "to send", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_35", native: "empfangen", english: "to receive", unit: 2, chapter: 5, type: "verb" },
  { id: "u2_c5_36", native: "Aufgabe", english: "task / assignment", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_37", native: "Besprechung", english: "meeting", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_38", native: "Kollege", english: "colleague (male)", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_39", native: "Kollegin", english: "colleague (female)", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_40", native: "Chef", english: "boss (male)", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_41", native: "Chefin", english: "boss (female)", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_42", native: "Küche", english: "kitchen", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_43", native: "Bad", english: "bathroom", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_44", native: "Wohnzimmer", english: "living room", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_45", native: "Schlafzimmer", english: "bedroom", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_46", native: "Boden", english: "floor", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_47", native: "Teppich", english: "carpet / rug", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_48", native: "Geschirr", english: "dishes", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_49", native: "Müll", english: "trash / rubbish", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_50", native: "Wäsche", english: "laundry", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_51", native: "Reinigung", english: "cleaning", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_52", native: "Spüle", english: "sink", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_53", native: "Regal", english: "shelf", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_54", native: "Schrank", english: "cupboard / closet", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_55", native: "Tisch", english: "table", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_56", native: "Stuhl", english: "chair", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_57", native: "Sofa", english: "sofa", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_58", native: "Lampe", english: "lamp", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_59", native: "Computer", english: "computer", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_60", native: "E-Mail", english: "email", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_61", native: "Dokument", english: "document", unit: 2, chapter: 5, type: "noun" },
  { id: "u2_c5_62", native: "sauber", english: "clean", unit: 2, chapter: 5, type: "adjective" },
  { id: "u2_c5_63", native: "schmutzig", english: "dirty", unit: 2, chapter: 5, type: "adjective" },
  { id: "u2_c5_64", native: "ordentlich", english: "tidy / neat", unit: 2, chapter: 5, type: "adjective" },
  { id: "u2_c5_65", native: "unordentlich", english: "messy / untidy", unit: 2, chapter: 5, type: "adjective" }
];
