export const chapter16 = [
  { id: "u4_c16_01", native: "Mietwagen", english: "rental car", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_02", native: "mieten", english: "to rent", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_03", native: "vermieten", english: "to rent out", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_04", native: "Führerschein", english: "driving licence", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_05", native: "internationaler Führerschein", english: "international driving permit", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_06", native: "Versicherung", english: "insurance", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_07", native: "Vollkasko", english: "fully comprehensive insurance", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_08", native: "Teilkasko", english: "partial cover insurance", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_09", native: "Kaution", english: "deposit / security", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_10", native: "Kilometerstand", english: "mileage / odometer reading", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_11", native: "tanken", english: "to refuel", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_12", native: "volltanken", english: "to fill up the tank", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_13", native: "Rückgabe", english: "return (of vehicle)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_14", native: "Übergabe", english: "handover", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_15", native: "Schaden", english: "damage", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_16", native: "Kratzer", english: "scratch", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_17", native: "Delle", english: "dent", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_18", native: "Besichtigung", english: "tour / visit (of a site)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_19", native: "Führung", english: "guided tour", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_20", native: "Stadtführung", english: "city tour", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_21", native: "Aussicht", english: "view / vista", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_22", native: "Turm", english: "tower", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_23", native: "Burg", english: "castle (fortified)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_24", native: "Dom", english: "cathedral", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_25", native: "Kathedrale", english: "cathedral", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_26", native: "Festung", english: "fortress", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_27", native: "Palast", english: "palace", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_28", native: "Residenz", english: "residence / royal palace", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_29", native: "UNESCO", english: "UNESCO", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_30", native: "Welterbe", english: "World Heritage", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_31", native: "Statue", english: "statue", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_32", native: "Brunnen", english: "fountain", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_33", native: "Schlosspark", english: "palace park / castle grounds", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_34", native: "Galerie", english: "gallery", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_35", native: "Sonderausstellung", english: "special exhibition", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_36", native: "Eintritt", english: "admission / entrance fee", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_37", native: "Audioguide", english: "audio guide", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_38", native: "Gruppe", english: "group", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_39", native: "individuell", english: "individual (tour)", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_40", native: "Sehenswürdigkeiten", english: "sights / places of interest", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_41", native: "Stadtrundgang", english: "city walk / walking tour", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_42", native: "Aussichtspunkt", english: "viewpoint", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_43", native: "Aussichtsturm", english: "observation tower", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_44", native: "Schlossführung", english: "castle tour", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_45", native: "Mietvertrag", english: "rental contract", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_46", native: "Kilometerpauschale", english: "mileage allowance", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_47", native: "Selbstbeteiligung", english: "excess / deductible", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_48", native: "Zusatzversicherung", english: "additional insurance", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_49", native: "Navigationsgerät", english: "navigation device", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_50", native: "Kindersitz", english: "child seat", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_51", native: "Winterreifen", english: "winter tyres", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_52", native: "Sommerreifen", english: "summer tyres", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_53", native: "Tankfüllung", english: "tank of fuel", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_54", native: "voll", english: "full (tank)", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_55", native: "leer", english: "empty (tank)", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_56", native: "zurückgeben", english: "to return (vehicle)", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_57", native: "übernehmen", english: "to take over / collect (rental car)", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_58", native: "besichtigen", english: "to visit / tour (a site)", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_59", native: "ansehen", english: "to look at / view (a sight)", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_60", native: "entdecken", english: "to discover", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_61", native: "ablichten", english: "to photograph / capture", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_62", native: "bewundern", english: "to admire", unit: 4, chapter: 16, type: "verb" },
  { id: "u4_c16_63", native: "Neuschwanstein", english: "Neuschwanstein Castle", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_64", native: "Kölner Dom", english: "Cologne Cathedral", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_65", native: "Heidelberger Schloss", english: "Heidelberg Castle", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_66", native: "Wartburg", english: "Wartburg Castle", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_67", native: "Sanssouci", english: "Sanssouci Palace", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_68", native: "Zwinger", english: "Zwinger (Dresden)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_69", native: "Frauenkirche", english: "Church of Our Lady (Dresden)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_70", native: "Marienplatz", english: "Marienplatz (Munich)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_71", native: "Hofbräuhaus", english: "Hofbräuhaus", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_72", native: "Römer", english: "Römer (Frankfurt city hall)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_73", native: "Speicherstadt", english: "Speicherstadt (Hamburg)", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_74", native: "Elbphilharmonie", english: "Elbphilharmonie", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_75", native: "Kulturdenkmal", english: "cultural monument", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_76", native: "Baudenkmal", english: "architectural monument", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_77", native: "Denkmalpflege", english: "monument preservation", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_78", native: "geschichtlich", english: "historical", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_79", native: "mittelalterlich", english: "medieval", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_80", native: "barock", english: "baroque", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_81", native: "romantisch", english: "romantic", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_82", native: "sehenswert", english: "worth seeing", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_83", native: "beeindruckend", english: "impressive", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_84", native: "einzigartig", english: "unique", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_85", native: "berühmt", english: "famous", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_86", native: "touristisch", english: "touristy", unit: 4, chapter: 16, type: "adjective" },
  { id: "u4_c16_87", native: "Andenken", english: "souvenir", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_88", native: "Prospekt", english: "brochure / leaflet", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_89", native: "Öffnungszeiten", english: "opening hours", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_90", native: "Eintrittskarte", english: "admission ticket", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_91", native: "Warteschlange", english: "queue / waiting line", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_92", native: "Vorverkauf", english: "advance sale / box office", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_93", native: "Onlinebuchung", english: "online booking", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_94", native: "Freizeitpark", english: "amusement park", unit: 4, chapter: 16, type: "noun" },
  { id: "u4_c16_95", native: "Themenpark", english: "theme park", unit: 4, chapter: 16, type: "noun" }
];
