export const chapter17 = [
  { id: "u5_c17_01", native: "Bühne", english: "stage", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_02", native: "Saal", english: "hall / auditorium", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_03", native: "Loge", english: "box (theatre)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_04", native: "Parkett", english: "stalls / orchestra level", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_05", native: "Vorhang", english: "curtain", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_06", native: "Leinwand", english: "screen (cinema)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_07", native: "Balkon", english: "balcony (theatre)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_08", native: "Opernhaus", english: "opera house", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_09", native: "Philharmonie", english: "concert hall / philharmonic", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_10", native: "Festival", english: "festival", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_11", native: "Open-Air", english: "open-air (event)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_12", native: "Schauspieler", english: "actor", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_13", native: "Schauspielerin", english: "actress", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_14", native: "Regisseur", english: "director (film/theatre)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_15", native: "Regisseurin", english: "female director", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_16", native: "Dirigent", english: "conductor", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_17", native: "Dirigentin", english: "female conductor", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_18", native: "Sänger", english: "singer (male)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_19", native: "Sängerin", english: "singer (female)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_20", native: "Zuschauer", english: "spectator / audience member", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_21", native: "Publikum", english: "audience / public", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_22", native: "Kritiker", english: "critic", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_23", native: "Kritik", english: "review / criticism", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_24", native: "Rezension", english: "written review", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_25", native: "Komödie", english: "comedy", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_26", native: "Tragödie", english: "tragedy", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_27", native: "Musical", english: "musical", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_28", native: "Oper", english: "opera", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_29", native: "Ballett", english: "ballet", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_30", native: "Sinfonie", english: "symphony", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_31", native: "Premiere", english: "premiere", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_32", native: "Vorstellung", english: "performance / show", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_33", native: "Aufführung", english: "performance / staging", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_34", native: "Akt", english: "act (of a play)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_35", native: "Zugabe", english: "encore", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_36", native: "Genre", english: "genre", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_37", native: "Handlung", english: "plot / storyline", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_38", native: "Hauptrolle", english: "leading role", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_39", native: "Nebenrolle", english: "supporting role", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_40", native: "Drehbuch", english: "screenplay / script", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_41", native: "Regie", english: "direction (film/theatre)", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_42", native: "Applaus", english: "applause", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_43", native: "Meinung", english: "opinion", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_44", native: "Lieblingsfilm", english: "favourite film", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_45", native: "Lieblingsstück", english: "favourite piece / play", unit: 5, chapter: 17, type: "noun" },
  { id: "u5_c17_46", native: "aufführen", english: "to perform / stage", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_47", native: "proben", english: "to rehearse", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_48", native: "klatschen", english: "to clap / applaud", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_49", native: "gefallen", english: "to please / to like (es gefällt mir)", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_50", native: "kritisieren", english: "to criticise", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_51", native: "loben", english: "to praise", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_52", native: "bewerten", english: "to rate / evaluate", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_53", native: "raten", english: "to advise / recommend", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_54", native: "vorschlagen", english: "to suggest", unit: 5, chapter: 17, type: "verb" },
  { id: "u5_c17_55", native: "spannend", english: "exciting / thrilling", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_56", native: "faszinierend", english: "fascinating", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_57", native: "spektakulär", english: "spectacular", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_58", native: "genial", english: "brilliant / ingenious", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_59", native: "mittelmäßig", english: "mediocre / average", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_60", native: "unterhaltsam", english: "entertaining", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_61", native: "berührend", english: "touching / moving", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_62", native: "originell", english: "original", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_63", native: "begeistert", english: "enthusiastic / thrilled", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_64", native: "enttäuscht", english: "disappointed", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_65", native: "großartig", english: "great / magnificent", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_66", native: "schwach", english: "weak (performance)", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_67", native: "emotional", english: "emotional", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_68", native: "humorvoll", english: "humorous", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_69", native: "dramatisch", english: "dramatic", unit: 5, chapter: 17, type: "adjective" },
  { id: "u5_c17_70", native: "absolut", english: "absolutely", unit: 5, chapter: 17, type: "adverb" },
  { id: "u5_c17_71", native: "total", english: "totally", unit: 5, chapter: 17, type: "adverb" },
  { id: "u5_c17_72", native: "besonders", english: "especially / particularly", unit: 5, chapter: 17, type: "adverb" },
  { id: "u5_c17_73", native: "überhaupt", english: "at all / in general", unit: 5, chapter: 17, type: "adverb" },
];
