export const chapter19 = [
  { id: "u5_c19_01", native: "Tor", english: "goal (sports)", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_02", native: "Torwart", english: "goalkeeper", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_03", native: "Schiedsrichter", english: "referee", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_04", native: "Abseits", english: "offside", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_05", native: "Elfmeter", english: "penalty kick", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_06", native: "Freistoß", english: "free kick", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_07", native: "Eckball", english: "corner kick", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_08", native: "Medaille", english: "medal", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_09", native: "Pokal", english: "cup / trophy", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_10", native: "Meisterschaft", english: "championship", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_11", native: "Liga", english: "league", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_12", native: "Verein", english: "sports club", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_13", native: "Schienbeinschoner", english: "shin pad", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_14", native: "Netz", english: "net", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_15", native: "Korb", english: "basket (basketball)", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_16", native: "Racket", english: "racket", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_17", native: "Trikotsatz", english: "team kit", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_18", native: "Auswechslung", english: "substitution", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_19", native: "Halbzeit", english: "half-time", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_20", native: "Verlängerung", english: "extra time", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_21", native: "Elfmeterschießen", english: "penalty shoot-out", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_22", native: "Siegertreppchen", english: "podium", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_23", native: "Rekord", english: "record", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_24", native: "Weltmeister", english: "world champion", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_25", native: "Olympiasieger", english: "Olympic champion", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_26", native: "Trainingseinheit", english: "training session", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_27", native: "Aufwärmen", english: "warm-up", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_28", native: "Dehnen", english: "stretching", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_29", native: "Kondition", english: "fitness / stamina", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_30", native: "Technik", english: "technique", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_31", native: "Taktik", english: "tactics", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_32", native: "Angriff", english: "attack", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_33", native: "Verteidigung", english: "defence", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_34", native: "Ballpass", english: "pass (ball)", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_35", native: "Dribbling", english: "dribbling", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_36", native: "Kopfball", english: "header", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_37", native: "Volley", english: "volley", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_38", native: "schießen", english: "to shoot (ball)", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_39", native: "zuspielen", english: "to pass (to teammate)", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_40", native: "köpfen", english: "to head the ball", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_41", native: "abwehren", english: "to save / block", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_42", native: "auswechseln", english: "to substitute", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_43", native: "wettkämpfen", english: "to compete", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_44", native: "siegen", english: "to win", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_45", native: "unterliegen", english: "to lose / be defeated", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_46", native: "Hund", english: "dog", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_47", native: "Katze", english: "cat", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_48", native: "Pferd", english: "horse", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_49", native: "Kuh", english: "cow", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_50", native: "Schwein", english: "pig", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_51", native: "Schaf", english: "sheep", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_52", native: "Ziege", english: "goat", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_53", native: "Huhn", english: "chicken", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_54", native: "Hahn", english: "rooster", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_55", native: "Ente", english: "duck", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_56", native: "Gans", english: "goose", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_57", native: "Vogel", english: "bird", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_58", native: "Maus", english: "mouse", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_59", native: "Kaninchen", english: "rabbit", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_60", native: "Hase", english: "hare", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_61", native: "Fuchs", english: "fox", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_62", native: "Hirsch", english: "deer", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_63", native: "Wildschwein", english: "wild boar", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_64", native: "Esel", english: "donkey", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_65", native: "Pony", english: "pony", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_66", native: "Bauer", english: "farmer", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_67", native: "Bäuerin", english: "female farmer", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_68", native: "Bauernhof", english: "farm", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_69", native: "Stall", english: "stable", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_70", native: "Weide", english: "pasture", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_71", native: "Scheune", english: "barn", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_72", native: "Traktor", english: "tractor", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_73", native: "Pflug", english: "plough", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_74", native: "Ernte", english: "harvest", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_75", native: "säen", english: "to sow", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_76", native: "ernten", english: "to harvest", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_77", native: "melken", english: "to milk", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_78", native: "füttern", english: "to feed animals", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_79", native: "züchten", english: "to breed", unit: 5, chapter: 19, type: "verb" },
  { id: "u5_c19_80", native: "Stallarbeit", english: "stable work", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_81", native: "Feldarbeit", english: "field work", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_82", native: "Landwirt", english: "agriculturalist / farmer", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_83", native: "Landwirtschaft", english: "agriculture", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_84", native: "Biohof", english: "organic farm", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_85", native: "Freilauf", english: "free-range system", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_86", native: "Stallhaltung", english: "indoor housing", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_87", native: "Dung", english: "manure", unit: 5, chapter: 19, type: "noun" },
  { id: "u5_c19_88", native: "Heu", english: "hay", unit: 5, chapter: 19, type: "noun" },
];
