export const chapter10 = [
  { id: "u3_c10_01", native: "U-Bahn", english: "subway / underground", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_02", native: "S-Bahn", english: "suburban train / city rail", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_03", native: "Auto", english: "car", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_04", native: "Motorrad", english: "motorcycle", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_05", native: "Roller", english: "scooter", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_06", native: "Fähre", english: "ferry", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_07", native: "Schiff", english: "ship", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_08", native: "Fahrradweg", english: "bike path / cycle lane", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_09", native: "Fußgänger", english: "pedestrian", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_10", native: "Fußgängerzone", english: "pedestrian zone", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_11", native: "Pendler", english: "commuter", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_12", native: "pendeln", english: "to commute", unit: 3, chapter: 10, type: "verb" },
  { id: "u3_c10_13", native: "Fahrgemeinschaft", english: "carpool", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_14", native: "Mitfahrer", english: "passenger / rider", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_15", native: "besser", english: "better", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_16", native: "schlechter", english: "worse", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_17", native: "größer", english: "bigger / larger", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_18", native: "kleiner", english: "smaller", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_19", native: "schneller", english: "faster", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_20", native: "langsamer", english: "slower", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_21", native: "teurer", english: "more expensive", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_22", native: "billiger", english: "cheaper", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_23", native: "mehr", english: "more", unit: 3, chapter: 10, type: "adverb" },
  { id: "u3_c10_24", native: "weniger", english: "less / fewer", unit: 3, chapter: 10, type: "adverb" },
  { id: "u3_c10_25", native: "als", english: "than (comparison)", unit: 3, chapter: 10, type: "conjunction" },
  { id: "u3_c10_26", native: "bester", english: "best", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_27", native: "schlimmster", english: "worst", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_28", native: "Familie", english: "family", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_29", native: "Mutter", english: "mother", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_30", native: "Vater", english: "father", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_31", native: "Eltern", english: "parents", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_32", native: "Bruder", english: "brother", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_33", native: "Schwester", english: "sister", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_34", native: "Sohn", english: "son", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_35", native: "Tochter", english: "daughter", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_36", native: "Kind", english: "child", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_37", native: "Großmutter", english: "grandmother", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_38", native: "Großvater", english: "grandfather", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_39", native: "Oma", english: "grandma", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_40", native: "Opa", english: "grandpa", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_41", native: "Onkel", english: "uncle", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_42", native: "Tante", english: "aunt", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_43", native: "Cousin", english: "male cousin", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_44", native: "Cousine", english: "female cousin", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_45", native: "Verwandte", english: "relative (female / plural)", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_46", native: "Verwandter", english: "relative (male)", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_47", native: "Nichte", english: "niece", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_48", native: "Neffe", english: "nephew", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_49", native: "Schwiegermutter", english: "mother-in-law", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_50", native: "Schwiegervater", english: "father-in-law", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_51", native: "Ehepartner", english: "spouse", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_52", native: "Ehemann", english: "husband", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_53", native: "Ehefrau", english: "wife", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_54", native: "Partner", english: "partner (male)", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_55", native: "Partnerin", english: "partner (female)", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_56", native: "verheiratet", english: "married", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_57", native: "ledig", english: "single / unmarried", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_58", native: "geschieden", english: "divorced", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_59", native: "verwitwet", english: "widowed", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_60", native: "älter", english: "older", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_61", native: "jünger", english: "younger", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_62", native: "gleich", english: "same / equal", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_63", native: "ähnlich", english: "similar", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_64", native: "unterschiedlich", english: "different", unit: 3, chapter: 10, type: "adjective" },
  { id: "u3_c10_65", native: "Vergleich", english: "comparison", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_66", native: "vergleichen", english: "to compare", unit: 3, chapter: 10, type: "verb" },
  { id: "u3_c10_67", native: "Transportmittel", english: "means of transport", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_68", native: "zu Fuß", english: "on foot", unit: 3, chapter: 10, type: "adverb" },
  { id: "u3_c10_69", native: "Autobahn", english: "highway / motorway", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_70", native: "Landstraße", english: "country road", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_71", native: "Stau", english: "traffic jam", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_72", native: "Parkplatz", english: "parking space / lot", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_73", native: "Parkhaus", english: "parking garage", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_74", native: "Tankstelle", english: "gas station / petrol station", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_75", native: "Benzin", english: "petrol / gasoline", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_76", native: "Diesel", english: "diesel", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_77", native: "Elektromotor", english: "electric motor", unit: 3, chapter: 10, type: "noun" },
  { id: "u3_c10_78", native: "Hybrid", english: "hybrid", unit: 3, chapter: 10, type: "noun" }
];
